### ISSUE TITLE
Crypto : "Send all"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1013]
send all remaiining crypto of a of an account

**Comment by HugoNDO** [comment]
Figma screens if needed : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2351%3A10620&t=ewyJZWWW7OfndPL6-1

**Comment by hawkbee1** [comment]
Looks like it's already working properly
