### ISSUE TITLE
New Talao Wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1025]
same code as Altme

do not display NFT and Crypto screens but keep drawers with crypto features

Change logo with Talao logo

Change background corl and font  for a light application

Adapt text of the splash screen -> Nicolas

Push on teh store as th" "Talao wallet"

**Comment by hawkbee1** [comment]
first version version same code as Altme

do not display NFT and Crypto screens but keep drawers with crypto features

Change logo with Talao logo

**Comment by hawkbee1** [comment]
Size: M
