### ISSUE TITLE
Add categories (advance settings) in new drawer menu

### ISSUE THREAD

**Issue by TalebRafiepour** [TalaoDAO/AltMe#1054]
@HugoNDO @ThierryThevenet   the "Categories" page (advance settings to choose which category to show in credential list page) not supported in new Figma design of the drawer menu

**Comment by ThierryThevenet** [comment]
to be discussed the category now should appera if there is a card only ?

**Comment by HugoNDO** [comment]
Yes exactly

**Comment by HugoNDO** [comment]
Categories will be displayed in "Discover" when we have suggestion for users. But they will only appear in "My wallet" if there is at least one card in a category 👍

**Comment by hawkbee1** [comment]
=> @TalebRafiepour lets's have all categories actives by default. This means category will appear as soon as there is a credential inside it.

**Comment by hawkbee1** [comment]
Size: S
