### ISSUE TITLE
Dynamic CredentiaOffer credential requested

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1060]
When a credentrialOffer requests credential ti present, display the requested credentials dynamically

**Comment by hawkbee1** [comment]
Credential offer => When presenting credentials  to get a new credential, we can now pick several credential at once.

**Comment by hawkbee1** [comment]
Size: M

**Comment by ThierryThevenet** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4637%3A12144&t=kYmR9ZdO24afGpF2-0

**Comment by ThierryThevenet** [comment]
must replace this screen which is not correct


![Image](https://user-images.githubusercontent.com/32768069/208745601-827dec8c-62e5-4c76-8ef2-fb9704bf2085.jpg)
