### ISSUE TITLE
REstore credentials now in two steps

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1070]
- The alert design and text has been updated
- Pin code is needed
![image](https://user-images.githubusercontent.com/49282360/206153593-36fa4d9f-e30f-4044-a6ea-27012ed1db0c.png)

Recovery phrase and file upload are now splited in two steps
![image](https://user-images.githubusercontent.com/49282360/206153863-90f1a53d-cda3-4fb8-a97c-751827efe445.png)

**Comment by TalebRafiepour** [comment]
@hawkbee1 you mean BackupCredential right?

**Comment by TalebRafiepour** [comment]
@hawkbee1 Nevemind, I got your point
