### ISSUE TITLE
NFT : update NFT detail screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1076]
display Metadata attribute if not null after description

Creators :
Publishers :
Date creation : (without seconds)

and no send button is not transferable (previous ticket)

**Comment by ThierryThevenet** [comment]
+ identifier

**Comment by ThierryThevenet** [comment]
example of metada of our SBT

https://ghostnet.tzkt.io/KT1JwgHTpo4NZz6jKK89rx3uEo9L5kLY1FQe/tokens/21/metadata

**Comment by hawkbee1** [comment]
Size: S
