### ISSUE TITLE
Didkit issue

### ISSUE THREAD

**Issue by SteveDevs** [TalaoDAO/AltMe#1097]
Having a runtime error with Didkit
Im running a dev env using ubuntu 22.

I have installed didkit already.

The application runs fine, untill i need to create a wallet. When i press continue on the screen where it says "Please, write down your Recovery Phrase", it throws "something went wrong when generating a key".

I added a stacktrace below of the catch clause.

I/flutter (12334): ⛔  | OnBoardingGenPhraseCubit | something went wrong when generating a key
I/flutter (12334): ⛔  | OnBoardingGenPhraseCubit | Invalid argument(s): Failed to load dynamic library 'libdidkit.so': dlopen failed: library "libdidkit.so" not found
I/flutter (12334): ⛔  | OnBoardingGenPhraseCubit | #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
I/flutter (12334): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
I/flutter (12334): #2      lib
package:didkit/didkit.dart:9
I/flutter (12334): #3      lib (package:didkit/didkit.dart)
package:didkit/didkit.dart:1
I/flutter (12334): #4      key_to_did
package:didkit/didkit.dart:29
I/flutter (12334): #5      key_to_did (package:didkit/didkit.dart)
package:didkit/didkit.dart:1
I/flutter (12334): #6      DIDKit.keyToDID
package:didkit/didkit.dart:119
I/flutter (12334): #7      DIDKitProvider.keyToDID
package:did_kit/src/did_kit_provider.dart:13
I/flutter (12334): #8      OnBoardingGenPhraseCubit.generateSSIAndCryptoAccount
package:altme/…/cubit/onboarding_gen_phrase_cubit.dart:62
I/flutter (12334): <asynchronous suspension>
I/flutter (12334): #9      OnBoardingGenPhraseView.build.<anonymous closure>.<anonymous closure>
package:altme/…/view/onboarding_gen_phrase.dart:195
I/flutter (12334): <asynchronous suspension>

To add to this, i removed the .env flutter: assets from the root pubspec.yaml, not sure if this has an effect on above error?

Thanks

**Comment by hawkbee1** [comment]
Every times when I have this "Failed to load dynamic library 'libdidkit.so': dlopen failed" error, it means:
- Either DIDKit installation failed and you should have an error in your DIDKit installation log
- Either you're using a non physical device: So far DIDKit is not loaded on simulator/emulator
