### ISSUE TITLE
CredentialOffer, credential manifest, input descriptors, "optional" attribute

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1098]
https://identity.foundation/presentation-exchange/spec/v2.0.0/#input-descriptor

The objective is to allow request optional credentials.
If the optional attribute is "True", user can skip to present the requested credential

-> add skip in the screen to present the credential

**Comment by hawkbee1** [comment]
Size: M But S if just after ticket

**Comment by hawkbee1** [comment]
here is the definition of optional from specs: https://identity.foundation/presentation-exchange/spec/v2.0.0/#input-descriptor
![Image](https://user-images.githubusercontent.com/49282360/207827188-46b3ece1-a2e8-4ea6-89bd-59a6984b2e89.png)

**Comment by ThierryThevenet** [comment]
for testing  https://talao.co/sandbox/direct_offer?VC=GamerPass.jsonld
