### ISSUE TITLE
"Update your application" system

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1100]
For security reason it's important to keep Altme up to date.
When app is launching it checks if current app version is < to last prod version. If that's the case we force user to update Altme.
In this case  we should offer possibility of backing up credentials?
To Be Defined: Where and how are we storing info about last production version? Is there an official mechanism with the stores?

**Comment by bibash28** [comment]
Check branch `app_update` later

**Comment by bibash28** [comment]
I found some packages but all are doing web scrapping which means that the package breaks when UI changes occur or some changes occur in the website... We need to make one API to fetch the latest version, release notes, etc. By doing this it will be stable forever. The only extra step will be we need to update the API response every time we release the new version.

**Comment by bibash28** [comment]
https://pub.dev/packages/new_version

**Comment by ThierryThevenet** [comment]
ok not urgent

**Comment by bibash28** [comment]
ok

**Comment by bibash28** [comment]
I think we need to do some test releases of the branch https://github.com/TalaoDAO/AltMe/tree/app_update
and check...

I have tried to do in app update for android... link direct for ios...
also we need to check if after app gets update the app is auto restarted or not
