### ISSUE TITLE
Wallet connect , add  other Blockchain Network in drawer and for walletconnect initiialisation

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1103]
Ethereum testnet Goerli  https://docs.infura.io/infura/networks/ethereum/how-to/choose-a-network

add Fantom Network and the Fantom testnet  https://rpc.testnet.fantom.network/ 

add Polygon and the polygon testnet

add Fuse

add Avalanche and the avalancje testnet

add Binance smart chain and the testnet

See RPC endpoint https://rpc.info/

By default in the drawer Tezos mainnet, Ethereum mainet, Polygon mainnet, avalanche mainnet,  fantom mainnet and Binance mainnet  are selected

**Comment by hawkbee1** [comment]
Size: S
