### ISSUE TITLE
Add PolygonAssociatedAddress and FantomAssociatedAddress

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1106]
same principle as EthereumAssociatedAddress

see Design of the card in Figma

https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/FantomAssociatedAddress.jsonld

https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/PolygonAssociatedAddress.jsonld

updatre create account and update  account to intagrate those new credntials

**Comment by bibash28** [comment]
Size: L
