### ISSUE TITLE
Beacon on Android : cannot connect to Tezotopia from android smartphone (same device)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1113]
The Beacon popup does not show mobile wallet as it is from IOS.
![Screenshot_20221217-132600_Chrome](https://user-images.githubusercontent.com/32768069/208241811-366e9e4c-7842-4ae3-b89b-4765725fd3b9.jpg)

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/210208248-5d6cd35d-719e-4910-8317-dd49b94050ab.png)
