### ISSUE TITLE
presentationRequest protocol 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1150]
Same as credentialOffer : 
when the user does not have the requested credential, display the card with a link to get it

**Comment by bibash28** [comment]
I need test URLs for this... 

https://talao.co/wallet/test/presentationRequest
The above URL is not working...

And where will the required credentials be listed.. inside the credential manifest???

@ThierryThevenet @hawkbee1

**Comment by ThierryThevenet** [comment]
you can test it here 
https://talao.co/sandbox/presentationRequest
the protocole is here
https://sandbox-doc.readthedocs.io/en/latest/altme.html#altme-wallet-presentation-request-query-types

**Comment by ThierryThevenet** [comment]
it is less complex that the imput descriptors with JsonPath

**Comment by bibash28** [comment]
Size: S/M
