### ISSUE TITLE
APP check, integrity of the wallet code and device. to give assurance to verifiers and issuers

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1156]
The verification check should be integrated in the DeviceInfo credental

https://firebase.google.com/docs/app-check/flutter/default-providers

**Comment by ThierryThevenet** [comment]
https://firebase.google.com/docs/app-check/flutter/default-providers

to integrate in the deviceInfo

**Comment by bibash28** [comment]
This feature needs integration of firebase in our project.

**Comment by bibash28** [comment]
A Firebase project needs to be created. @ThierryThevenet  @hawkbee1

**Comment by bibash28** [comment]
and need to add me as a **developer**

**Comment by bibash28** [comment]
https://www.youtube.com/watch?v=Fjj4fmr2t04
