### ISSUE TITLE
Update DeviceInfo with Altme build number

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1164]
new credential :
https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/DeviceInfo.jsonld

new credential manifest
https://github.com/TalaoDAO/wallet-tools/blob/main/credential_manifest/DeviceInfo_credential_manifest.json

**Comment by bibash28** [comment]
Size: S

**Comment by bibash28** [comment]
![image](https://user-images.githubusercontent.com/18188709/210358002-a9e17c81-95f7-4a3b-8c09-0af20b990278.png)
