### ISSUE TITLE
Remove possibility of copying sensitive data to clipboard

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1168]
[Info] Sensitive data can be copied to the clipboard
- mnemonics during wallet creation
- did keys
- private keys of blockchain accounts
[Sensitive data should not be copied to clipboard as other applications can access it](https://github.com/MobSF/owasp-mstg/blob/master/Document/0x04b-Mobile-App-Security-Testing.md#clipboard). The clipboard is accessible system-wide and is therefore shared by apps. This sharing can be misused by malicious apps to get sensitive data that has been stored in the clipboard.

**Comment by ThierryThevenet** [comment]
to be discussed ....

**Comment by ThierryThevenet** [comment]
to be discussed as there is a hude UX pb behind that

**Comment by ThierryThevenet** [comment]
1) remove the copy option in the DID private key screen (no clipboard)
2) for private blockchain account key (in the reveal screen) : leave the screen open no more than 10s (with discounted counter if possible)

**Comment by bibash28** [comment]
Size: S
