### ISSUE TITLE
Prevent screenshots when sensitive data are displayed

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1169]
[Info] The app does not have capabilities to prevent against screenshots of sensitive data
Pages that allows to take screenshots of sensitive data:
- Recovery phrase (during on-boarding and in settings as well)
- Private/did keys

**Comment by bibash28** [comment]
It is not possible to completely disable screenshots in iOS. However, you can use the UIApplicationExitsOnSuspend key in your app's Info.plist file to prevent the user from taking a screenshot of your app when it is in the background. Additionally, you can use the UIScreen.screenshot() method to detect when a screenshot is being taken and take appropriate action, such as displaying a message or blocking the screenshot. However, it's worth noting that even with these methods, it is still possible for a user to take a screenshot of your app using external tools.

**Comment by bibash28** [comment]
It is possible to disable screenshot in android.

**Comment by bibash28** [comment]
i have found sth: **https://pub.dev/packages/secure_application**

**Comment by bibash28** [comment]
@ThierryThevenet @hawkbee1

**Comment by bibash28** [comment]
https://www.nomtek.com/blog/screenshot-preventing-on-mobile-apps

**Comment by bibash28** [comment]
https://github.com/yoxisem544/ScreenshotPreventing-iOS

**Comment by bibash28** [comment]
Size: L
