### ISSUE TITLE
Text for twitter credential

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1172]
Directly on the "Twitter card" should be the following text : **Prove your twitter account ownership**

Then, in card details : 

**Why get this card : This card is a proof that you own your twitter account. Use it to prove your twitter account ownership whenever you need.** 

**How to get it : Follow the steps on TezosProfiles https://tzprofiles.com/connect. Then, claim the “Twitter account” card in Altme. Make sure to sign the transaction on TZPROFILES with the same account you are using in Altme.** 

**Expiration date : This card will be active for 1 year.**

**Comment by hawkbee1** [comment]
Size: S
