### ISSUE TITLE
EmailProof universal link does not open on Android even if app is installed

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1173]
By defaul default the web addess "app.altme.io" is not set 

i think the probleme is that one 
https://stackoverflow.com/questions/70653427/android-deep-links-not-working-due-to-supported-web-addresses-being-disabled-by

**Comment by bibash28** [comment]
I think this issue is already solved. I didn't face any issues with android  fresh build...
@ThierryThevenet @hawkbee1
