### ISSUE TITLE
Implement a "What's new" modal in Altme to inform people about last updates

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1183]
People need to know what is new in Altme to be able to use the last versions of our features. 

That is why I propose to dev this screen. It will appear every time someone update its Altme wallet to inform him about the last modifications in the wallet. It's important to show that we are active correcting bugs and always improving the Altme wallet. 

This should display everything from the 1st version (last update at the top to the first version at the bottom).

https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4549%3A11503&t=eyCpBHCWviUt0a0T-1

<img width="406" alt="Capture d’écran 2023-01-05 à 08 48 06" src="https://user-images.githubusercontent.com/108657151/210728489-94fa10ef-412d-4375-ba19-6d6bc332086e.png">

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/215053199-ce009e4d-377b-4b64-aaeb-6041dc7e2b82.PNG)
