### ISSUE TITLE
Redesign screen of "select a credential" when there is no credential (credentialOffer flow) available in the wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1190]
![File(1)](https://user-images.githubusercontent.com/32768069/210816395-b175822d-3849-4826-84be-1cd9260d550a.jpg)

**Comment by bibash28** [comment]
Do we already have new design? @ThierryThevenet @hawkbee1

**Comment by bibash28** [comment]
@HugoNDO

**Comment by bibash28** [comment]
@HugoNDO

**Comment by hawkbee1** [comment]
DOMAIN requests missing => The required credential is not in your wallet
