### ISSUE TITLE
Update design card "Device Info"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1193]
New card display "Wallet certificate" instead of "Device Info"
See Figma

and new credential ( jsonld)

**Comment by hawkbee1** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4010%3A12035&t=1LOMsmjwIfqsW7V5-0

https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4151%3A11129&t=1LOMsmjwIfqsW7V5-0

**Comment by ThierryThevenet** [comment]
https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/WalletCredential.jsonld
new credential
add : "deviceIdentifier"
change attribute "device" to "deviceName"

**Comment by ThierryThevenet** [comment]
credentuial manifest

https://github.com/TalaoDAO/wallet-tools/blob/main/credential_manifest/WalletCredential_credential_manifest.json

**Comment by hawkbee1** [comment]
Size: S
