### ISSUE TITLE
add Altme in the walletconnect repo of wallets 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1201]
![File(2)](https://user-images.githubusercontent.com/32768069/211065052-18707b4f-6be4-4e74-b848-d2a01a0d7aa6.jpg)

**Comment by hawkbee1** [comment]
duplicate of [Add Altme wallet in the walletConnect sdk#1275](https://github.com/TalaoDAO/AltMe/issues/1275)
