### ISSUE TITLE
Wert : when unsupported chain is current (Fantom), BUY must be inactive and grey

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1208]

**Comment by bibash28** [comment]
Size: S

**Comment by bibash28** [comment]
Making grey is confusing.. So I just showed this message.. 



![Image](https://user-images.githubusercontent.com/18188709/211264481-beb2b382-8b67-4548-8683-b9bd465b9e3f.png)

**Comment by bibash28** [comment]
@ThierryThevenet
