### ISSUE TITLE
New card design for blockchain account and account from other wallets

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1214]
2 sets of 5 cards

**Comment by hawkbee1** [comment]
new design for existing AssociatedAddress cards: 


![Image](https://user-images.githubusercontent.com/49282360/212011667-28a7f066-1ac1-4623-b73d-03a125a88d48.png)
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4847%3A14518&t=5QBO3RrRrVEtBKaz-0

The cherry on the cake would be the address position : Two lines or 1 line depending on length. Base line for address display is at the bottom 


![Image](https://user-images.githubusercontent.com/49282360/212012472-0fa5b6aa-ac9c-40db-b363-a235034adb74.png)

**Comment by hawkbee1** [comment]
This new cards are provided by a dapp, we don't have to create them in the wallet.
The new cards are Proof Of Ownership cards (Poo cards):
EthereumPooAddress
TezosPooAddress
PolygonPooAddress
BinancePooAddress
FantomPooAddress
More information about the model here: 
https://talao.slack.com/archives/C047YAGGA5U/p1673447169235449

Here is the design: 


![Image](https://user-images.githubusercontent.com/49282360/212013855-0f5fad2c-030c-4dcc-9070-d346ffc22c55.png)

https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=4874%3A12280&t=5QBO3RrRrVEtBKaz-0

Cherry on the cake : Write address from center Base line  


![Image](https://user-images.githubusercontent.com/49282360/212014289-b7071b31-e902-4ae4-a9ce-e60dfccbe4ab.png)

**Comment by hawkbee1** [comment]
Thierry Thevenet
  [09:23](https://talao.slack.com/archives/C03V9HU19DM/p1673511806141769)
You can request tje new Poo credentials on https://talao.co/wallet-link
