### ISSUE TITLE
Change the text on this screen

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1261]
Replace "Let's discover everything web 3 has to offer" by : "Explore the world of true identity ownership."

![File](https://user-images.githubusercontent.com/108657151/214016191-e8639a02-4b10-4ed3-afd9-259bd3cf846d.jpg)

**Comment by hawkbee1** [comment]
on talao branch

**Comment by ThierryThevenet** [comment]
not done
