### ISSUE TITLE
live chat with matrix.org

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1283]
with matrix .org

serveur will be our own server on aws (Syracuse)
there are several Flutter/Dart packages like https://pub.dev/packages/matrix

live chat screen will be in the drawer/Help center
User will exchange messages with our Support guy

it is like whatsapp but room is onlly for 2 people : user and support

at wallet creation, the wallet create a room and invite the support 

The support (Bastien)  will use a mobile app like  https://apps.apple.com/fr/app/element-messenger/id1083446067 to answer to user questions

**Comment by hawkbee1** [comment]
Size: XXXXXL
