### ISSUE TITLE
Talao wallet : Add linkedinIn info screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1288]
replace example by "https://www.linkedin.com/john.doe/"

**Comment by ThierryThevenet** [comment]
when enter an url the input field is RED ? and the export displayed ?

Dont know if the url is correct or not

**Comment by bibash28** [comment]
yes.

I have used the following regex for the filter:
r'^(https:\/\/)(www\.)?linkedin\.com\/in\/[a-zA-Z0-9-]+(\/)?$'

**Comment by bibash28** [comment]
Size: S
