### ISSUE TITLE
Add button "chat" in bottom bar

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1304]
Replace Search with chat

Add "Search credential" in drawer/manage identity

**Comment by hawkbee1** [comment]
The chat will be last icon on the right and the buy button take the search place.

**Comment by hawkbee1** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=5121%3A12964&t=3wezWNvXpYIQ3BVb-0

**Comment by hawkbee1** [comment]
**For Talao**
If the build is not with blockchain part (app var used to diplay or not the token and NFT sections), we hide the buy icon and show search icon instead (with search screen behind the icon)
