### ISSUE TITLE
Publish ebsi lib as a Dart package

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1312]

**Comment by ThierryThevenet** [comment]
need to check the functions available with you.
some libs exists in js :
https://www.npmjs.com/package/@cef-ebsi/ebsi-did-resolver
https://www.npmjs.com/package/@cef-ebsi/wallet-lib?activeTab=versions

**Comment by hawkbee1** [comment]
publish on pub.dev

**Comment by ThierryThevenet** [comment]
Nor urgent, not a priority
