### ISSUE TITLE
EBSI : need to use P-256 keys instead of P-256K

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1324]
generated from scratch and stores aside passphrase
We will see later how to import it

**Comment by hawkbee1** [comment]
Flow: 
At wallet creation We generate and store a P-256 key with jose package.
When user need to use EBSI package, if key doesn't exist we create it and store it.

When wallet interact with EBSI package, Ebsi object is initialized Ebsi with the P-256 key from wallet (we keep possibility of initialization with mnemonic but wallet doesn't use it).
During thumbprint computation we sort element on alphabetical order and remove alg if any is present (just for thumbprint computation).
