### ISSUE TITLE
Impossible to display an ethereum NFT

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1339]
the NFT is dispayed as "NFT too big to load"
ERC721 

address 0x03817255659DC455079DF516c5271B4046b2065b

https://etherscan.io/tx/0x77740129ebdacb9f98ed69e78ece47675bd07f9213f540c15322ba5d3a3dc0ad

**Comment by ThierryThevenet** [comment]
![Screenshot_20230210-125843](https://user-images.githubusercontent.com/32768069/218087861-f02385e7-5039-4d11-a180-354305975a03.jpg)

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  The metadata that returned from Moralis API is null for this NFT 




![Image](https://user-images.githubusercontent.com/40627325/218442346-4694b960-223d-462c-957c-fcca006d0032.png)
