### ISSUE TITLE
EBSI : Add ed25519d key for EBSI

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1341]
Derive from wallet passphrase . this key is the one we use for did:key today

**Comment by bibash28** [comment]
ebsi_func_test_update

**Comment by bibash28** [comment]
so the ionly solution we have is ES256 ECDSA using P-256 and SHA-256 to be clean.
Anyway the passphrase issue is not really an issue fior EBSI and the future EUDI wallet as they said that they do not want to export the key.....so lets keep the key for EBSI as a standalone key
