### ISSUE TITLE
SIOPV2 (ebsi verifier) does not work with emailpass a $.credentialSubject.type

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1367]
test 
https://talao.co/sandbox/ebsi/login?code=46ae8ecb-ad1f-11ed-a8a0-0a1628958560

**Comment by hawkbee1** [comment]
Should probably be $..credentialSubject.type with two dots instead of one.

**Comment by bibash28** [comment]
https://talao.co/sandbox/ebsi/login?code=e5299d09-add6-11ed-9572-0a1628958560
