### ISSUE TITLE
Cannot send token ion Ethereum

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1370]
When one clics to confirm  a token send there is a loop on the confirmation

**Comment by ThierryThevenet** [comment]
The problem is that the biometric confirmation when sending tokens refers to the confirmation page and does not validate the sending
the second problem is that the last line of numbers ( , 0 supp) goes down too far and is not easily accessible to users

**Comment by hawkbee1** [comment]
https://user-images.githubusercontent.com/49282360/219059567-deef2238-18c3-4aa1-9ce7-89d56202a950.MP4
