### ISSUE TITLE
OIDC4VCI flow (credential issuance)  with authorization code displays a white screen for 1s

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1380]
There is a white screen displayed 1s then the process goes and credential is transfered correctly.

For information : in the real process there will be a pause before the access token is sent back to the wallet as the issuer may request user to login to a portal

**Comment by bibash28** [comment]
Can you give the test url? @ThierryThevenet

**Comment by bibash28** [comment]
Still there? @ThierryThevenet
