### ISSUE TITLE
LIve chat for external company associated to a loyalty card 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1394]
Use case.
A c ompany launches a new loyalty card on Altme. This loyalty card allow to open a chat rom betwen the user wallet and a customer support (not Talao support). 
Need to acces to the Live chat when we open the Loyalty card.
The address on the support will be in the loyalty card as an attribute of the loyalty card.

See hugo for design

**Comment by hawkbee1** [comment]
@hawkbee1 ask for design and testing credential+chat parameter (matrix id of company support)

**Comment by ThierryThevenet** [comment]
The room must be **unique** for all users.

**Comment by ThierryThevenet** [comment]
we confirm the live chat associated to a loyalty card. When user receives a loyalty card (bloometa for instance), wallet can create a new matrix room with the bloometa support (address on the loyalty card vc). The messages are displayed on the cards detail screen as discussed yesterday . If the support is not defined in the VC then there is a message displayed "This feature is not available" or equivalent (modifié)
