### ISSUE TITLE
Audit : Secret keys are stored in memory 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1397]
we need to keep theh secret key in secure storage

**Comment by hawkbee1** [comment]
@hawkbee1 : Asking more information from audit company.

**Comment by hawkbee1** [comment]
- every wallet has "wallet state" where all crypto accounts with secret keys are stored
/TalaoDAO/AltMe/lib/wallet/model/crypto_account_data.dart, class CryptoAccountData, L:13, L:23, secretKey field

- this state updates every time when new account is created
/TalaoDAO/AltMe/lib/wallet/cubit/wallet_cubit.dart, createBlockchainAccount, L:305
