### ISSUE TITLE
Problems with cards issued following KYC Passbase

### ISSUE THREAD

**Issue by nicolasmullertalao** [TalaoDAO/AltMe#1409]
Following Passbase process I didn’t get the 6 cards but only 3 of them (Verifiable ID, Over 18 and Over 13), and not automatically (I had to request again in the discover)
+ the message "you have a new credential" keeps appearing
+ I got 3 times the "Verifiable ID" and twice "Nationality proof"
![IMG_4039](https://user-images.githubusercontent.com/72191863/221547962-bad5c7f7-ceec-4ca3-abe5-581aebe6582d.jpeg)

**Comment by bibash28** [comment]
Yes, "you have a new credential" message for each credential addition...
I tried to add. I got 6 credentials..
