### ISSUE TITLE
Altme : check if pass phrase has been saved

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1421]
at bootstrap after having shown the passphrase
Request user to prove he has saved the pass phrase
see hugo fro screen design

**Comment by bibash28** [comment]
@HugoNDO

**Comment by ThierryThevenet** [comment]
that step must not be skipped

**Comment by ThierryThevenet** [comment]
The same screen as treh 12 words is displayed but 4 words a left empty.
User must fill the 4 words correctly to go forward. a back button is there to allow user to ge back to teh screen with the 12 words.

**Comment by hawkbee1** [comment]
![image](https://user-images.githubusercontent.com/49282360/222663957-cfd6164e-244c-4e7d-a4dd-a93506426316.png)

**Comment by hawkbee1** [comment]
After showing the 12 words to user we display the words in random order. The user must press the first 6 words in correct order.
When user press the right word its number is displayed (1-6)
When user presse the wrong word the border is red and pressing the word again cancel the selection.

**Comment by bibash28** [comment]
ok
