### ISSUE TITLE
Polygon ID : generate a DID at wallet creation

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1425]
it is a secp256k1 curve , same as ethereum.
Need to use the wallet flutter dart sdk

https://0xpolygonid.github.io/tutorials/

**Comment by hawkbee1** [comment]
https://github.com/iden3/polygonid-flutter-sdk/tree/develop

**Comment by hawkbee1** [comment]
good documentation for flutter package here: https://github.com/iden3/polygonid-flutter-sdk/tree/develop/example

**Comment by hawkbee1** [comment]
First version create DID and display it in new menu in drawer
![image](https://user-images.githubusercontent.com/49282360/223042793-96f45a4f-6b9d-41e0-af4e-1c7c8f5d487c.png)

**Comment by hawkbee1** [comment]
When creating the identity the blockchain is polygon and the network is the main net.
