### ISSUE TITLE
OIDC4VCI and SIOPV2 : resolve did:web

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1483]
today we only resolve "did:ebsi" .
 "resolve" means get the DID document from the DID
we need to resolve any did. one can use the external universal resolver :
example 
curl -X GET [https://dev.uniresolver.io/1.0/identifiers/did:indy:idunion:BDrEcHc8Tb4Lb2VyQZWEDE](https://dev.uniresolver.io/1.0/identifiers/did:web:talao.co
When we get eth DID docuiment we need to find the publickey for the verification method

**Comment by ThierryThevenet** [comment]
Not urgent, not a priority

**Comment by hawkbee1** [comment]
issuer: when getting credential we display status after checking public key (didkit do it automatically in most usecase). in case of OIDC4VCI protocol wallets need to check verifiable credential signature by getting public key from DID document. Universal resolver
can get DID document and kid from issuer header allow us to pick the right public key.


verifier: When getting DID from verifier we need to check verifier signature, especially when request uri is used to get credential in a JWK. same process as with issuer: we get DID document from universal resolver...


testing issuers : 
https://talao.co/sandbox/issuer/employee (gayaX)
https://talao.co/sandbox/issuer/diploma (EBSIV2)

universal resolver: https://github.com/decentralized-identity/universal-resolver
