### ISSUE TITLE
Check for phones compability with PolygonId

### ISSUE THREAD

**Issue by TalebRafiepour** [TalaoDAO/AltMe#1527]
Iphone:
Supported iPhone devices for the Polygon ID app require the following capabilities: arm64 architecture, minimum performance a12, wifi, and still-camera.
Android:
We only support architecture ‘arm64-v8a’ and ‘x86_64’ and the minimum Android API version is 21 (Lollipop 5.0).

**Comment by ThierryThevenet** [comment]
Check with iphone 6 or iphone 8
