### ISSUE TITLE
the deeplink does not work on Android for emailpass and phonepass

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1542]

**Comment by ThierryThevenet** [comment]
"Altme is not installed on your phon"

**Comment by ThierryThevenet** [comment]
still does not work on build 1.13.12

**Comment by ThierryThevenet** [comment]
does not work on 1.13.13

**Comment by hawkbee1** [comment]
removing NO GO, Thierry is checking if he has another parameter related to deeplink on his phone since he's the only one to get this issue.
