### ISSUE TITLE
Card ratio should always be the same.

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1544]
Probably a consequence of https://github.com/TalaoDAO/AltMe/issues/1514, the aspect ratio is not the same on cards in discover, list and detail screens. aspect ratio should always be with 500 width and 300 height.

Since we removed backgrounds, the "add card" in the credential list should also respect the 500/300 ratio.

**Comment by ThierryThevenet** [comment]
when you switch from My wallet to Discover, one can see the button (Coins...) moving slightly and the width of the screen larger
