### ISSUE TITLE
PolygonID : New verifiable credentials visuals + title and VC sentence

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1553]
Here you can get the new VCs : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=5709%3A23614&t=2zO2LguHqDoBiVE6-1

Please, make sure to change the title + text on cards as well (for the MY WALLET and DISCOVER sections)

**Comment by ThierryThevenet** [comment]
See ticket for credential manifest for polygonID

**Comment by hawkbee1** [comment]
linked ticket about: https://github.com/TalaoDAO/AltMe/issues/1563

**Comment by hawkbee1** [comment]
@TalebRafiepour link to get credentials: https://issuer-demo.polygonid.me/

**Comment by hawkbee1** [comment]
same thing as what we are doing with wallet credential (device credential) except that we get the credential manifest from url.
