### ISSUE TITLE
Add Blockchain account cards in the DISCOVER sections

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1554]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=5709%3A23614&t=UkaYobGSj7SVs2MZ-1

It should open the process to create / import a new account

**Comment by HugoNDO** [comment]
<img width="790" alt="Capture d’écran 2023-04-13 à 14 15 53" src="https://user-images.githubusercontent.com/108657151/231755390-4199f059-da09-4020-99b1-7ef031527dc7.png">

**Comment by TalebRafiepour** [comment]
@hawkbee1 @HugoNDO We need descriptions for the details page of get_it
