### ISSUE TITLE
Altme does not start on Android which does not support polygon ID wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1569]

**Comment by hawkbee1** [comment]
@ThierryThevenet 
I'm not able to reproduce the issue with my old P20 PRO device... Furthermore I was able to use polygon :-/

**Comment by hawkbee1** [comment]
Adding temp sniffer in next testing release to catch error message during this usecase.

**Comment by hawkbee1** [comment]
@bibash28 @hawkbee1 ping to check

**Comment by bibash28** [comment]
@hawkbee1 check check

**Comment by hawkbee1** [comment]
build 1.13.13 => still crashing on Thierry's old android phone and nothing is sent to sentry (sniffer).
