### ISSUE TITLE
PolygonID verifier : need a step to confirm the sending of a proof to the verifier

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1572]
cf with @HugoNDO 
We will need the PIN code also for signing

![image](https://user-images.githubusercontent.com/32768069/233175333-5130774e-cc18-4395-ad70-cb15a44ad806.png)

**Comment by bibash28** [comment]
https://gist.github.com/plusema86/4bfc3cdc3ee542a4359626a63af6b7ba

**Comment by hawkbee1** [comment]
My pixel is crashing when presenting KYC age MTP
