### ISSUE TITLE
PolygonID : verifier side, problem of message

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1574]
with a key age credential 
if you verify with key Age MTP, Alltme display error message but PolygonID display "The claim cannot be found in the wallet"

There are 2 types of proofs requested by issuer  (MTP and signature), when the verifier request a proof "MTP" and the credential has a proof "SIG" then Altme should displayed a message "Credntial does not exist". Same for opposite SIG versus MTP

https://0xpolygonid.github.io/tutorials/wallet/wallet-sdk/polygonid-sdk/iden3comm/auth-requests/#structure-of-basic-auth-request

**Comment by bibash28** [comment]
Sign up : {"id":"900f566a-5c6f-4907-910e-ce9f3e6cf3e3","typ":"application/iden3comm-plain-json","type":"https://iden3-communication.io/authorization/1.0/request","thid":"900f566a-5c6f-4907-910e-ce9f3e6cf3e3","body":{"callbackUrl":"https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=223289","reason":"test flow","scope":[]},"from":"did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"}"

**Comment by bibash28** [comment]
Adding claim: "{"id":"48cab35b-c385-4f99-ab54-c82792c1dc90","typ":"application/iden3comm-plain-json","type":"https://iden3-communication.io/credentials/1.0/offer","thid":"48cab35b-c385-4f99-ab54-c82792c1dc90","body":{"url":"https://self-hosted-platform.polygonid.me/v1/agent","credentials":[{"id":"2a81b48c-e25b-11ed-b7df-0242c0a88005","description":"KYCAgeCredential"}]},"from":"did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5","to":"did:polygonid:polygon:mumbai:2qJENvdzkkAnAoSZFQMNMwqDSsR1R6DxqNS5Xk4buL"}"

**Comment by bibash28** [comment]
Sign in
```
{
  "id": "900f566a-5c6f-4907-910e-ce9f3e6cf3e3",
  "typ": "application/iden3comm-plain-json",
  "type": "https://iden3-communication.io/authorization/1.0/request",
  "thid": "900f566a-5c6f-4907-910e-ce9f3e6cf3e3",
  "body": {
    "callbackUrl": "https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=223289",
    "reason": "test flow",
    "scope": []
  },
  "from": "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"
}
```

**Comment by bibash28** [comment]
Sign in : KYC Age Credential - SIG
```
{
  "id": "3d90c422-892a-456d-845b-a3b5e6196d30",
  "typ": "application/iden3comm-plain-json",
  "type": "https://iden3-communication.io/authorization/1.0/request",
  "thid": "3d90c422-892a-456d-845b-a3b5e6196d30",
  "body": {
    "callbackUrl": "https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=960873",
    "reason": "test flow",
    "scope": [
      {
        "id": 1,
        "circuitId": "credentialAtomicQueryMTPV2",
        "query": {
          "allowedIssuers": [
            "*"
          ],
          "context": "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld",
          "credentialSubject": {
            "countryCode": {
              "$nin": [
                840,
                120,
                340,
                509
              ]
            }
          },
          "skipClaimRevocationCheck": true,
          "type": "KYCCountryOfResidenceCredential"
        }
      }
    ]
  },
  "from": "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"
}
```

**Comment by ThierryThevenet** [comment]
see new tickets
