### ISSUE TITLE
ID360 : new verifiableID process

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1578]
**To be done after ticket #1576 and #1577 as Passbase sdk must be removed from code in this ticket**

When user clic on VerifiableID in Discover
get  code with API call
curl https:talao.co/id360/get_code?client_id=<wallet_id> -H "apiKey":<wallet_api_key>
    
return json  {"code": <code>} 
request wallet_id and wallet_api_key to Thierry

then open a window in browser and redirect user with
https://talao.co/id360/authenticate?code=<code>&vc=verifiableid&client_id=<wallet_id>&callback=<wallet_callback> (modifié) 
wallet_callback is a deeplink to be defined...

**Comment by hawkbee1** [comment]
client ID will be different in TALAO and ALTME

**Comment by ThierryThevenet** [comment]
https://issuer.talao.co/pornhub

**Comment by ThierryThevenet** [comment]
mist open a window, it does not work

**Comment by ThierryThevenet** [comment]
must add &did=<wallet_did> in teh request
