### ISSUE TITLE
yoti not working on android ?

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1585]
On android, selfie has a 90° rotation when validating and age estimation is failing
Test on ios: Works fine on first try and don't see any rotation.

**Comment by hawkbee1** [comment]
image sent on android was too big

**Comment by ThierryThevenet** [comment]
Dont see the difference now ?

**Comment by ThierryThevenet** [comment]
Still not working for me  3 times

**Comment by ThierryThevenet** [comment]
stll not working

**Comment by ThierryThevenet** [comment]
masq if not large enough.

**Comment by ThierryThevenet** [comment]
Remove the mask !!!
