### ISSUE TITLE
Yoti call, if error for first call 'return code 400 do not do other calls

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1588]

**Comment by hawkbee1** [comment]
Lets compute image size on android and change  inSampleSize parameter accordingly. Currently, depending on phone camera settings images are too big or too small.

**Comment by hawkbee1** [comment]
error messages: https://developers.yoti.com/v8.0/ai-services-terminals/api-reference

**Comment by hawkbee1** [comment]
@bibash28 phone will get 403 error if user is not old enough to get credential.
=> let's ask for credentials in following order : 

1. age estimation
2. over18
3. over15
4. over13

If on of them fail we stop the process of credential acquisition.

**Comment by ThierryThevenet** [comment]
dont see teh difference
When return is 400, do not call a second time
