### ISSUE TITLE
Beacon does not start on IOS when smartphone browser is used

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1592]
Use a custoe link if web link does not work

**Comment by bibash28** [comment]
tezotopia.com -> Choose Altme -> Opening Altme app

**Comment by bibash28** [comment]
- Tested in iphone X
- Browser: Safari

**Comment by ThierryThevenet** [comment]
it works on iphone X but there is an issuer with i^phone 14 now. we will see later
