### ISSUE TITLE
PolygonID authenticate (issuer side)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1593]
Ad "Do you trust this domain..." with the domain name of the issuer website

**Comment by ThierryThevenet** [comment]
dont see teh difference ?

**Comment by bibash28** [comment]
You need enable the alert option in the drawer...

**Comment by ThierryThevenet** [comment]
Not totally completed;
If alert is off user should not see the screen above, user should be authenticated
