### ISSUE TITLE
PolygonID : verifier side, difference on behavior between  PolygonID wallet and Altme 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1633]
with a AgeKyc VC
on verifier side, PolygonID wallet dispolays "credential not found" wjen Altme sends the proof
![Capture d’écran de 2023-05-10 10-19-42](https://github.com/TalaoDAO/AltMe/assets/32768069/21526b3e-9ca3-4e61-a556-6b42d1130918)

**Comment by bibash28** [comment]
Issue in their side....

**Comment by bibash28** [comment]
https://github.com/0xPolygonID/polygonid-flutter-sdk/issues/314
