### ISSUE TITLE
DeFI card GET : description is missing

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1649]

**Comment by hawkbee1** [comment]
@HugoNDO

**Comment by hawkbee1** [comment]
defi compliance

**Comment by HugoNDO** [comment]
Why get this card: This card serves as a verifiable proof of your KYC/AML compliance. It can be requested by compliant DeFi protocols and Web3 dApps that have adopted decentralized identity standards to protect user data. Once obtained, you can mint a privacy-preserving, non-transferable NFT, ensuring seamless on-chain verification by dApps and smart contract, without revealing personal data.

How to get it: Obtaining this DeFi compliance credential is a straightforward process. Just complete a one-time KYC check within the Altme wallet (powered by the ID360 solution).  Once you successfully pass the compliance check, you will promptly receive your DeFi compliance credential.

Expiration date: This DeFi compliance credential remains active for a duration of 3 months. After this period, a new compliance check is required (it's a straightforward request, without the need for a new KYC check).
