### ISSUE TITLE
Small error in the Over 13 VC description

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#1660]
![Capture d’écran 2023-05-22 à 16 35 25](https://github.com/TalaoDAO/AltMe/assets/108657151/dd0afbed-3a1f-4f90-8976-a9eb88addbdc)

Description : This card is a proof **that** you are over 13 yo.

Please verify that the same error is not on the over15 VC.

**Comment by ThierryThevenet** [comment]
Issuer side
