### ISSUE TITLE
Deeplink to launch multiple credentialOffer process

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1679]

**Comment by ThierryThevenet** [comment]
with &uri_list=[....]

**Comment by hawkbee1** [comment]
In jeprouvemonage, altme and talao;

**Comment by hawkbee1** [comment]
deeplink example:
https://app.altme.io/app/download?uri_list=https%3A%2F%2Fissuer.talao.co%2Fmy_route_to_wallet_endpoint%2F1111111111&uri_list=https%3A%2F%2Fissuer.talao.co%2Fmy_route_to_wallet_endpoint%2F2222222222

uri_list appear for each element of the list.
first step of dev: write a dart test with this deeplink to check ability of dart to parse it correctly.
