### ISSUE TITLE
Altme wallet UI gets stuck when a contract call is made from a dApp in ghostnet network Tezos

### ISSUE THREAD

**Issue by singhparshant** [TalaoDAO/AltMe#1685]
I am trying to interact with a smart contract deployed in ghostnet using @airgap/beacon-sdk . But when I make the contract method call like below, the UI of the wallet gets stuck in waiting.

Contract address: https://better-call.dev/ghostnet/KT1KHhpL9Pk9DVh5GDnikH4Gx1kQ6NMb3GmC/operations

```
  const result = await dAppClient?.requestOperation({
      operationDetails: [
        {
          kind: TezosOperationType.TRANSACTION,
          destination: process.env
            .NEXT_PUBLIC_TEZOS_REGISTRY_CONTRACT as string,
          amount: "0",
          parameters: {
            entrypoint: "log_Issuance",
            value: { string: hash },
          },
        },
      ],
    });
``` 

<img src="https://github.com/TalaoDAO/AltMe/assets/65491540/eef08e9a-a478-426f-95d8-f20f68d3ebf8 " alt="Your image title" width="200"/>

**Comment by bibash28** [comment]
Hello @singhparshant, thank you for reporting. Can you share step by steps you followed? Also, can you share the URLs you used?
