### ISSUE TITLE
add a design for the polygonID clique social VC

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1693]
see with Hugo

**Comment by hawkbee1** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=5709-23614&t=AEQjKdOMeL0BzIt8-0

**Comment by ThierryThevenet** [comment]
take the current design to start

**Comment by ThierryThevenet** [comment]
and adfdd the VC in teh Polygon category
