### ISSUE TITLE
Add a category for polygonid VC in mywallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1694]

**Comment by hawkbee1** [comment]
Polygon credentials
Discover : (initialisé mais vide et donc non montré)
Title: Get Polygon ID credentials
Subtitle: Prove your access rights in the Polygon ecosystem
My wallet :
Title: My Polygon ID credentials
Subtitle: Prove your access rights in the Polygon ecosystem
