### ISSUE TITLE
Reference Altme in the walletconnect sdk as we cannot launch walletconnect from the smartphone

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1698]

**Comment by ThierryThevenet** [comment]
![File(14)](https://github.com/TalaoDAO/AltMe/assets/32768069/10bdd057-b411-4750-bfbd-dd16ed273dc7)

**Comment by hawkbee1** [comment]
App submitted to wallet connect. Review should be done at the end of week 31
