### ISSUE TITLE
Beacon does not start on Android mobile

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1701]
go to https://talao.co/altme-identity with mobile browser
try to open Altme as a crypto wallet, it opens Altme but does not synchronize

**Comment by ThierryThevenet** [comment]
it seems ok on IOS

**Comment by ThierryThevenet** [comment]
same problem with Android on tezotopia.com with mobile browser

**Comment by hawkbee1** [comment]
Tezotopia:
Not working on the morning and working the afternoon without any code change.
