### ISSUE TITLE
We should be able to delete cards we got from https://talao.co/altme-identity

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1721]
The type of this card is different from the type of cards created during onboarding, right ?

**Comment by hawkbee1** [comment]
link to https://github.com/TalaoDAO/AltMe/issues/1716

**Comment by bibash28** [comment]
![Image](https://github.com/TalaoDAO/AltMe/assets/18188709/99c839ca-761f-4d82-925c-443fe228aabf)

@ThierryThevenet @hawkbee1

**Comment by ThierryThevenet** [comment]
For me this one is not done
