### ISSUE TITLE
Redesign of walletconnect signature screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1723]
The screen below must be redisgn with @HugoNDO 

![IMG_7570](https://github.com/TalaoDAO/AltMe/assets/32768069/c15b1d0a-95fe-4ce8-94c8-420bbb2fa3dd)

see below Metamask equivalent screen
![File(16)](https://github.com/TalaoDAO/AltMe/assets/32768069/c0b025bb-49cd-4f4e-9566-af5df66bc1c8)

**Comment by HugoNDO** [comment]
Please, just keep this and do not display the rest 
<img width="592" alt="Capture d’écran 2023-07-19 à 12 36 55" src="https://github.com/TalaoDAO/AltMe/assets/108657151/e5c97997-778d-445b-92c0-97b41e7672ee">

**Comment by HugoNDO** [comment]
All information under this should not be displayed

**Comment by hawkbee1** [comment]
@hawkbee1 add current screenshot

**Comment by hawkbee1** [comment]
![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/62cd32c3-f188-496c-9cd3-6a96710a6631)



![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/972bb8ba-f753-42ba-8284-b1d30262e000)
