### ISSUE TITLE
Return code 212 and 412 as pop up with custom message for presentationRequest and credential Offer

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1729]
the 412 is alreadtyt implemented for credentialRequest in the POST

need to do the same in the POST for presenttaionRequest

need to do the same for 212

212 is a green popup
412 is a red popup

**Comment by hawkbee1** [comment]
@bibash28 @TalebRafiepour that's not already the case?

**Comment by ThierryThevenet** [comment]
the message is displayed 2 times .
see with Discover/NFT compliance

**Comment by ThierryThevenet** [comment]
see also https://github.com/TalaoDAO/AltMe/issues/1713 which is close
