### ISSUE TITLE
Add Design for Civic Pass credential

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1733]
see @HugoNDO

**Comment by hawkbee1** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=5709-23614&mode=design&t=8U9fuqrpyiQAkKsv-0

**Comment by hawkbee1** [comment]
https://issuer.talao.co/credential-manifest/polygonid/civicpasscredential

**Comment by ThierryThevenet** [comment]
Must rework the design with Hugo

**Comment by ThierryThevenet** [comment]
and use the credntial manifest for title and subtitle
