### ISSUE TITLE
EBSI diploma are not accepted anymore ?

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1734]
https://talao.co/sandbox/issuer/diploma

it looks like the credential is issued  but the wallet refuses on the credential endpoint 
The issuer is an EBSI issuer not registered. If this is the problem we should only get a red message but accept the credential

**Comment by hawkbee1** [comment]
Le blocage a lieu dans la récupération du credential manifest. 
On cherche l'output descriptors pour VerifiableDiploma mais sur https://talao.co/sandbox/ebsi/issuer/kgivldcsuz il n'y a que https://api.preprod.ebsi.eu/trusted-schemas-registry/v1/schemas/0xbf78fc08a7a9f28f5479f58dea269d3657f54f13ca37d380cd4e92237fb691dd

**Comment by ThierryThevenet** [comment]
It is ok
