### ISSUE TITLE
how can fix and start the altme

### ISSUE THREAD

**Issue by liJian55** [TalaoDAO/AltMe#1736]
1、flutter doctor
![1](https://github.com/TalaoDAO/AltMe/assets/28912029/2a3c8e4d-2f7e-4233-a206-9337fd2abcbd)
2、flutter run 
![image](https://github.com/TalaoDAO/AltMe/assets/28912029/30c1af6f-fedd-4b58-9b77-91c23b45e3e8)

**Comment by hawkbee1** [comment]
Hello
Have you done the didKit build and ran build_runner?
 If you're using fvm you can run script.sh. Without fvm you will need to update script.sh.

**Comment by liJian55** [comment]
Thanks for your reply, I have done a didkit build and used fvm but the compiler tells me that my dart version does not support null safe syntax @hawkbee1  Cleared the local cache and re-pulled the dependency, so I'm wondering why this is a problem, thank you

**Comment by hawkbee1** [comment]
Looks like an environnement issue for me. You should check 
- dart path in your editor settings
- flutter doctor -v  (in your ide terminal)  
- fvm flutter doctor -v  (in your ide terminal)
- flutter doctor -v  (in a normal terminal)
- fvm flutter doctor -v  (in a normal terminal)
