### ISSUE TITLE
MATIC transfert (polygon) does not work 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1739]

**Comment by ThierryThevenet** [comment]
there are some funds on the test address

**Comment by hawkbee1** [comment]
Need more info on your issue @ThierryThevenet 
I added another polygon account and sent 1 MATIC without any issue.


![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/0e25af17-ea45-4b47-8e76-8ade3b9017be)
![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/a0c8abfd-3d7c-4e89-abf9-7473add98c21)
![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/3bc68c04-403e-4b89-8e77-d6ce6fd53cd7)
![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/a8923faa-3761-4558-a463-6aaa9cd7ccc9)
