### ISSUE TITLE
Cannot connect on clique social (walletconnect)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1741]
fiorst step, crypto 

it works with Metamask

**Comment by hawkbee1** [comment]
Fist step work for me. 
I choose ethereum address
clique told me that I was on wrong network
I switched to testnet
I tell clique I switched network
Wallet connect asked me to sign payload
I signed payload
=> step OK

I'm having issue at end of the process when clique is checking twitter account after subscriptions.


![Image](https://github.com/TalaoDAO/AltMe/assets/49282360/8d5ba885-7dbc-446e-8374-8b6aa2804aee)
