### ISSUE TITLE
Add profile page in drawer/Self Sovereign Identity

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1744]
Set up a switch through different profile for OIDC4VC = OIDC4VCI + SIOPV2 + OIDC4VP)
- EBSIV2
- GAIA-X
- JWTVC 
- DEFAULT 
'- ARF (grey)

Profile EBSIV2 is the current parameter for EBSI  (it works !) :
- use did:ebsi for wallet
- oidc4vci prefix is  openid://initiate_issuance for qr code
- issuer is did:ebsi
- vc a jwt format
- credential type is json schema url

Profile GAIAX
- use did:key for wallet
- oidc4vcio prefix is openid-initiate-issuance://
_ issuer is did:web
- vc is json-ld format
- credential type is type of json-ld

Profile DEFAULT 
based on the last relase of th specs
- use did:key for wallet
- oidc4vcio prefix is openid-initiate-issuance://
- prefix are siopv2 or openid4vp for verifier side
_ issuer is did:web
- vc and vp is jwt  format

**Comment by hawkbee1** [comment]
profile = {

    "EBSIV2" :
        {
            "issuer_vc_type" : "jwt_vc",
            "verifier_vp_type" : "jwt_vp",
            "offer_prefix" : "openid://initiate_issuance",
            "presentation_prefix" : 'openid-vc://',
            'cryptographic_binding_methods_supported' : ['DID'],
            'cryptographic_suites_supported' : ['ES256K','ES256','ES384','ES512','RS256'],
            'subject_syntax_types_supported' : ['did:ebsi'],
            "grant_types_supported": [
                "authorization_code",
                "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            ],
            'credential_supported' : ['VerifiableDiploma', 'VerifiableId'],
            'schema_for_type' : True,
            'oidc4vci_draft' : 'https://openid.net/specs/openid-connect-4-verifiable-credential-issuance-1_0-05.html#abstract',
            'siopv2_draft' : '',
            'service_documentation' : 'It is the profile of the EBSI V2 compliant test. DID for natural person is did:ebsi. \
                The schema url is used as the VC type in the credential offer QR code. \
                The prefix openid_initiate_issuance://'
        }, 
    "EBSIV3" :
        {
            "issuer_vc_type" : "jwt_vc",
            "verifier_vp_type" : "jwt_vp",
            "offer_prefix" : "openid://initiate_issuance",
            "presentation_prefix" : 'openid-vc://',
            'cryptographic_binding_methods_supported' : ['DID'],
            'credential_supported' : ['VerifiableDiploma', 'VerifiableId'],
            "grant_types_supported": [
                "authorization_code",
                "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            ],
            'cryptographic_suites_supported' : ['ES256K','ES256','ES384','ES512','RS256'],
            'subject_syntax_types_supported' : ['did:key'],
            'schema_for_type' : False,
            'oidc4vci_draft' : 'https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html',
            'service_documentation' : ''

        },
     "GAIAX-COMMUNITY" :
        {
            "issuer_vc_type" : "ldp_vc",
            "verifier_vp_type" : "ldp_vp",
            "offer_prefix" : "openid-initiate-issuance://" ,
            "presentation_prefix" : "openid-vc://",
            "cryptographic_binding_methods_supported" : ('DID'),
            'credential_supported' : ['EmployeeCredential'],
            "grant_types_supported": [
                "authorization_code",
                "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            ],
            "cryptographic_suites_supported" : ['ES256K','ES256','ES384','ES512','RS256'],
            "subject_syntax_types_supported" : ['did:key'],
            "schema_for_type" : False,
            "oidc4vci_draft" : "https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html",
            'service_documentation' : 'Issuer pour projet Docaposte Gaia-X'

        },
    "DEFAULT" :
        {
            "issuer_vc_type" : "ldp_vc",
            "verifier_vp_type" : "ldp_vp",
            "offer_prefix" : "openid-credential-offer://" ,
            "presentation_prefix" : "openid-vc://",
            "cryptographic_binding_methods_supported" : ('DID'),
            "grant_types_supported": [
                "authorization_code",
                "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            ],
            "cryptographic_suites_supported" : ['ES256K','ES256','ES384','ES512','RS256'],
            "subject_syntax_types_supported" : ['did:ebsi', 'did:key', 'did:ethr', 'did:tz'],
            "schema_for_type" : False,
            "oidc4vci_draft" : "https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html",
            'service_documentation' : 'Last release of the OIDC4VC documentation'

        },
    "ARF" :
        {
            "issuer_vc_type" : "jwt_vc",
            "verifier_vp_type" : "jwt_vp",
            "offer_prefix" : "openid-credential-offer://" ,
            "presentation_prefix" : 'openid-vc://',
            'cryptographic_binding_methods_supported' : ('DID'),
            "grant_types_supported": [
                "authorization_code",
                "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            ],
            'cryptographic_suites_supported' : ['ES256K','ES256','ES384','ES512','RS256'],
            'subject_syntax_types_supported' : ['did:ebsi', 'did:key', 'did:ethr', 'did:tz'],
            'schema_for_type' : False
        },
    "JWTVC" :
        {
            "issuer_vc_type" : "jwt_vc",
            "verifier_vp_type" : "jwt_vp",
            "presentation_prefix" : 'openid-vc://',
            'cryptographic_binding_methods_supported' : ('DID'),
            'cryptographic_suites_supported' : ['ES256K','ES256','ES384','ES512','RS256'],
            'subject_syntax_types_supported' : ['did:ion'],
            'schema_for_type' : False
        },

}

**Comment by hawkbee1** [comment]
issuer_vc_type

currently we are getting a jwt 
![image](https://github.com/TalaoDAO/AltMe/assets/49282360/2b30bd7d-8063-4e34-95f5-74dff6fd79d5)

**Comment by hawkbee1** [comment]
verifier_vp_type: json-ld or jwt

**Comment by hawkbee1** [comment]
offer_prefix : how do we start the issuance process?
 openid://initiate_issuance",

currently dealing with this in ebsi package 
![image](https://github.com/TalaoDAO/AltMe/assets/49282360/d72070f2-6167-4f6f-94c9-a33429f1caad)

Also used to start EBSI issuance process and check properly for issuer in registry

**Comment by hawkbee1** [comment]
schema_for_type: in did document are we looking for credential manifest with matching schema or type ? (discussion under way about using (id of credentiel manifest) = type.
