### ISSUE TITLE
Add EmployeeCredential design 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1748]
see design from hugo

insert in  a new catagory "My professional cards

**Comment by ThierryThevenet** [comment]
issuer available 
https://talao.co/sandbox/playground

**Comment by hawkbee1** [comment]
![Capture d’écran 2023-07-26 à 14 00 44](https://github.com/TalaoDAO/AltMe/assets/49282360/5ca25e40-f439-4fe5-874b-e03cad887e44)

**Comment by hawkbee1** [comment]
issuer: https://talao.co/sandbox/issuer/gaiax
