### ISSUE TITLE
Question: How is JWT VC Support handled?

### ISSUE THREAD

**Issue by jfelixh** [TalaoDAO/AltMe#1753]
Hi everyone,

the JWT VC format seems to be gaining importance ([reference discussion](https://github.com/GAIA-X4PLC-AAD/gx-credentials/issues/10)). I want to understand fully how Altme deals with JWT VC. There are several questions I would love to get some insight on:
1. How does Altme store JWT VC internally? Are they transformed or just stored as JWT?
2. Are you using/recommending any specific software for verification? Can any generic library for JWT be used?
3. What format should the "vc" data inside the JWT have? Is it pure JSON or rather JSON-LD?

Best
Felix

**Comment by ThierryThevenet** [comment]
Hello
In the OIDC4VC doc, there are 2 format behind the jwt-vc. 
'jwt_vc_json', -> pure jwt.....only used today in a EUDI wallet profile like https://vcstuff.github.io/oid4vc-haip-sd-jwt-vc/draft-oid4vc-haip-sd-jwt-vc.html

'jwt_vc_json-ld' which is trehh classic one as mentionned in the Verifibale credential W3C doc vers 1.0 . We are using it with a Gaiax-x project in France (Docaposte) today.

Altme supports 'jwt_vc_json-ld' as EBSI v2 standards (OIDC4VCI, OIDC4VP, OSIOPV2) and next beta (this week) will support the pure ldp_vc with OIDC4VCI. and next week for OIDC4VP and SIOPV2

Altme already supports ldp_vc but with 2 other protocoles :
- polygonID
- verifablepresentation request which is a simple SSI protocols
