### ISSUE TITLE
wallet does not work with external issuer GAIA-X

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1769]
**DO TICKET 1770 before**

THEN try with external server

https://icp-portal.abc-federation.gaia-x.community/

with employee in the menu

"icp" and "test" as password

If credential manifest is wrong or missing the wallet must display teh card anyway

**Comment by bibash28** [comment]
![Image](https://github.com/TalaoDAO/AltMe/assets/18188709/40437210-e292-4b0e-9b75-ec81efd3c04b)
