### ISSUE TITLE
Update credential request body format

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1770]
In order to accept different standard, wallet must add the attribute "type " to the body  of the credential request and change the value of the attribute "types"

"type" -> credential type a string ex **"type" : "**VerifiableId"****
"types" -> an array equal to the value of "types" in the openid-configuration/credential_supported/..../    
example **"types" : **["VerifiableCredential", "VerifiableId"]****

**Comment by bibash28** [comment]
{
   "format":"jwt_vc_json",
`   "type":"UniversityDegreeCredential",`
   "types":[
      "VerifiableCredential",
      "UniversityDegreeCredential"
   ],
   "proof":{
      "proof_type":"jwt",
      "jwt":"eyJraWQiOiJkaWQ6ZXhhbXBsZTplYmZlYjFmNzEyZWJjNmYxYzI3NmUxMmVjMjEva2V5cy8
      xIiwiYWxnIjoiRVMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzNkJoZFJrcXQzIiwiYXVkIjoiaHR
      0cHM6Ly9zZXJ2ZXIuZXhhbXBsZS5jb20iLCJpYXQiOiIyMDE4LTA5LTE0VDIxOjE5OjEwWiIsIm5vbm
      NlIjoidFppZ25zbkZicCJ9.ewdkIkPV50iOeBUqMXCC_aZKPxgihac0aW9EkL1nOzM"
   }
}
