### ISSUE TITLE
OIDC4VCI Test 9 : improve the design and flow

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1822]
Limit to 6 digit, center the input field
"Please insert th" secret code recieved"

When the user clc on next and get his VC return to the screen "My wallet"
![File(17)](https://github.com/TalaoDAO/AltMe/assets/32768069/bbbae889-a9f5-4857-888c-69e7f6765b09)

**Comment by bibash28** [comment]
this is different pin code @hawkbee1
