### ISSUE TITLE
OIDC4VCI : error in the format of the credential_offer_uri response to the wallet call

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1843]
I made a mistake, the issuer should respond to the wallet with the json object directly as

{'credential_issuer': 'http://192.168.88.32:3000/sandbox/ebsi/issuer/kwcdgsspng', 'credentials': [{'format': 'jwt_vc', 'trust_framework': {'name': 'ebsi', 'type': 'Accreditation', 'uri': 'TIR link towards accreditation'}, 'types': ['VerifiableCredential', 'VerifiableAttestation', 'VerifiableDiploma']}], 'grants': {'urn:ietf:params:oauth:grant-type:pre-authorized_code': {'pre-authorized_code': '62a86ec2-437c-11ee-b096-b5bae73ba948', 'user_pin_required': True}}}

**Comment by ThierryThevenet** [comment]
see test 10 OIDC4VCI

**Comment by bibash28** [comment]
I think it handles both case.. @ThierryThevenet
