### ISSUE TITLE
OIDC4VP /SIOPV2 : request_uri 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1850]
if request_uri is in the request, wallet must call eth endpoint to get the request as a jwt

**Comment by ThierryThevenet** [comment]
test 6 OIDC4VP

**Comment by bibash28** [comment]
This is the current senario.. Can you give me the specific case where we are having the issue? 
@ThierryThevenet

**Comment by ThierryThevenet** [comment]
Request_uri could be used for all types of response (vp_token and id_token
