### ISSUE TITLE
Beacon QR code scan not working on Android

### ISSUE THREAD

**Issue by crustypluto19** [TalaoDAO/AltMe#1851]
I am trying to connect my Altme Wallet on Android with an application that supports Beacon.
However, after scanning the QR code the app shows no prompts and does nothing.

https://github.com/TalaoDAO/AltMe/assets/24537483/a4a1b39a-4717-4dd1-8e6d-8e8f51777860

**Device**: Mi 9T
**Android version**: 11
**Software version**: MIUI Global 12.1.4 (stable)

**Comment by ThierryThevenet** [comment]
Tks, which altme release is it ? @crustypluto19

**Comment by hawkbee1** [comment]
Where can we find the application to test the behavior @crustypluto19 ?

**Comment by crustypluto19** [comment]
> Tks, which altme release is it ? @crustypluto19

Version 1.20.2

**Comment by crustypluto19** [comment]
> Can you point me to a failing app or an installed version of gx-credentials? @crustypluto19

I wanted to fund my wallet on Ghostnet [here](https://faucet.ghostnet.teztnets.xyz/). When logging in using the "connect wallet" option, specifically using Altme, it fails. 
And yes, I switched the blockchain network on the wallet to Tezos Ghostnet.

**Comment by hawkbee1** [comment]
By default the app is using Mainnet and the website is asking for a Ghostnet connection.
You can change network in the drawer -> blockchain settings -> blockchain  network

**Comment by ThierryThevenet** [comment]
Does not wotk for me. tested on rarible . 
@bibash28 
1.20.18

**Comment by hawkbee1** [comment]
Worked without issue for me :-/
I will test today with 2 other android devices.
