### ISSUE TITLE
EBSI-V3 compliance test 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1895]
organize 4 hours test

https://api-conformance.ebsi.eu/docs/wallet-conformance/holder-wallet/flow

**Comment by hawkbee1** [comment]
tests with EBSI V3 did:key did:key:zBhBLmYmyihtomRdJJNEKzbPj51o4a3GYFeZoRHSABKUwqdjiQPY2bNEc3kD5f3BtjYVZfBWA6WqYNew4bcCcw2LtxRRZexY1dqAbvVFvJZxo3hEUWbrJknMShRGiR8xHk1sHovix8L9QNWfcq9JFXiA6aFe1XrHuugwxNJqxMu16PvntBkHkMz

1/ flow In-time Credential
error occur when get: 
 Response | REQUEST[GET] => PATH: https://api-conformance.ebsi.eu/conformance/v3/issuer-mock/offers/2c8f6bd6-8ffb-4b67-a8e9-93d80f685451

RESPONSE[201] => PATH: https://api-conformance.ebsi.eu/conformance/v3/issuer-mock/offers/2c8f6bd6-8ffb-4b67-a8e9-93d80f685451 => data: {"credential_issuer":"https://api-conformance.ebsi.eu/conformance/v3/issuer-mock","credentials":[{"format":"jwt_vc","types":["VerifiableCredential","VerifiableAttestation","CTWalletCrossInTime"],"trust_framework":{"name":"ebsi","type":"Accreditation","uri":"TIR link towards accreditation"}}],"grants":{"authorization_code":{"issuer_state":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6InVPa3Y1TE9pbzlYQnE2a1JRaHNaMHpOTVZ1czBjNFZqcFB0cDY1dTVjWXcifQ.eyJjbGllbnRfaWQiOiJkaWQ6a2V5OnpCaEJMbVlteWlodG9tUmRKSk5FS3piUGo1MW80YTNHWUZlWm9SSFNBQktVd3FkamlRUFkyYk5FYzNrRDVmM0J0allWWmZCV0E2V3FZTmV3NGJjQ2N3Mkx0eFJSWmV4WTFkcUFidlZGdkpaeG8zaEVVV2JySmtuTVNoUkdpUjh4SGsxc0hvdml4OEw5UU5XZmNxOUpGWGlBNmFGZTFYckh1dWd3eE5KcXhNdTE2UHZudEJrSGtNeiIsImNyZWRlbnRpYWxfdHlwZXMiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzSW5UaW1lIl0sImlhdCI6MTY5NDY3

**Comment by hawkbee1** [comment]
2/ deferred
REQUEST[GET] => PATH: https://api-conformance.ebsi.eu/conformance/v3/issuer-mock/offers/fdd71f35-5bd4-4f54-a080-11ab40ea7fe1
I/flutter (12592): 💡 | Response | RESPONSE[201] => PATH: https://api-conformance.ebsi.eu/conformance/v3/issuer-mock/offers/fdd71f35-5bd4-4f54-a080-11ab40ea7fe1 => data: {"credential_issuer":"https://api-conformance.ebsi.eu/conformance/v3/issuer-mock","credentials":[{"format":"jwt_vc","types":["VerifiableCredential","VerifiableAttestation","CTWalletCrossDeferred"],"trust_framework":{"name":"ebsi","type":"Accreditation","uri":"TIR link towards accreditation"}}],"grants":{"authorization_code":{"issuer_state":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6InVPa3Y1TE9pbzlYQnE2a1JRaHNaMHpOTVZ1czBjNFZqcFB0cDY1dTVjWXcifQ.eyJjbGllbnRfaWQiOiJkaWQ6a2V5OnpCaEJMbVlteWlodG9tUmRKSk5FS3piUGo1MW80YTNHWUZlWm9SSFNBQktVd3FkamlRUFkyYk5FYzNrRDVmM0J0allWWmZCV0E2V3FZTmV3NGJjQ2N3Mkx0eFJSWmV4WTFkcUFidlZGdkpaeG8zaEVVV2JySmtuTVNoUkdpUjh4SGsxc0hvdml4OEw5UU5XZmNxOUpGWGlBNmFGZTFYckh1dWd3eE5KcXhNdTE2UHZudEJrSGtNeiIsImNyZWRlbnRpYWxfdHlwZXMiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzRGVmZXJyZWQiXSwiaWF0IjoxNj

**Comment by hawkbee1** [comment]
pre-authorized with pincode 
=> get credential

**Comment by ThierryThevenet** [comment]
test 1 ? we already tested on sandbox this step.
Wallet should download openid confid on credentila-issuer-confg, then on authorization-server/openid config
then wallet must do a redirect to the authorization endpoint
same as test 10 oidc4vci 
after that step it is more complicated....issuer sends a request to the openid:// authorization endpoint of teh wallet (client_metdata)

**Comment by ThierryThevenet** [comment]
replaced by several tickets test by test
