### ISSUE TITLE
SIOPV2 / test 4 must succeed with any prefix without changing profile on wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1912]
as treatment is the same for all profiles.

openid-vc://
openid://
siopv2:::

**Comment by hawkbee1** [comment]
![image](https://github.com/TalaoDAO/AltMe/assets/49282360/c8c3c8f4-de93-4a70-b1e1-b6061f3de352)

**Comment by ThierryThevenet** [comment]
cross device
