### ISSUE TITLE
OIDC4VCI -> authorization code flow : Test 10, the callback does not open on Chrome. it works on Safari

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1921]

**Comment by peppelinux** [comment]
is this something related to this issue we have in the italian implm profile https://github.com/italia/eudi-wallet-it-docs/issues/131?

**Comment by ThierryThevenet** [comment]
@peppelinux I have not seen in your posts where you have this kind of issue ? but would be interested to see the Italian Profile to support the ARF !

**Comment by peppelinux** [comment]
FYI

we're going to align credential issuance with OAuth client based attestation and the presentation phase with the pending PRs in openid/openid4vp (removing the dpop on the request uri endpoint)

Milestone 0.6.0 Will brings these

**Comment by peppelinux** [comment]
The issues happens in the same device flow where the http Response Is 302 found

As It Is for the authorization endpoint response during the issuance
