### ISSUE TITLE
Add the liveness card in the Discover

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1932]

**Comment by ThierryThevenet** [comment]
see achille for link, same prinicple as veruifiable id cards

**Comment by hawkbee1** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=3%3A1533&mode=design&t=fwBCZ5p93mgmAw71-1

**Comment by bibash28** [comment]
HowToGetIt, ExpirationDate, WhyGetThisCard => need these info
