### ISSUE TITLE
Support for SD-JWT format?

### ISSUE THREAD

**Issue by crustypluto19** [TalaoDAO/AltMe#1935]
I am interested in issuing VCs in SD-JWT format (according to this [IETF spec on SD-JWT](https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/)) in this [project](https://github.com/GAIA-X4PLC-AAD/gx-credentials) and am currently using Altme for development. I'd like to ask some questions:

- Is the format supported already? How would the disclosures be stored in the wallet?
- Not sure how Altme consumes VC in JWT format (from [VC data model v.1.1](https://www.w3.org/TR/2022/REC-vc-data-model-20220303/#disputes)), here is an example dummy JWT credential I generated and used for testing but Altme simply returns "something went wrong, please try again later".
`eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3JUUG9mVG00eExtbmZXcFNhTWhvRVBURTVGd0QxNEw4RkFjdGhUamk4MzdEI3o2TWtyVFBvZlRtNHhMbW5mV3BTYU1ob0VQVEU1RndEMTRMOEZBY3RoVGppODM3RCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtyVFBvZlRtNHhMbW5mV3BTYU1ob0VQVEU1RndEMTRMOEZBY3RoVGppODM3RCIsIm5iZiI6MTY5NTgyMzc3OC45MjUsImp0aSI6Imh0dHA6Ly9leGFtcGxlLm9yZy9jcmVkZW50aWFscy8zNzMxIiwic3ViIjoiZGlkOmtleTp6Nk1raVNwOFVXUXF5UkJRYXRjQnhURkhRZVhvR3VIRUxDejNDZDg1YWJDMjZ3VXAiLCJ2YyI6eyJAY29udGV4dCI6Imh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaWQiOiJodHRwOi8vZXhhbXBsZS5vcmcvY3JlZGVudGlhbHMvMzczMSIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6a2V5Ono2TWtpU3A4VVdRcXlSQlFhdGNCeFRGSFFlWG9HdUhFTEN6M0NkODVhYkMyNndVcCJ9LCJpc3N1ZXIiOiJkaWQ6a2V5Ono2TWtyVFBvZlRtNHhMbW5mV3BTYU1ob0VQVEU1RndEMTRMOEZBY3RoVGppODM3RCIsImlzc3VhbmNlRGF0ZSI6IjIwMjMtMDktMjdUMTQ6MDk6MzguOTI1WiJ9fQ.mhRjS8-1aCL_LA5U5k0zNEdz9K-rJUO27Bt6hOaX-UezwwXpa5qlscx_ZkzG4rwMFT7YuEcpQBIivYAOFe-iBQ`

Thanks in advance!

**Comment by ThierryThevenet** [comment]
Hello
Yes altme supports JWT formats. The error code you have is probably due to the protocol. Which issuer do you use ? what is the process when  you got that error ?
We do not yet support the SD-JWT format but it is in our plan to support it. It will depend of the use case as tyere very fex projects which supports SD-JWT
Let me know more about your project and environment so we can help ?

**Comment by ThierryThevenet** [comment]
@crustypluto19 the jwt looks almost fine ( need "typ" = "JWT" in header).
You can get JWT VC on that page https://talao.co/sandbox/issuer/oidc/test and the tests for "**EBSI v3 profil** which uses the JWT format . 
Once you have the VC in the wallet you can clic on "SHARE" in the detail page to send it to your email box and look at the content of the payload and header.

**Comment by crustypluto19** [comment]
Since Altme uses Beacon protocol, I was wondering if DIDKit is also used by Altme for issuing JWT VCs?

**Comment by ThierryThevenet** [comment]
we only use didkit for json-ld signing, 
JWT signing is based on JOSE and there are plenty of libs doing that for years.

**Comment by ThierryThevenet** [comment]
@crustypluto19 we are now starting to implement the SD-JWT credntial format.
