### ISSUE TITLE
SIOPV2 / OIDC4VP : verifier response normalization

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1957]
wallet must accept verifier response as :

if status = 200 and no data (application/json) -> nothing happen in the wallet

if status = 200 and data = { 
    "redirect_uri" : "https;....", 
    response_code : "ghfjhgfhg"
}
 wallet must open a webview and redirect user UI to redirect_uri with response_mode as an argument

if status is >399 'error'
Wallet must use the error module and display error, error_description etc....
Be careful the error format is not REQUIRED in that case so wallet does not freeze if the json recieved has no error and no error description.

**Comment by bibash28** [comment]
wallet does not freeze if the json recieved has no error and no error description.

`it will take default error = request is not supported`
