### ISSUE TITLE
Check wallet has all required deeplinks 

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1990]
Some of those deeplinks are not in ios and android configuration
num OIDC4VCType {
  DEFAULT(
    offerPrefix: 'openid-credential-offer://',
    presentationPrefix: 'openid-vc://',
  ),

  GAIAX(
    offerPrefix: 'openid-initiate-issuance://',
    presentationPrefix: 'openid://',
  ),

  GREENCYPHER(
    offerPrefix: 'openid-credential-offer-hedera://',
    presentationPrefix: 'openid-hedera://',
  ),

  EBSIV3(
    offerPrefix: 'openid-credential-offer://',
    presentationPrefix: 'openid-vc://',
  ),

  JWTVC(
    offerPrefix: '',
    presentationPrefix: 'openid-vc://',
  );

**Comment by hawkbee1** [comment]
check again @hawkbee1

**Comment by ThierryThevenet** [comment]
I suppose it is ok
