### ISSUE TITLE
Documentation: licensing

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2023]
The main readme still shows a batch indicating a MIT license even if the license text is according to Apache 2.0

Header including a copyright statment and SPDX license identifier are missing like in tis example header:

//
// Copyright 2016 -- 2018 Contributor Company Nr. 1
// Copyright 2023 Contributor Company Nr. 2
// SPDX-License-Identifier: Apache-2.0
//

Look at the [SPDX documentation](https://spdx.dev/learn/handling-license-info/) for further information.

**Comment by hawkbee1** [comment]
Not sure I'm getting your point.
The MIT license part comes from very good cli, a flutter tool provided by very good venture: https://pub.dev/packages/very_good_cli

**Comment by jdsika** [comment]
This is the LICENSE file in the [root directory](https://github.com/TalaoDAO/AltMe/blob/main/LICENSE). It states in line 189    "Copyright [yyyy] [name of copyright owner]" which means it has been copied but not filled with the project specific information.

The main readme has a banner which signals to the user that the whole project is under MIT license which contradicts the information of the license file:
![grafik](https://github.com/TalaoDAO/AltMe/assets/11943343/93c41068-38dc-4ddb-8837-807920615df2)

In addition it often is the case that software modules are used and e.g. copied from other projects. in this case the files should be separated in the repository and each file should have a SPDX license identifier stating two things:

1) Under which license is this file
2) Who owns the copyright

My point is that the repositories licensing and copyright situation is not clearly documented according to best practices like e.g. SPDX is providing.

Best regards
Carlo
