### ISSUE TITLE
Doc: Securtiy audits

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2024]
Hi team,

have there any external security audits been conducted for altme or is there any specific documentation regarding IT security?

I am giving an example for a wallet like e.g. Temple here:
https://www.cossacklabs.com/case-studies/temple-wallet/

I would need this for application approval at BMW.

Best regards
Carlo

**Comment by hawkbee1** [comment]
here is the last code audit on Altme.
[AltMe security audit report for Web3 Digital Wallet.pdf](https://github.com/TalaoDAO/AltMe/files/13061196/AltMe.security.audit.report.for.Web3.Digital.Wallet.pdf)

**Comment by jdsika** [comment]
You could link this in the readme or the docs somewhere, thank you!

**Comment by jdsika** [comment]
@hawkbee1 I don't consider this solved if the information cannot be found in the docs

**Comment by hawkbee1** [comment]
Added to project Readme @jdsika
