### ISSUE TITLE
Update license file 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2042]

**Comment by jdsika** [comment]
links to #2023

**Comment by ThierryThevenet** [comment]
license updated on repo @jdsika

**Comment by jdsika** [comment]
@ThierryThevenet please have a look at the things that I have written in my issue as well.

**Comment by hawkbee1** [comment]
badge and opensource link are updated in main Readme

**Comment by jdsika** [comment]
Thx!
I recommend keeping a "nice to have Todo" to comply with SPDX inside the whole project which would mean that you have to change every file header...

**Comment by hawkbee1** [comment]
https://github.com/TalaoDAO/talao-wallet/issues/336
