### ISSUE TITLE
Feature to remove 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2045]
![Screenshot_20231024_100517](https://github.com/TalaoDAO/AltMe/assets/32768069/e11c9d8c-27ee-4e99-a02f-3f5d3775650a)

**Comment by bibash28** [comment]
We have two rewards section.
1. UNO Reward
2. XTZ Reward

Should we remove both???
@hawkbee1 @ThierryThevenet
