### ISSUE TITLE
Bug: Application not detected 

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2046]
When I use both features
* verify phone
* verify email

I am forwarded to the phones browser (Firefox mobile) and it asks me to chose one of the two applications
* altme
* Talao

If I click on altme then it tells me that it is not installed even if it is the case.
The import of the VC works when I click
* open in app

Expected behavior:
It searches successfully for both apps on the phone. If one is detected then it is automatically chosen. If both are detected then I am offered a choice.

![Screenshot_20231024-150800](https://github.com/TalaoDAO/AltMe/assets/11943343/99c492f5-e86a-4b73-9d21-c88f5b3cecda)
![Screenshot_20231024-150806](https://github.com/TalaoDAO/AltMe/assets/11943343/834b0994-5668-43b4-a75f-b4c48feb1440)

**Comment by hawkbee1** [comment]
Firefox handles universal link differently, this should solve the issue: https://support.mozilla.org/en-US/kb/set-firefox-android-open-links-native-apps

**Comment by jdsika** [comment]
Ok, thx. This is for the "automatic opening" BUT isn't it a bug that your website does wrongly state "the application is not installed"?

**Comment by hawkbee1** [comment]
Concerning the website we can't know if the app is installed or not. We just see that a universal link is called and guess that app is not installed.
Normal behavior doesn't imply calling the website (with app installed).

**Comment by jdsika** [comment]
My case is Android. But ok, if it is not possible to check the installation status (privacy + security reasons) then maybe adapt the message to the user to better understand what's happening?

https://stackoverflow.com/a/12901352/2883130

**Comment by hawkbee1** [comment]
yes, I will ask again to add information about browsers issues on the website screen.

**Comment by ThierryThevenet** [comment]
is it still an issue ? @jdsika
