### ISSUE TITLE
Confusing: wrong domain

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2048]
I wanted to search for this service on the altme.io website and was not able to find it!

Then I asked google and found the blog post leading to:
https://talao.co/altme-identity

It confuses that this is running on the talao.co website (even if the logo says altme) and if I press "back home" then I am redirected to altme.io!

**Comment by jdsika** [comment]
@hawkbee1 shouldn't this be able to be found under https://altme.io/verifiable-credentials/ ?

**Comment by ThierryThevenet** [comment]
At the moment we use several domains as company domains fro our tools.
- talao.io (web site + app site)
- talao.co (issuers and verifiers)
- altme.io (website + app site )

**Comment by jdsika** [comment]
I am not sure if this solves the issue. As a user I was not able to figure this out...
