### ISSUE TITLE
Bug: Endless loop account renaming

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2049]
System:
IOS
iPhone 12,8
System Version: 16.7.1
Wallet Build: 1.23.0 (302)

How to reproduce:
I installed the app. Initialize the wallet creating new set of addresses with seed words.
Click on edit the name of the account. 
Enter name and click "save"
New name is displayed and the system is in endless loop (see screenshot)

If I force shutdown the application and restart it I can see the chnaged name.

Expectation:
No endless Loop

![bug](https://github.com/TalaoDAO/AltMe/assets/11943343/57f9400d-e262-4e5d-8d00-16291bc64efd)

**Comment by dansan566** [comment]
Experienced the same!

**Comment by dansan566** [comment]
Also, if you close the App and go back in, the account has been renamed accordingly. However, there are two account ownership cards with the same address: 

![image](https://github.com/TalaoDAO/AltMe/assets/20326784/78a9e96e-b94e-45c0-b831-185d6927d7b4)

**Comment by jdsika** [comment]
This was a good catch from Daniel! So this duplicated card I have described in my issue is happening because of the account renaming

              Thanks for your feedback @jdsika, I will probably create several tickets. I understand you have twos ownership cards in "My blockchain accounts" section, both identical. Could you tell me which network is written on the cards ?

_Originally posted by @hawkbee1 in https://github.com/TalaoDAO/AltMe/issues/1716#issuecomment-1609633298_
