### ISSUE TITLE
Feature Request: Company Profile Configuration

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2057]
As a company I would like my employees to use the Altme wallet for certain tasks and applications. As an administrator I want to deploy a company profile that sets the general settings of the application.

Examples:
* I want only certain networks to be visible (e.g. disable BNB)
* I want employees e.g. to allow or not allow the use of the developer mode
* I want to hide certain services in the "Discover" section

Best regards
Carlo

**Comment by hawkbee1** [comment]
That's a lot of work and we need to discuss it in the team... According to me, forbidding user to use some features is an issue and means creating a specific wallet based on Altme. We already created specific wallets for some compagnies.

**Comment by jdsika** [comment]
Often products have hidden beta features which are enabled for certain users only and the features are tested and decided on based on the feedback of the users.

It is an architectural choice on how to enable something like this. I think you should discuss it as creating new wallets all the time is a maintenance nightmare.

I found the same issues in talao as I already reported in altme and this is your best example why it doesn't work the way you currently do it.

My 2 cents :D

**Comment by ThierryThevenet** [comment]
This iis going to be the next big feature of Altme and Talao wallet. A portal is in development to configure the wallet dynalically.

**Comment by ThierryThevenet** [comment]
@jdsika What kind of features of the Discove would you want to hide ?r

**Comment by ThierryThevenet** [comment]
This feature is available in beta.
