### ISSUE TITLE
Issue: Failed to generate key, please try again

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2058]
Hello,

I've tried to import a Tezos Ghostnet account into my Altme wallet using the private key method. I've been attempting the import during the first initialization of the Altme Wallet using iOS 16.6.1 with an iPhone 12 (Wallet build: 1.23.0). The field where I could paste the private key turned green but then I got the message "Failed to generate key, please try again". I've tried it multiple times.

Today, I wanted to reproduce the error to report this issue. Suddenly, I see the "My wallet" view without having finished the first initialization. I also tried importing an additional Tezos Ghostnet account using the "Add account" functionality with the private key but still got the "Failed to generate key, please try again" error message.

**Comment by hawkbee1** [comment]
How did you create your Tezos Ghostnet account, a specific app @dansan566 ?

**Comment by dansan566** [comment]
If I remember correctly @jdsika, the accounts were created from the source. Funnily, it works if I use the Temple "Reveal Private Key" functionality and then import it into Altme!

**Comment by dansan566** [comment]
I just double-checked and imported the private key into Temple - it worked!

**Comment by hawkbee1** [comment]
"created from the source" ? @dansan566 @jdsika  ?

**Comment by dansan566** [comment]
yes, from the Tezos source code using the octez (tezos) client.

**Comment by dansan566** [comment]
@hawkbee1 Altme Import says "Once you have entered your 12 words (recovery phrase) or 54 characters private (private key), tap Import. 

My 54 character private key does not work, my 98 character key (the export from temple) works :)
