### ISSUE TITLE
Expected behavior? Close/Open AltMe Wallet App sets back the network settings 

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2064]
I chose the Tezos Ghostnet in "Blockchain network (by default)". When I close the AltMe Wallet App and go back into the App, the network is set to Tezos Mainnet again. Is this an expected behavior? I felt a little bit annoyed because I often close and reconnect it and sometimes I forget to set it to Tezos Ghostnet :)

**Comment by dansan566** [comment]
It also sets back the network settings when adding a new account

**Comment by jdsika** [comment]
This is extremely annoying! Please show the currently persistent network in the top right under account (as e.g. temple wallet does it). It is a terrible UX and an impossibility to change the network to ghostnet under settings for every interaction.

**Comment by dansan566** [comment]
It even changes by switching accounts which is indeed very painful.

**Comment by ThierryThevenet** [comment]
fixed on build 1.24.7
