### ISSUE TITLE
Feature Request: Remove account

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2065]
I think it would be a handy feature to remove an account in Blockchain Settings -> Manage blockchain accounts. Currently, I do it with "Reset Wallet".

**Comment by ThierryThevenet** [comment]
to be designed @HugoNDO

**Comment by ThierryThevenet** [comment]
see with @HugoNDO for desgn

**Comment by dansan566** [comment]
@HugoNDO how about a "swipe left" functionality with a trash bin appearing? Like Apple does it when deleting messages or recent phone calls.

![image](https://github.com/user-attachments/assets/0881a754-65f0-490d-8052-57cbd8172901)

**Comment by ThierryThevenet** [comment]
Yes we are going to look at it
@HugoNDO @bibash28

**Comment by ThierryThevenet** [comment]
done in build 2.9.11
