### ISSUE TITLE
Altme can not load Ghostnet XTZ balance

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2073]
It's currently not possible to display the Tezos Ghostnet balance on Altme. I set the network to Ghostnet and the account has a sufficient balance. There is an error message "Something went wrong, please try again later." If I click the button "Try again", I get an error message "Something went wrong, please try again later."

Maybe the tzkt API can help to fix it!

**Comment by hawkbee1** [comment]
Strange 🤔
We are using tzkt API

**Comment by dansan566** [comment]
@hawkbee1 working now! seems it was a temporary issue. The issue can probably be closed!

**Comment by dansan566** [comment]
Proof of Issue:
![IMG_6836](https://github.com/TalaoDAO/AltMe/assets/20326784/4f558e6c-0e86-4bc0-85ab-8e99c5681bf9)

**Comment by ThierryThevenet** [comment]
Solved in last build
