### ISSUE TITLE
Bug: Altme Soft-locks on Beacon Connect

### ISSUE THREAD

**Issue by jfelixh** [TalaoDAO/AltMe#2074]
Hi everyone,

I might have found a breaking bug or I am missing something crucial. Beacon connection just does not work at all after switching phones from an iPhone Xs Max to a 12 Pro Max, both on iOS 17. It is a bit weird, because Altme works on the old phone, but not on the new one, even though both run the exact same versions of Altme and iOS.

This is being a major annoyance and I appreciate any help!

# Steps to reproduce

1. Clicking "connect wallet" on any relevant website (e.g. https://faucet.ghostnet.teztnets.xyz/) in my browser on desktop.
2. Choosing Altme and getting a QR code.
3. Using Altme to scan the QR code.

iPhone 12 Pro Max, iOS 17.0.3, Altme Version 1.23.0 (302)

# What happens

Altme gets completely soft-locked in the "Please wait a moment..." overlay. This goes on for at least 10 minutes and can only be remedied by closing Altme in the multitasking menu. The website I am trying to connect to displays no indication of any progress.

# What I expect

Altme should ask if I want to connect and actually connect to the website. The website is supposed to display the connection happening in the top right corner.

# What I tried so far

I reset the Altme Wallet completely and set it up with fresh keys generated by Altme.

**Comment by bibash28** [comment]
Tested in iPhone 14 pro max, iOS 17.0.3, Altme version 1.24.1(314)

Successfully connected to dApp.

**Comment by jfelixh** [comment]
Error unfortunately consistently happens. Beacon has not worked with Altme since ticket opening.
Current software details:
Altme v2.0.8 (345)
iOS 17.2.1

OID4VC qr codes work. Connecting via a Beacon qr code does not work on any of the handful of websites I tried. Altme always freezes and remains frozen forever. To somewhat try to circle in on the issue, I installed Temple Wallet on my iPhone and with that, Beacon worked as expected.

I understand that this problem is probably hard to track down and am willing to have a call to show the issue.

**Comment by hawkbee1** [comment]
We are not able to reproduce the issue.
There are some technical changes in last version (2.2.13 ios), could you tell me if it change the behavior of your new phone @jfelixh  ?

**Comment by jfelixh** [comment]
Just tested on newest iOS and Altme Versions. I also reset the wallet a couple of times. Issue unfortunately persists:
![image](https://github.com/TalaoDAO/AltMe/assets/9974641/b2279fde-5ad4-48fd-b2aa-705833b7ad56)

**Comment by ThierryThevenet** [comment]
see new ticket https://github.com/TalaoDAO/AltMe/issues/2588
