### ISSUE TITLE
Bug xtz transfer

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2075]
When trying to press the 'confirm' button to send xtz to another addresd, a popup telling "something went wrong, please try later" makes the transaction impossible

**Comment by jdsika** [comment]
I am guessing unstable RPC. Maybe you should consider using [tzpro](https://tzpro.io/) as an API provider. It is the successor of tzstats from Blockwatch (Alexander Eichhorn) and I just successfully tested it.
