### ISSUE TITLE
2FA : add a third option to get Biometric and PIN check at wallet creation or later

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2095]
see @HugoNDO for UX design

**Comment by HugoNDO** [comment]
Onbboarding : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=7223%3A11995&mode=design&t=BKqlqtMoZh6SLvsA-1

Drawer : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=3759%3A9853&mode=design&t=BKqlqtMoZh6SLvsA-1

**Comment by ThierryThevenet** [comment]
Hedera grant

**Comment by ThierryThevenet** [comment]
@bibash28 You have done this one
