### ISSUE TITLE
question: w3c credentials v2  & review of ASC(S custom credentials 

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2113]
Do you support "https://www.w3.org/2018/credentials/v2"?

**Comment by ThierryThevenet** [comment]
We are following the WG for https://www.w3.org/TR/vc-data-model-2.0/
As far as what we have seen up to now they are loosen the specs to accept different VC format as JWT, CBOR and SD-JWT and anoncreds with BBS+ signature. So yes we can say atht we support

**Comment by jdsika** [comment]
I realized that my question was stupid when I looked at the release of the version 2... I asked because I wanted to know what I need to follow to be compatible with altme.

I would be happy about a review/tuning of our credentials that you offered:

https://github.com/ASCS-eV/credentials
