### ISSUE TITLE
Deeplink doe not work on Samsung internet browser, need to find a solution

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2120]

**Comment by hawkbee1** [comment]
deeplink or universal link?
@ThierryThevenet For me it means using webview instead of normal phone browser.
Or the solution is outside of the wallet like giving explanation to the user on our website instead of direclty sending him to the store when wallet is not opened through universal link.

**Comment by ThierryThevenet** [comment]
To be tested with Talao new build + samsung explorer
