### ISSUE TITLE
wallet configuration update / Full process

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2133]
need https://github.com/TalaoDAO/AltMe/issues/2116 before

user clic on button "update wallet configuration" see @HugoNDO for design

**Step 1 : update button is static in the drawer**

wallet call eth /nonce endpoint to get a nonce and then wallet call the /configuration endpoint to get an updated configuration file.
same authentication as for creation

**Comment by HugoNDO** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=7232%3A20410&mode=design&t=f1M62VIdiqjO7Sw1-1

**Comment by ThierryThevenet** [comment]
il faut en rediscuter parcequ il nous faudrait une solution simple sans notification chat pour le court terme @HugoNDO
