### ISSUE TITLE
2 wallet enterprise screens to be improved

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2141]
it lokks strange to ogetr 2 blue butto box ? @HugoNDO 

![File (4)](https://github.com/TalaoDAO/AltMe/assets/32768069/792fcf2e-2ae1-4088-bbcd-a0d37c7f0161)

The "Login" word is not really great here as there is n o login but just a call to get a wallet attestation and a confuguration file. It is more an initialization step @HugoNDO 
 
![File (3)](https://github.com/TalaoDAO/AltMe/assets/32768069/50ca3f73-e2ae-434f-a629-09a83140b92c)

**Comment by ThierryThevenet** [comment]
@bibash28 see new figma where the "import button" is moved to another screen
@HugoNDO

**Comment by HugoNDO** [comment]
Here is the new flow : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=7232%3A20410&mode=design&t=4Aw7Dp2z8nXGU20N-1


<img width="1195" alt="Capture d’écran 2023-12-05 à 17 11 58" src="https://github.com/TalaoDAO/AltMe/assets/108657151/70ccba97-175f-4c1d-9ba3-518a6bc8ad6a">

**Comment by HugoNDO** [comment]
<img width="665" alt="Capture d’écran 2023-12-05 à 17 14 07" src="https://github.com/TalaoDAO/AltMe/assets/108657151/f065a0c7-8447-422f-93fc-4557709c3840">

**Comment by HugoNDO** [comment]
<img width="803" alt="Capture d’écran 2023-12-07 à 09 35 17" src="https://github.com/TalaoDAO/AltMe/assets/108657151/3ad9f512-22dc-4189-9963-b53323677937">
