### ISSUE TITLE
Wallet Configuration : Splashscreen with company logo

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2154]
see @HugoNDO  for design

**Comment by ThierryThevenet** [comment]
use tagline from configuration jwt and logo url

**Comment by HugoNDO** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?type=design&node-id=7390%3A20636&mode=design&t=8EiQ6c4q9eKefFks-1

**Comment by HugoNDO** [comment]
![7](https://github.com/TalaoDAO/AltMe/assets/108657151/202037b7-f32f-4a36-8ea9-a0a7358366bb)
