### ISSUE TITLE
Credential formats don't match OIDC4VCI specification

### ISSUE THREAD

**Issue by vincentkelleher** [TalaoDAO/AltMe#2178]
Hi 👋 

I've been working on implementing OIDC4VCI in the [Gaia-X Registration Number Notary](https://gitlab.com/gaia-x/lab/compliance/gaia-x-notary-registrationnumber) with the help of [Sphereon's Issuer Library](https://github.com/Sphereon-Opensource/OID4VCI/tree/develop/packages/issuer). My main testing tools is have been the AltMe wallet and [Trustbloc's Wallet CLI](https://github.com/trustbloc/vcs/tree/main/component/wallet-cli).

After having some issues during VC issuance through the AltMe wallet, I had a quick look at the source code where I noticed that the credential format in issuer metadata and credential requests doesn't match the [OIDC4VCI specification](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#format_profiles).

In [Appendix E.1](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#appendix-E.1), three formats are defined :
- `jwt_vc_json`, VC signed as a JWT, not using JSON-LD
- `jwt_vc_json-ld`, VC signed as a JWT, using JSON-LD
- `ldp_vc`, VC secured using Data Integrity, using JSON-LD, with proof suite requiring Linked Data canonicalization

In [many parts of the AltMe wallet source code](https://github.com/search?q=repo%3ATalaoDAO%2FAltMe%20jwt_vc&type=code) the `jwt_vc_json` format is defined as `jwt_vc` which causes issues with OIDC4VCI compliant issuers.

I imagine that changing this can have a big impact on existing solutions that comply with the AltMe wallet. What is your position about this subject ? Can it be fixed ?

**Comment by ThierryThevenet** [comment]
Hello,
Yes we know quite well this issue and it will be fixed soon. I would say that the oidc4vci is evolving fast and altme target is to support draft 8, 11, 12 and soon 13 of oidc4vci. We also have tested the wallet with the dutch blockchain coalition issuer made by sphereon, it is fine, it will be available next week. If you have an issuer ready for testing contact me thierry.thevenet@talao.io we will work on it.

**Comment by ThierryThevenet** [comment]
done in next build
