### ISSUE TITLE
OIDC4VCI Test 1 with profile Ebsi fails

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2196]

**Comment by ThierryThevenet** [comment]
fails

**Comment by ThierryThevenet** [comment]
fails for me

**Comment by bibash28** [comment]
![Image](https://github.com/TalaoDAO/AltMe/assets/18188709/fecbf2ee-eae8-4694-abdb-d75c2c873c9d)

issuer data is missing in the credential preview

**Comment by bibash28** [comment]
@ThierryThevenet
