### ISSUE TITLE
OIDC4VCI test 2  and test 3 : no VC data are displayed in card details when credential manifest  switch is on ? (ldp_vc format)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2208]
If format is ldp_vc ou jwt_vc_json-ld then 
If switch is credential manifest use it else use "display" attribute

If format is jwt_vc or jwt_vc_json then only "display"

**Comment by bibash28** [comment]
![Image](https://github.com/TalaoDAO/AltMe/assets/18188709/9674c520-f8c6-421d-8786-e0b44f5b2464)

issue with test 3
