### ISSUE TITLE
Android Dark Mode Splash Screen is not correct 

### ISSUE THREAD

**Issue by demirdev** [TalaoDAO/AltMe#2279]
I created a flutter project with this command.
 
`very_good create flutter_app android_splash_problem`

In Android 13 device in Dark Mode, I seen splash screen may be have an overlay or another thing on top of it. 
I also changed the SVG logo color to another color (red) , but it looks like there is a light gray layer in the logo.

How can I solve this?

### yours default color
![screenshot](https://github.com/TalaoDAO/AltMe/assets/54906407/17769ea3-63d3-4f0c-8bb0-d57c5d102f0b)

### after changing color to #FF0000 (red)
![screenshot](https://github.com/TalaoDAO/AltMe/assets/54906407/9cc7a501-e12d-44b6-bada-380ddb45cbba)

**Comment by hawkbee1** [comment]
You should ask the appropriate project: https://pub.dev/packages/very_good_cli

**Comment by demirdev** [comment]
I realized later that I opened a record in the wrong place. I cannot delete this record now. Thank you for your quick reply.
