### ISSUE TITLE
Altme displays "This request is not supported" when I want to download my company or user credential to an Android smartphone

### ISSUE THREAD

**Issue by jtdemer** [TalaoDAO/AltMe#2333]
**What I'm trying to do:**
Downloading my company or user credential from DEMIM https://identity.ascs.digital/ to my Altme wallet of my Samsung Ultra 

**What happens**
Altme shows a message that "This request is not supported"!

**Screenshots**
![IMG-20240129-WA0035](https://github.com/TalaoDAO/AltMe/assets/48685701/5cd20c6d-e74f-46a4-8b28-cb804e4c49b3)
![IMG-20240129-WA0036](https://github.com/TalaoDAO/AltMe/assets/48685701/f35e1c1b-98e6-49dc-aace-55a74f8cfdfb)
![IMG-20240129-WA0037](https://github.com/TalaoDAO/AltMe/assets/48685701/652f3c2c-5a39-4ce4-9c47-c8540fbf4dde)
![IMG-20240129-WA0038](https://github.com/TalaoDAO/AltMe/assets/48685701/3e2fd615-be3e-44d7-8e08-304d43e12d12)

**More infos**
Software version from the phone:
One UI-Version: 6.0   
Safetypatch level 1: 01.01.2024
latest version

Version of Altme App:
Version 2.2.3
last update from 23.01.2024
latest version

**What I expected to happen**
I'm should be able to download the credential as a card

**Other info**
If I do the same procedure on an apple phone it would work

**Comment by ThierryThevenet** [comment]
Hello
Is there an issuer where we can reproduce the problem ?

**Comment by hawkbee1** [comment]
Where can I get an Asc(s credential @jtdemer to see what's happening under the hood?
I filled a form for membership with fake data except the email.

**Comment by jtdemer** [comment]
> Where can I get an Asc(s credential @jtdemer to see what's happening under the hood? I filled a form for membership with fake data except the email.

@hawkbee1 did you used an account with the Tezos Ghostnet for register and did you click on sus

**Comment by hawkbee1** [comment]
Yes, of course. I'm connecting with beacon on testNet (In Altme I have a message when I'm not using the correct Network).
After the register button I have to choose between "Membership identity" and "User Identity"
![image](https://github.com/TalaoDAO/AltMe/assets/49282360/d75d263c-4148-42b5-9a2f-c37957c73657)

For both choice I have different screens and a register form at the end. @jtdemer

**Comment by jtdemer** [comment]
I didn't expect that you register for the company ascs. But I found you now an approved your registration. You should now be able to download the credential.

**Comment by hawkbee1** [comment]
There are some technical changes in last version (2.2.14 android), could you tell me if it change the behavior of your phone @jtdemer   ?

**Comment by jtdemer** [comment]
I have tested it, but it does not work. It seems you can't currently log in/connect with altme (Android 14, One Ui version 6.0) to beacon. @hawkbee1

**Comment by hawkbee1** [comment]
I am now able to get to the presentation step after successful connection :-)
I get same error as you and the exact error is the following: 
Response | ERROR[500] TYPE[DioExceptionType.badResponse],=> PATH: https://identity.ascs.digital/api/credentials/user data: {error: Invalid presentation}
It looks like that's a wallet issue, I'm investigating and will probably update Altme during the week.

**Comment by ThierryThevenet** [comment]
Great !
