### ISSUE TITLE
OIDC4VCI Draft 13 and above : attribute format is no more in the response of the credential endpoint

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2347]
**complete other tickets about Draft 13 before this one.**

example of a response
```

HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store

{
  "credential": "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L",
  "c_nonce": "fGFF7UkhLa",
  "c_nonce_expires_in": 86400
}
```
only `credential` attribute is REQUIRED if `transaction_id` is not returned
if transaction_id (replace the acceptance token) is present it is a deferred use case -> later another ticket

**Comment by bibash28** [comment]
we are not using format from credential response
