### ISSUE TITLE
Simplify the process of the enterprise wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2433]
At creation store email and password that are privided by user to get the wallet config file.

When user clics on update enterprise wallet config bypass the screen to enter login/password and get the new config file

**Comment by hawkbee1** [comment]
- Onboarding: no more entreprise button => user create or import wallet as before entreprise stuff
- Entreprise account creation comes with a specific link like: configuration://?password=xfdfcf&login=test@gmail.com&wallet-provider=https://wallet-provider.talao.co

NB: online QR code generator: https://www.the-qrcode-generator.com/

**Comment by ThierryThevenet** [comment]
@bibash28 
I have tried to get my enterprise account through the  qrcode -> `configuration://?password=BZZJQT&login=thevenet_thierry1963@gmail.com&wallet-provider=https://wallet-provider.talao.co`

but the scanner display "Format nor supportedé

**Comment by ThierryThevenet** [comment]
![test](https://github.com/TalaoDAO/AltMe/assets/32768069/af5e3de0-cccd-48aa-a1f3-51e194203b6d)

**Comment by ThierryThevenet** [comment]
![configuration](https://github.com/TalaoDAO/AltMe/assets/32768069/efcf79c0-6d74-45e3-8e4a-0dde0280d73a)

**Comment by ThierryThevenet** [comment]
![configuration(1)](https://github.com/TalaoDAO/AltMe/assets/32768069/486d6b05-73f0-4f02-9908-195f009b0cff)


**configuration://?password=BZZJQT&login=thevenet_thierry1963@gmail.com&wallet-provider=https://wallet-provider.talao.co**
