### ISSUE TITLE
Enterprise wallet : when  we add an issuer Over18 and other OverXX in a ldp_vc format, wallet fails

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2435]
**Do not propose Yoti on enterprise wallet profile** but only the issuer with ID360

when parameter is "`displayOver18": true,`, API call should be https://talao.co/id360/oidc4vc?format=ldp_vc&type=over18
same for other parameter Over15 -> https://talao.co/id360/oidc4vc?format=ldp_vc&type=over15
21, 50, 13, 65

 ```
 "discoverCardsOptions" : {
        "displayRewardsCategory": true,
        "displayOver18": true,

```

remove API call https://talaop.co/id360/get_code  which useless

**Comment by hawkbee1** [comment]
This one needs to go directly to main branch

**Comment by hawkbee1** [comment]
Yes same for jwt_v_json
For sd-jwt , it is not needed as the selective disclosure on the verifiable id includes everything in the VC!





[08:36](https://talao.slack.com/archives/C03V9HU19DM/p1708673792856629)
Currently the missing oidc4vc issuer are : nationality, agerange, phoneproof
