### ISSUE TITLE
Downloaded VC in ALTME are gone and can't be restored, Android Phone

### ISSUE THREAD

**Issue by jtdemer** [TalaoDAO/AltMe#2457]
**What I'm trying to do:**
After the latest Upgrade on Friday 23.02.2024 my downloaded VC are gone, and it is not possible to restore them. Even when I set up the wallet complete new.

I recieved the same fault what I already reportet on issue 2333. https://github.com/TalaoDAO/AltMe/issues/2333
It is again not possible to download my company or user credential from DEMIM https://identity.ascs.digital/ to my Altme wallet of my Samsung Ultra 

** What happens **
After the latest update all stored credentail are gone. By trying to restore them, I get the fault: This request is not supported

@hawkbee1 can you help please?

**Comment by hawkbee1** [comment]
That's probably just a setting issue after last update of wallet default settings. Are you using default profile or custom profile ?

**Comment by jtdemer** [comment]
Thanks for the fast reply, I'm used the default profile. 

Now I tried out all availible profiles, all with the same issue
![WhatsApp Bild 2024-03-01 um 17 40 04_a7158bbe](https://github.com/TalaoDAO/AltMe/assets/48685701/8189ccc0-b856-41e1-9749-4c80b929734f)

**Comment by hawkbee1** [comment]
Looks like a traditionnel credential offer for me. When presenting my Account Ownership card the verifier respond with http 500 error. 
I have also a 500 issue with older version of Altme.
What keys are you accepting ?
Can you get more information on the error from the verifier ?

**Comment by jdsika** [comment]
Did you use a version from December/January? There where no changes to DEMIM
