### ISSUE TITLE
Wallet suspension.does not work

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2582]
A status list has been added to the wallet attestation

Check status list of wallet attestation if it exists (**same process as sd-jwt status list)**

```
status": {
    "status_list": {
      "idx": 53544,
      "uri": "https://talao.co/sandbox/issuer/statuslist/1"
```

If the wallet attestation  is suspensed, diplay message "This wallet is suspended" for 10 seconds.

The test must be done when the app is launched only.

use same rule for cache : by default 2 days, if switch if off, no cache

**Comment by ThierryThevenet** [comment]
It does not work, i revoked the status list of teh wallet and nothing happen
the status list is the same as sd-jwt status list

**Comment by ThierryThevenet** [comment]
**We should get a popup when we open the app if the wallet attestation has been revoked.**

**Comment by bibash28** [comment]
**when we set the cache swich on Off, we dont see any call on the server to get the status list ?? **

cached for two days.. the call is made after 2 days only..

**Comment by ThierryThevenet** [comment]
does not work for me
The status list is fetch but I dont see the popup
