### ISSUE TITLE
Scanning Beacon generated QR no longer works

### ISSUE THREAD

**Issue by royscheeren** [TalaoDAO/AltMe#2588]
Steps to reproduce:

- Go to any Tezos dApp that uses beacon to request wallet permissions. Ie tzkt.io
- Click on connect wallet (or wallet icon in case of tzkt.io)
- Choose altme
- Scan QR code with altme wallet

Result:
Altme goes back to default screen and nothing happens

Expected behavior:
I'm able so sign in using my altme wallet.

**Comment by ThierryThevenet** [comment]
It is ok with IOS build 2.4.17 and android 2.4.11

which config do you have ?

**Comment by royscheeren** [comment]
I've got 2.4.11 (431) on Android, and it does not work when trying ie https://app.plenty.network/pools/v3 or https://app.playstables.io/en/login

**Comment by ThierryThevenet** [comment]
@bibash28 in my side both sites are ok with IOS but both fails with Android (2.4.11)

**Comment by bibash28** [comment]
What device model are you using? @ThierryThevenet @royscheeren

**Comment by jdsika** [comment]
Google Pixel 7a newest Android update

**Comment by ThierryThevenet** [comment]
On our side it looks like Stables (r https://app.playstables.io/en/login) has an app issue as Temple does not pass neither.

The other site is fine on our tests with Samsung devices, We are trying now to explore with the Beacon team a possible issue with Pixel phones as we already had specific issues with Pixel phones/beacon.
@royscheeren

**Comment by royscheeren** [comment]
I use a Samsung galaxy a80. I just tried again unsuccessfully.

**Comment by jdsika** [comment]
@bibash28 It is still not working on Google Pixel 7a , Altme v2.4.22

**Comment by royscheeren** [comment]
Yes we might have to reopen this. I was able to log in just fine on Friday with the beta, but trying it again today, back to the same problem as described above. cc @ThierryThevenet

**Comment by ThierryThevenet** [comment]
@bibash28

**Comment by ThierryThevenet** [comment]
@bibash28 
 It is unstable with Android Samsung, it does not work at all then later it works well..
It looks like in same device scenario it is better ?  could it be a QR code reading issue ?
