### ISSUE TITLE
This OIDC4VC request is rejected by the wallet at reading  because teh wallet cannot verify the signature of the request jwt 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2603]
this is the verifier request object as a jwt :

eyJraWQiOiJkaWQ6d2ViOmRpZC5hZGFwdGl2ZXNwYWNlLmlvOm5lbTpzYXRzdW1hIzIzZDc0NGI4LWY4NGItMTFlZS05NWUwLTE3NTZhMjdkZDhkNSIsImFsZyI6IkVkRFNBIn0.eyJyZXNwb25zZV91cmkiOiJodHRwczovLzE5ZDYtMTc4LTIyMC0xMDktMjUwLm5ncm9rLWZyZWUuYXBwL3ZlcmlmaWNhdGlvbi9jYWxsYmFjayIsImF1ZCI6Imh0dHBzOi8vc2VsZi1pc3N1ZWQubWUiLCJjbGllbnRfaWRfc2NoZW1lIjoiZGlkIiwiaXNzIjoiZGlkOndlYjpkaWQuYWRhcHRpdmVzcGFjZS5pbzpuZW06c2F0c3VtYSIsInJlc3BvbnNlX3R5cGUiOiJ2cF90b2tlbiIsInByZXNlbnRhdGlvbl9kZWZpbml0aW9uIjp7ImlkIjoiOGExNDIzOTktZjk2ZS0xMWVlLTlhNDgtMGExNjI4OTU4NTYwIiwiaW5wdXRfZGVzY3JpcHRvcnMiOlt7ImlkIjoiZW1haWxwYXNzXzEiLCJjb25zdHJhaW50cyI6eyJmaWVsZHMiOlt7InBhdGgiOlsiJC5jcmVkZW50aWFsU3ViamVjdC50eXBlIl0sIm9wdGlvbmFsIjpmYWxzZSwiaWQiOm51bGwsIm5hbWUiOm51bGwsInB1cnBvc2UiOm51bGwsImZpbHRlciI6eyJwYXR0ZXJuIjoiRW1haWxQYXNzIiwidHlwZSI6InN0cmluZyJ9fV0sImxpbWl0X2Rpc2Nsb3N1cmUiOm51bGx9LCJuYW1lIjoiSW5wdXQgZGVzY3JpcHRvciBmb3IgY3JlZGVudGlhbCAxIiwicHVycG9zZSI6IiIsImZvcm1hdCI6bnVsbH1dLCJuYW1lIjoidGVzdCIsInB1cnBvc2UiOiJibGEiLCJmb3JtYXQiOnsiand0IjpudWxsLCJqd3RfdmMiOm51bGwsImp3dF92cCI6bnVsbCwibGRwIjpudWxsLCJsZHBfdmMiOm51bGwsImxkcF92cCI6eyJwcm9vZl90eXBlIjpbIkVkMjU1MTlTaWduYXR1cmUyMDE4Il19fX0sInN0YXRlIjoiMmMzNTU0MGQtZjNiYy00NTZhLThmNGQtODRlMDEwNzEyNzljIiwibm9uY2UiOiJmaHN2VnlieVRFTXNhTFg1MXZySCIsImNsaWVudF9pZCI6ImRpZDp3ZWI6ZGlkLmFkYXB0aXZlc3BhY2UuaW86bmVtOnNhdHN1bWEiLCJjbGllbnRfbWV0YWRhdGEiOnsiY2xpZW50X25hbWUiOiJTSUNQQSBTYWFTIFZlcmlmaWVyIiwiaWRfdG9rZW5fdHlwZXNfc3VwcG9ydGVkIjpbIlJTMjU2IiwiRVMyNTYiLCJFUzI1NksiLCJFZERTQSJdLCJzdWJqZWN0X3N5bnRheF90eXBlc19zdXBwb3J0ZWQiOlsiZGlkOnNvdiIsImRpZDppbmR5IiwiZGlkOnYxIiwiZGlkOmlvbiIsImRpZDpnYXRjIiwiZGlkOmVic2kiLCJkaWQ6dHoiLCJkaWQ6a2V5IiwiZGlkOnBraCIsImRpZDp3ZWIiLCJkaWQ6ZXRociIsImRpZDpqd2siLCJkaWQ6Y2hlcWQiLCJkaWQ6d2VicyIsImRpZDpkbnMiXSwidnBfZm9ybWF0cyI6eyJsZHBfdnAiOnsicHJvb2ZfdHlwZSI6WyJFRDI1NTE5X1NJR05BVFVSRV8yMDE4Il19fX0sInJlc3BvbnNlX21vZGUiOiJkaXJlY3RfcG9zdCJ9.BVsFZcCQwPAzqiAxSnlcUvshsQYvNZcRJ_wt3boHEbMMNmy4p4_o1GTHPKoQfR2ydFQcCzbmSIYRomwanZISBA

This request is rejected by the wallet at reading (invalid format)

**Comment by ThierryThevenet** [comment]
probably the public key which is not extracted correctly

**Comment by bibash28** [comment]
https://github.com/jonasroussel/dart_jsonwebtoken/issues/55

**Comment by bibash28** [comment]
package maker claims that he/she has solved the issue...
