### ISSUE TITLE
Not able to add Tezos Ownership card

### ISSUE THREAD

**Issue by jeroenbranje** [TalaoDAO/AltMe#2620]
Hi,

In my existing wallets I was missing the Tezos Ownership card.

I'm not able to add this card, it doesn't show up.
![6FD18590-3753-449B-B0AD-B6B0C90F21F1_1_105_c](https://github.com/TalaoDAO/AltMe/assets/15377688/2d0a3b7f-f750-4ba0-a31e-327be17e477b)

The only option is to create or import a new wallet.

**Comment by ThierryThevenet** [comment]
Which build do you have ?

**Comment by jeroenbranje** [comment]
Version 2.4.21 iOS

**Comment by ThierryThevenet** [comment]
you have one account credential already created ?
If yes it is normal as you need to create a new tezos account (up right menu)  to get a new GET card
Or you need to delete the one you have to create anothere one for the same account 
So you can see your account cards for the account selected

**Comment by royscheeren** [comment]
I did a fresh install on a new iPhone 11 v 2.4.21 (441) (never had altme installed on it before)
- imported 4 accounts
- added tz ownership cards
- closed the app
- reopened it
- all 4 tz ownership cards are gone
- cannot add them again

**Comment by ThierryThevenet** [comment]
fixed in beta 2.4.28
