### ISSUE TITLE
Add a Credential card

### ISSUE THREAD

**Issue by jeroenbranje** [TalaoDAO/AltMe#2621]
Hi,

When I try to download and add a credential card in my existing wallet.
I got an error with "This request is not supported".

After a complete reset of the app and use a new wallet i'm able to add the credential card.
I think it's not usual that I need to reset the complete wallet before I can do this.

Before it was working normal, did there something change why this is needed?

Version: 2.4.21 iOS

![DE270871-C4A2-4735-922E-ED1E0E2D921B_1_105_c](https://github.com/TalaoDAO/AltMe/assets/15377688/a5c75920-a93f-4aec-ab4e-225e3bb9345f)
![9290402F-719B-468A-BBC4-6891A8109D5E_1_105_c](https://github.com/TalaoDAO/AltMe/assets/15377688/6c2e8122-6869-4ff3-88ad-dfbef8f5ce34)

**Comment by ThierryThevenet** [comment]
No there was no reason for that reset. Let us know if you still have this issue.
It may happen sometimes that the QRcode reader keep some previous data but usually we only need to close the app and reopen.

**Comment by ThierryThevenet** [comment]
is that ok ? @jeroenbranje
