### ISSUE TITLE
Account renaming issue (minor)

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2623]
Iphone SE
2.4.21

1) Import an account with my seed phrase
2) Edit account Name for Tezos
3) The name changes when i click the arrow and I see the "Select account" menue

Problem: The name is not changed in the standard wallet screen in the top right

4) I close the application (shut down)
5) Start altme
6) Now the name is correctly displayed in the top right

**Comment by ThierryThevenet** [comment]
fixed in 2.9.1
