### ISSUE TITLE
Strange transaction details are shown in Altme

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2626]
I wanted to add a user as a company within our DEMIM project (https://staging.identity.ascs.digital/). 
Screen recording: https://drive.google.com/file/d/1CGCErr1ANR5K1ArZoMvvciajdLZbPDeS/view?usp=sharing

When interacting with the smart contract (https://ghostnet.tzkt.io/KT1Rm2csqyJQXiZXZ8i4A8R2UFZTTPPXqsYN), Altme shows a wrong amount. Notice that it adds the "Amount" and "Estimated gas fee" as well. Also, it does not display the fee (0,000631 ꜩ). This was the successful transaction: https://ghostnet.tzkt.io/ooXSXvtBT3wM8FXBF2kVZBad1FeS75QfM2sxnjvpiW3MGNDANqb/21784013

Altme shows the fee as "Estimated gas fee". 

The first transaction always fails, it works on the second try. I created an additional issue #2627.

**Comment by ThierryThevenet** [comment]
@bibash28 can you tell what you did ?  it is difficult to test
