### ISSUE TITLE
First transaction always fails, second succeeds

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2627]
I wanted to add a user as a company within our DEMIM project (https://staging.identity.ascs.digital/).
Screen recording: https://drive.google.com/file/d/1CGCErr1ANR5K1ArZoMvvciajdLZbPDeS/view?usp=sharing

When interacting with the smart contract (https://ghostnet.tzkt.io/KT1Rm2csqyJQXiZXZ8i4A8R2UFZTTPPXqsYN), the first transaction always fails. The second transaction with a much smaller fee goes trough - https://ghostnet.tzkt.io/ooXSXvtBT3wM8FXBF2kVZBad1FeS75QfM2sxnjvpiW3MGNDANqb/21784013

There you can see the fee on the successful transaction with fee 0.000631 XTZ) (shown in Altme as "Estimated gas fee", which is wrong)
![Bildschirmfoto 2024-04-25 um 16 57 24](https://github.com/TalaoDAO/AltMe/assets/20326784/7cb5819c-b760-4fa4-98bf-4f240984fdf0)

Failed transaction with fee 0.043881 XTZ
![Bildschirmfoto 2024-04-25 um 16 59 33](https://github.com/TalaoDAO/AltMe/assets/20326784/3555fbe3-1c09-4c41-a502-c23fa9eaf269)

It also feels like a double-screen issue... For one transaction, two different screens appear. 

Related to issue #2626

**Comment by ThierryThevenet** [comment]
@bibash28 can you tell me what you did ?

**Comment by hawkbee1** [comment]
@dansan566 Would it be possible to upgrade my account in order to test this?

**Comment by dansan566** [comment]
which account @hawkbee1?

**Comment by hawkbee1** [comment]
After checking my account is not on the staging server.
I created a company account (Altme) on the staging website with tz1PVoUQcgTNnJW9RogBRaupuhcu8Nc2XM8x and I'm now waiting for some Tz from Tezos faucet.
@dansan566

**Comment by dansan566** [comment]
@hawkbee1 send you some tez (https://ghostnet.tzkt.io/oozpcFruQNSR3bj6z5MSVL3NAevddZb7FbTK4pvqhGMdnX4or4r/10488581). However, I can't see the "Altme" company... 

Is it possible to do the following steps again?
1. What type of digital identity do you want to request? -> **Membership identity** 
2. Does an ASCS membership already exists? **Yes**
3. Does an ENVITED research cluster membership already exist? **Yes**
4. For what type of entity do you want to apply? **My company or my institution**
5. Fill out the form and submit / don't forget to sign it within Altme wallet

**Comment by hawkbee1** [comment]
I even have the pdf provided at the end of the process :)
My answers were not the same for membership and Envited.
New subscription done... On **staging** like yesterday. @dansan566
