### ISSUE TITLE
Altme shows "something went wrong, please try again later" and beacon shows "successfully signed payload"

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2659]
System:
Altme Version: 2.5.3 (452)
iPhone 12

Issue: When signing the member credential as a trust anchor, the beacon pop-up shows "successfully signed payload", within Altme "something went wrong, please try again later". 

How to reproduce: It should be the same issue if Altme (approved member) wants to sign a new user credential.

![Bildschirmfoto 2024-05-15 um 14 33 55](https://github.com/TalaoDAO/AltMe/assets/20326784/838f9036-bd41-4044-99b3-e440cbb60d42)

![Bildschirmfoto 2024-05-15 um 14 34 16](https://github.com/TalaoDAO/AltMe/assets/20326784/7893f3c5-acf7-45e0-b2c7-ca0acbc7de0b)

**Comment by dansan566** [comment]
Hey @hawkbee1, any progress on this issue?

**Comment by hawkbee1** [comment]
I'm on vacation until August @dansan566

**Comment by bibash28** [comment]
I think this issue is occurring when the account list does not contain the required Tezos account.. @dansan566

**Comment by dansan566** [comment]
what do you mean by that @bibash28? can you elaborate? why does it work with another wallet?

**Comment by bibash28** [comment]
Can you again test with the latest builds? @dansan566

**Comment by dansan566** [comment]
Used Version 2.10.10 (493)
Both accounts were also revealed (included in the blockchain storage) before and had some tez (ghostnet) on it. 

<img width="378" alt="Bildschirmfoto 2024-08-21 um 09 50 56" src="https://github.com/user-attachments/assets/e1d40825-40a6-4dfb-bc50-c668ebea1ff5">

<img width="1339" alt="Bildschirmfoto 2024-08-21 um 09 51 42" src="https://github.com/user-attachments/assets/a3a5eeef-051c-4adb-9dd2-d16ac0b0d1e2">

Again, Beacon says successfully signed payload, Altme shows an error

**Comment by jdsika** [comment]
@ThierryThevenet high prio

**Comment by ThierryThevenet** [comment]
@hawkbee1

**Comment by hawkbee1** [comment]
@jdsika Currently I can't ask a credential with new account. When https://ascs.digital/redirect is called I get the following error in the browser: 

This site can’t provide a secure connection
ascs.digital uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by jdsika** [comment]
Please wait until the evening - you picked the one day where we redeploy contracts and purge the database :D

**Comment by dansan566** [comment]
@hawkbee1 please use https://staging.identity.ascs.digital/ and create an issuer identity. @ThierryThevenet registered Talao - he can approve you. Once he will try to sign your credential, it will result in this issue

**Comment by hawkbee1** [comment]
I'm not finished with preparing the build but it looks like there is good news for this ticket.

**Comment by jdsika** [comment]
Bravo 👏🏻

**Comment by dansan566** [comment]
@jdsika @hawkbee1 @ThierryThevenet issue still ongoing on 2.16.3 - we will find a workaround for the event but this is still an very important issue.

**Comment by dansan566** [comment]
@jdsika @hawkbee1 @ThierryThevenet thank you! I can confirm it has been fixed. I'm currently using 2.18.2 (555) on my iPhone12
