### ISSUE TITLE
"My identity cards" as well as "My blockchain accounts" dissapear 

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2660]
System:
Altme Version: 2.5.3 (452)
iPhone 12

Issue: After upgrading to 2.5.3, my old accounts were present. However, I noticed that all my cards were gone. First, I clicked on "Add cards", then I chose "Get a proof of crypto account ownership" and clicked on "GET THIS CARD". Under "My blockchain accounts" my "Account ownership" card was shown. I then went off to https://staging.identity.ascs.digital/ to download my user credential. After successfully signing the payload, I clicked on "ADD THIS CARD" and selected my "Account ownership" card. Afterward, my identity cards were gone. 

How to reproduce: Download a user credential (the user must have been approved by the member, i.e. Altme company). 

![Uploading IMG_7473.PNG…]()
![IMG_7474](https://github.com/TalaoDAO/AltMe/assets/20326784/cefaf9de-29c1-4efa-b3d9-f5c2510348a3)
![IMG_7475](https://github.com/TalaoDAO/AltMe/assets/20326784/5e7dd40b-2ee5-445f-8508-7ffca42963e6)

**Comment by dansan566** [comment]
Edit: This also happens when closing and reopening the app!

**Comment by ThierryThevenet** [comment]
yes, we are on it .
