### ISSUE TITLE
Update flutter_secure_storage at next pub.dev update

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#2666]
This update will solve issue on deleteAll, getAll appeared with 9.1.0. A workaround using 9.0.0 is currently used.

**Comment by hawkbee1** [comment]
Package ready for update, we are now able to remove hack from #2663 
https://pub.dev/packages/flutter_secure_storage/versions

**Comment by bibash28** [comment]
Is this still valid?

**Comment by bibash28** [comment]
@hawkbee1
