### ISSUE TITLE
Renaming on the main page becomes effective after closing and reopening Altme

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2667]
Description: I did a complete reset of my Altme wallet. Afterward, I imported a Tezos account with PK and accepted T&C. I renamed the imported account to "DL Ventures" using the down arrow on the top right. The change did not become effective once I returned to the landing screen. However, when clicking the down arrow again, the account was renamed to "DL Ventures". After closing and reopening the app (completely closed it), the account was renamed to "DL Ventures" also on the main screen of Altme. 

Desired Behaviour: It would be great if the change directly becomes visible on the main screen.

**Comment by dansan566** [comment]
This is the main page in my description:
![IMG_0AD02DF5CC81-1](https://github.com/TalaoDAO/AltMe/assets/20326784/7b89a048-7e73-4e92-a045-ace46b3ea218)

**Comment by ThierryThevenet** [comment]
@hawkbee1 can you open a ticket for this ?

**Comment by jdsika** [comment]
Same as #2623 ?

**Comment by ThierryThevenet** [comment]
done in 2.8.3
