### ISSUE TITLE
Desired Behaviour? Redo download external credential without having account ownership card

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2668]
Description: I used an imported account without having the account ownership (Tezos network). The company got approved by the trust anchor. Once the company tried to download the member credential from https://staging.identity.ascs.digital/, I had to add the account ownership card first. So far so good! 
However, afterward, I got redirected to the main page/landing screen again in Altme and had to redo "Download Credential" in my company dashboard. 

Expected Behaviour: It would be nice if I could first add the account ownership credential and directly afterwards my ascs Member Credential without starting the process again. 

Impact: Small

**Shout Out to the Altme Team: The UX from a few months ago has been improved tremoundsly! Please keep up the great work.**

**Comment by ThierryThevenet** [comment]
@hawkbee1 can you add a ticket for that one
