### ISSUE TITLE
Feature Request: Easier way to copy the wallet address from Altme

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2669]
Description: I often want to copy and paste my wallet address from Altme. It always involves a few steps after I can copy it. Here are the steps:

1. Settings
2. Blockchain Settings
3. Manage blockchain accounts
4. "SEE ADDRESS"

another way is

1. Coins
2. Receive
3. Copy

I sometimes used the shortcut to copy the address from the account ownership card but it seems it is not possible anymore. 

My feature request:
Solve it like Phantom Wallet does! One-click on the right top, then add a copy field here:
![IMG_7492](https://github.com/TalaoDAO/AltMe/assets/20326784/3625515b-e9d5-4062-b8c0-6a6ee0c149a2)

Phantom Comparison: 
![IMG_7493](https://github.com/TalaoDAO/AltMe/assets/20326784/cae46763-3ba9-448d-8055-8acab250dff1)

**Comment by ThierryThevenet** [comment]
@HugoNDO can you add a ticket for that feature

**Comment by ThierryThevenet** [comment]
Don" in 2.8.0
