### ISSUE TITLE
Question: Account specific credential view?

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2671]
Question: The Trust Anchor issued a member credential, and the member then issued a user credential. Both are "attached" to their corresponding addresses (Altme asks to which account I want to present the credential if I'm not mistaken). However, shouldn't the corresponding credential on the main page of Altme only be visible to the account owner? 

View of the user:
![IMG_C064027486AD-1](https://github.com/TalaoDAO/AltMe/assets/20326784/d0d5548d-223d-441d-8432-4eea143189ff)

**Comment by ThierryThevenet** [comment]
yes, all credential accounst are displayed currently
we are going to take that into account

**Comment by ThierryThevenet** [comment]
new ticket https://github.com/TalaoDAO/AltMe/issues/2680

**Comment by jtdemer** [comment]
Thx @dansan566 for raising this question, that would defnitly help our users an lead to less conusion by using the  altme to generate a USER and MEMBER Credential via our DEMIM plattform.
