### ISSUE TITLE
Verifier NETCETRA : wallet fails

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2673]
https://verifier-webapp.ssi-open-banking-kyc.test.netcetera.com/simple.

**Comment by ThierryThevenet** [comment]
typ is missing

**Comment by ThierryThevenet** [comment]
format in the input descriptor is not defined

**Comment by ThierryThevenet** [comment]
typ JWT is wrong

**Comment by ThierryThevenet** [comment]
content type is plain/text instead of  "Content-Type": "application/oauth-authz-req+jwt"

**Comment by ThierryThevenet** [comment]
"typ" is missing in kb header `kb+jwt`

**Comment by ThierryThevenet** [comment]
server error 500

**hold**

**Comment by ThierryThevenet** [comment]
Problem on our side with limited disclosure attributes not presented to verifier

**Comment by ThierryThevenet** [comment]
**Test with sandbox OIDC4VP test 12 and test 14**

**Comment by hawkbee1** [comment]
@ThierryThevenet, with dev version 
Test 12 OK
Test 14 KO due du Edward key not handled by jose
![image](https://github.com/TalaoDAO/AltMe/assets/49282360/958abb00-769e-4599-ae3e-9adf9b5b5292)

NETCETRA
issue on subject_syntax_types_supported in client metadata which is absent.
After making it optional we can present the PID with SD-JWT but we are facing the following issue: 
```
I/flutter (15136): 💡 | Response | REQUEST[POST] => PATH: https://dev-integration-ssi-agents.fra.nip-non-prod.cloud.netcetera.com/openid4vp/authresponses
I/flutter (15136): ⛔ | Response | ERROR[500] TYPE[DioExceptionType.badResponse],=> PATH: https://dev-integration-ssi-agents.fra.nip-non-prod.cloud.netcetera.com/openid4vp/authresponses data: {title: Internal Server Error, status: 500, detail: Disclosure with digest UNXkjBBb5QN9XQcV9gTDA6lhW9D2e0m-1wWU-X-1WVQ not found as _sd element}
```

**Comment by hawkbee1** [comment]
PID credential:

eyJhbGciOiJFUzI1NiIsImtpZCI6IlU2TjlBenlWdmpsMWpMQXRSNjRJRVR3V1dVUXpDYjFiQ2xIajItN1UzbkEiLCJ0eXAiOiJ2YytzZC1qd3QifQ.eyJfc2QiOlsiSGN0cVFPamh4c0lYdXNYMVEtS1lHWHdHMzh4d2VaOU41OEt3ajlvSHFXTSIsInlfc09tRlJNVXpsdmc5U1pmT2VTM0k4ekk1bnktWi13YzhKUWRLQWxLLVUiLCJMZmtXZ1NOTjE4Sm0wbUJKbHBQRWhtc2dxUG1SOFBGdDBsZWtPdjNJS3VRIiwiaGgyZEYwRGh1VXF6akZQRlIwT0wwWkM3WHBPMU5ZSE94VjFEcW5BNDRFTSIsInZDOFFkMGpvS0FGalhlU2pzaWs4UUhDdlpuZG5GRlFiRnlPeWp0dUI5VUEiXSwiX3NkX2FsZyI6InNoYS0yNTYiLCJhZGRyZXNzIjp7Il9zZCI6WyJRcWEtbzBvbXNFRDJ0X1NiVHB6cjZ0Tk5pVEU1V2xiZU1sa21hNjZ2cGpJIiwibmJTRHowSEdjNmp0LUxKVUVzc20zOTFPZ3ZSaVl3VkJCZU1SNEM0UHpOQSIsIjE4aFZGdGk0dDFrb0RxX1lLUmFsakxSOUNOaXhobVprckx5VjJROThwTzAiLCI5UUExYWVwc044a0J6bElzZkpuSGxQUVhqbjBlVG1yWUpjV3VrOHQzS19jIl0sImNvdW50cnkiOiJJVCIsInJlZ2lvbiI6IkxhemlvIn0sImFnZV9lcXVhbF9vcl9vdmVyIjp7IjY1IjpmYWxzZSwiX3NkIjpbIjFDWlo3RDdvdl9hVXdBRk96V29lRVhmSHAwMksxREhYc2lDdzRYdWZDS00iLCJkMWpuWFlpU3ZWaFdUZnloUUtoSF9VZndvd0ZabWdUWXRFUk5rbzhFTHhNIiwiUFc0QmJuS255WHJXVmhRdnhVTjlTZjgxNTRVNGROY3hqUzNNUndaUC1kayIsImZlbWZadW04d211SEY1RGtZZFU5d3BJZVY0eEFTcTJ6ak5xVl9IMmtVYTQiLCJBd19sQlU1RWpHRmNNNFNRT3NWV21sOEdYVl9sWUppOVRueWZZVDJIZ2dRIl19LCJjbmYiOnsiandrIjp7ImFsZyI6IkVTMjU2IiwiY3J2IjoiUC0yNTYiLCJrdHkiOiJFQyIsIngiOiJieDdkUC1qUEg2Rzl4ZHA4aUF4RWo0OUlXS2NLd0Y2dTMwckphLTBUcXR3IiwieSI6IjIzN2J3Y0Z0WmNHZWY1ejBTazhHQ3hYb1BZT1hfbHNoNFpPaFBSRFhWUGsifX0sImV4cCI6MTc0ODQ5ODM2MSwiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTcxNjk2MjM2MSwiaXNzIjoiaHR0cHM6Ly90YWxhby5jby9pc3N1ZXIvbnB3c3NoYmxybSIsIm5hdGlvbmFsaXRpZXMiOlt7Ii4uLiI6IjdvT3EtcGMzWmNNT0p4bXdmVkFUZVQzR3YtNnI2aVI1TlI5dFdSTURfZWcifSx7Ii4uLiI6IjhEbEZJRmJ6OWVfWVQwRUFSN0Q0RFR0N090ZlkxQXA5bGpVb2JDZllBMEkifV0sInBsYWNlX29mX2JpcnRoIjp7Il9zZCI6WyJEMmRQejdrQnJvSDFqdnFWc1NUV1N6WU9kam1Ya0R2NDFtZi1IbUdwcFNVIiwiTU1ZTFBlODJLUFg0Skxzal9QTG5DaWVjZzRpa2FyWFhQZUk0X3NDWjlrMCJdLCJjb3VudHJ5IjoiREQifSwic3RhdHVzIjp7InN0YXR1c19saXN0Ijp7ImlkeCI6OTg5NywidXJpIjoiaHR0cHM6Ly90YWxhby5jby9zYW5kYm94L2lzc3Vlci9zdGF0dXNsaXN0LzEifX0sInZjdCI6InVybjpldS5ldXJvcGEuZWMuZXVkaTpwaWQ6MSJ9.H2jFcUoz2pYPuHgTUuiG51v-qm6kwVUYzYxUniYQVpu6LBh68mA-Ybs4adq1FPX1611dkRcMzdC_eTSee5TaBQ~WyIzd2kyWmNPUXlxYUJiZ21tREpLVjR3IiwgImdpdmVuX25hbWUiLCAiUGF0cmljayJd~WyJNNzhkZ1FaS1c2R1MxOUFvR3R6UnZRIiwgImZhbWlseV9uYW1lIiwgIkRvZSJd~WyJOVml0R1k5VGNzQjJfa21QVmU1QndRIiwgImJpcnRoZGF0ZSIsICIyMDAwLTEyLTAxIl0~WyJHaTdudkJCeWlKZHhJeWItbmZnd0pBIiwgImZvcm1hdHRlZCIsICIxMjMgVmlhIEFwcGlhLCBSb21lLCAwMDEwMCBMYXppbywgSXRhbHkiXQ~WyI3Z2ZrNVFmbjlpWlFjZTNfNW1pSGRBIiwgInN0cmVldF9hZGRyZXNzIiwgIjEyMyBWaWEgQXBwaWEiXQ~WyJXaXpKQTQzT0EwQ0VVaTVBZWlsOGF3IiwgImxvY2FsaXR5IiwgIlJvbWUiXQ~WyJiYUJSWG1Jd3BOZG5aYUZ0TUFCYWVnIiwgInBvc3RhbF9jb2RlIiwgIjAwMTAwIl0~WyJJQVE4cXFoU3dYYklwTkFCUHdteC1RIiwgImxvY2FsaXR5IiwgIkxlaXB6aWciXQ~WyI3MXdPMDNDTUdZMVVHcm1qYXJvaEZnIiwgInJlZ2lvbiIsICJTYXhvbnkiXQ~WyJfMklPenFUaEZ0RGs2VlpRY0FxSWFRIiwgIkRFIl0~WyJvNm9VM1E2X2xjSGRUV08yQ2lmVTJBIiwgIklUIl0~WyJ6SVNsQUN2bVNDX19QanZ3U1dyd0Z3IiwgIjEyIiwgdHJ1ZV0~WyJkXzRNVDQzNkhHZjNhOENIRmMwRzJRIiwgIjE0IiwgdHJ1ZV0~WyJqSkRpNGZFLTVuQWUzY2ZIRHA4X09BIiwgIjE2IiwgdHJ1ZV0~WyJNeXVHUUQtblJGZ3RCOUozOFdVTVFBIiwgIjE4IiwgdHJ1ZV0~WyJrY29hVmtVUmd2VGYzdXBzUEg5M2FRIiwgIjIxIiwgdHJ1ZV0~WyIwNEFqQ3pxUWpVUzBGc21jejNCQUJ3IiwgImlzc3VpbmdfY291bnRyeSIsICJERSJd~WyJnSzBCTHM0alNPdFVab2s0WUVFYlhBIiwgImlzc3VpbmdfYXV0aG9yaXR5IiwgIkRFIl0~

**Comment by hawkbee1** [comment]
family name
given name
birthDate
iat
exp
issuing_authority
issuing_country
age_equal_or_over.18 (optional)
address.formatted (optional)
