### ISSUE TITLE
Issuer eidas , wallet fails

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2677]
login and password = johnsmithtester

website https://test.eid.as/
choose test account

**Comment by ThierryThevenet** [comment]
credential offer typo error on their side
**hold**

**Comment by ThierryThevenet** [comment]
login and password = johnsmithtester

website https://test.eid.as/ 
choose test account

**Comment by hawkbee1** [comment]
Just done another test @ThierryThevenet and I get q 413 with message: "Request Entity Too Large"
