### ISSUE TITLE
New translation for Catalan and Spanish

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#2684]
"proofType": "OIDC4VCI Proof Type",
  "proofTypeSubtitle": "Default: jwt\nSelect one of the proof type.",
  "thisWalleIsAlreadyConfigured": "This wallet is already configured",
  "walletSettings": "Wallet Settings",
  "walletSettingsDescription": "Choose your language", "phoneLanguage": "Phone language",
  "pushAuthorizationRequestTitle": "Push Authorization Request (PAR)",
  "pushAuthorizationRequestSubTitle": "Default: false\nEnable to secure the authorization code flow",
  "cardIsValid": "Card is valid",
  "cardIsExpired": "Card is expired",
  "signatureIsInvalid": "Signature is invalid",
  "statusIsInvalid": "Status is invalid",
  "statuslListSignatureFailed": "Status list signature failed",
  "walletMetadataForIssuers": "Wallet metadata for issuers",
  "walletMetadataForVerifiers": "Wallet metadata for verifiers",
  "statusListCachingTitle": "StatusList caching",
  "statusListCachingSubTitle": "Default: On\nSwitch off to reload StatusList when needed",
  "statusList": "Status list",
  "statusListIndex": "Status list index",
  "theWalletIsSuspended": "The wallet is suspended.",
  "clientTypeTitle": "Wallet Client_id Scheme",
  "confidentialClient": "Confidential Client",
  "jwkThumbprintP256Key": "JWK Thumbprint P-256 Key"

**Comment by ThierryThevenet** [comment]
same as previousd, let the information of the OIDC4VC settings in english

**Comment by jotis4ivis** [comment]
ESPAÑOL-SPANISH

"proofType": "Tipo de prueba OIDC4VCI",
"proofTypeSubtitle": "Predeterminado: jwt\nSeleccione uno de los tipos de prueba.",
"thisWalleIsAlreadyConfigured": "Esta cartera digital ya está configurada",
"walletSettings": "Configuración de la cartera digital",
"walletSettingsDescription": "Elige tu idioma", 
"phoneLanguage": "Idioma del teléfono",
"pushAuthorizationRequestTitle": "Solicitud de Autorización Push (PAR)",
"pushAuthorizationRequestSubTitle": "Predeterminado: false\nHabilitar para asegurar el flujo del código de autorización",
"cardIsValid": "La tarjeta es válida",
"cardIsExpired": "La tarjeta ha caducado",
"signatureIsInvalid": "La firma no es válida",
"statusIsInvalid": "El estado no es válido",
"statuslListSignatureFailed": "Error en la firma de la lista de estado",
"walletMetadataForIssuers": "Metadatos de la cartera para emisores",
"walletMetadataForVerifiers": "Metadatos de la cartera para verificadores",
"statusListCachingTitle": "Almacenamiento en memoria caché de la lista de estados",
"statusListCachingSubTitle": "Predeterminado: Activado\nApague para recargar la lista de estados cuando sea necesario",
"statusList": "Lista de estados",
"statusListIndex": "Índice de lista de estados",
"theWalletIsSuspended": "La cartera digital está suspendida.",
"clientTypeTitle": "Esquema Client_id de la cartera digital",
"confidentialClient": "Cliente confidencial",
"jwkThumbprintP256Key": "Huella digital JWK P-256"

CATALÀ-CATALA

"proofType": "Tipus de prova OIDC4VCI",
"proofTypeSubtitle": "Predeterminat: jwt\nSeleccioneu un dels tipus de prova.",
"thisWalleIsAlreadyConfigured": "Aquesta cartera ja està configurada",
"walletSettings": "Configuració de la cartera",
"walletSettingsDescription": "Trieu el vostre idioma",
"phoneLanguage": "Idioma del telèfon",
"pushAuthorizationRequestTitle": "Sol·licitud d'autorització Push (PAR)",
"pushAuthorizationRequestSubTitle": "Predeterminat: false\nHabiliteu per assegurar el flux del codi d'autorització",
"cardIsValid": "La targeta és vàlida",
"cardIsExpired": "La targeta ha caducat",
"signatureIsInvalid": "La signatura no és vàlida",
"statusIsInvalid": "L'estat no és vàlid",
"statuslListSignatureFailed": "Error en la signatura de la llista d'estats",
"walletMetadataForIssuers": "Metadades de la cartera per a emissors",
"walletMetadataForVerifiers": "Metadades de la cartera per a verificadors",
"statusListCachingTitle": "Emmagatzematge en memòria cau de la llista d'estat",
"statusListCachingSubTitle": "Predeterminat: Activat\nApagueu per recarregar la llista d'estats quan sigui necessari",
"statusList": "Llista d'estats",
"statusListIndex": "Índex de la llista d'estats",
"theWalletIsSuspended": "La cartera està suspesa.",
"clientTypeTitle": "Esquema Client_id de la cartera",
"confidentialClient": "Client confidencial",
"jwkThumbprintP256Key": "Empremta digital JWK P-256"
