### ISSUE TITLE
New translation for French

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#2685]
"pushAuthorizationRequestTitle": "Push Authorization Request (PAR)",
  "pushAuthorizationRequestSubTitle": "Default: false\nEnable to secure the authorization code flow",
  "cardIsValid": "Card is valid",
  "cardIsExpired": "Card is expired",
  "signatureIsInvalid": "Signature is invalid",
  "statusIsInvalid": "Status is invalid",
  "statuslListSignatureFailed": "Status list signature failed",
  "walletMetadataForIssuers": "Wallet metadata for issuers",
  "walletMetadataForVerifiers": "Wallet metadata for verifiers",
  "statusListCachingTitle": "StatusList caching",
  "statusListCachingSubTitle": "Default: On\nSwitch off to reload StatusList when needed",
  "statusList": "Status list",
  "statusListIndex": "Status list index",
  "theWalletIsSuspended": "The wallet is suspended.",
  "clientTypeTitle": "Wallet Client_id Scheme",
  "confidentialClient": "Confidential Client",
  "jwkThumbprintP256Key": "JWK Thumbprint P-256 Key"

**Comment by ThierryThevenet** [comment]
same as previous about translation
