### ISSUE TITLE
UX: Credential selection #Minor #Feedback

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2782]
If an application requests a type of credential then the suitable credentials available in my altme app are shown.

Current situation:
I tap on a credential and I can see the selection of the credential through an X in a checkbox.
The order of the credential selection changes randomly.

Expected behavior:
I can select the credential by tapping on the credential and it is selected by highlighting the credential. I don't see a checkbox.
The order of the credentials is e.g. alphabetical by name.

**Comment by ThierryThevenet** [comment]
alphabetical order done in build 2.13.1
