### ISSUE TITLE
Proof of email: Address Not Found error

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2803]
After I enter my email address I receive the verification code.
I enter the verification code and then I am forwarded to talao.co/sandbox/ebsi..... and get the error "Address Not Found"

**Comment by ThierryThevenet** [comment]
@bibash28

**Comment by bibash28** [comment]
No issue on my side:
Added Proof of email from discover..

**Comment by ThierryThevenet** [comment]
@jdsika Do you have more info about the context as it is fine from our side ?
