### ISSUE TITLE
High Priority: System Language incorrectly detected

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2889]
MacOS: 17.6.1
iPhone: Iphone 15 pro max
Altme: v2.10.2
System language: German

Bug:
After the installation the altme application is set to **"Portuguese".**

Expected:
The system language is correclty detected.

![23523_2024-08-20 15_09_35-2024 – OneDrive](https://github.com/user-attachments/assets/9f6a95ba-90e6-4809-a6de-104a70fc1e05)

**Comment by ThierryThevenet** [comment]
@hawkbee1

**Comment by hawkbee1** [comment]
Solved @jdsika 
In next release, when we don't have translation files for the active language, english is the fallback language.

**Comment by jdsika** [comment]
Thanks!
