### ISSUE TITLE
High Priority: Enterprise Wallet description

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2890]
Problem:
The process and the customization options of the **Enterprise Wallet** are not documented. The button redirects to the following webiste that lacks the description: [here](https://wallet-provider.talao.co/)

![grafik](https://github.com/user-attachments/assets/b106e77b-08f8-4a9e-b263-263c8bf50fa5)

Expected:
The features and restrictions and terms are docuemented on the website.

**Comment by ThierryThevenet** [comment]
@HugoNDO

**Comment by ThierryThevenet** [comment]
Doc wallet provider term and conditions

**Comment by HugoNDO** [comment]
Done : New Altme's menu ✅
Next : FAQ will be added on this page : https://wallet-provider.talao.co (working on it) 
Next : Release of the wallet backend terms and conditions

**Comment by HugoNDO** [comment]
New terms and conditions for wallet backend: https://docs.google.com/document/d/1cc-m8VJpLh-BnxZUB98XuTAzBHRD0BPeod5iAfB1ZZY/edit?usp=sharing

**Comment by jdsika** [comment]
I am pretty sure that Section 11. and 12. are impossible for a paid service and can only be applied in combination with e.g. open source code.

**Comment by HugoNDO** [comment]
Here is a new version of the T&C : https://docs.google.com/document/d/1cc-m8VJpLh-BnxZUB98XuTAzBHRD0BPeod5iAfB1ZZY/edit?usp=sharing

**Comment by HugoNDO** [comment]
Here is the page with the new T&C for Talao's wallet backend: https://talao.io/terms-and-conditions-wallet-backend/

**Comment by ThierryThevenet** [comment]
terms and conditions have been improved

https://talao.io/terms-and-conditions-wallet-backend/
