### ISSUE TITLE
Add activity log in screen settings

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2895]
Between About and Reset Wallet add "Activity Log"

when user clic on it display a screen with the all the activities of presenttaion and issuance fo VCs 
It is a sum of all the Activity data of each VCs indeed

**Comment by ArthurMLi** [comment]
I think this will help you.
https://bit.ly/3TyLBMS

you may need to install the c compiler

**Comment by ThierryThevenet** [comment]
@bibash28 first line must be "Wallet installation" with date
if user deletes a VC it must be added
same if backup or Restore
same if key is imported


There will be later a switch to manage the display for enterprise profile.

**Comment by ThierryThevenet** [comment]
in config file

 ```
"settingsMenu": {
        "displayProfile": false,
        "displayDeveloperMode": false,
        "displayHelpCenter": false,
        "displaySelfSovereignIdentity": true,
        "displayActivityLog": true
    },
```
by default display the log if the attribute does not exist in teh cofig file
