### ISSUE TITLE
Get enterprise configuration at smartphone installation (first download from store) without QR code scan

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2899]
When wallet is installed first time and after setup and message "wallet is ready"

Wallet must try to get the configuration in calling GET https://app.altme.io/configuration or GET https://app.talao.co/configuration for Talao wallet. If the configuration exists, data received are the same as the ones of the QR code scan.
example : 
`{'login': 'guest@eudi.talao.co', 'passsword': 'x', 'wallet-provider': 'https://preprod-wallet-provider.talao.co'}`

if configuration exists, download the config file from wallet provider backend and extract the organization name

Then display popup to request consent to user 'Do you consent to install the configuration of <`organization name> `? 

if yes, install the config in the wallet

Then the behavior of the wallet is the same as the config was obtained through a QR code

**Comment by ThierryThevenet** [comment]
This does not replace the QR code scanning method to obtain the config file

**Comment by hawkbee1** [comment]
companyName for install confirmation. Same process with or without qrcode
