### ISSUE TITLE
DEADLINE 4th DECEMBER: tzpro will be deprecated 

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2924]
See this post for information! Switch to tzkt instead:

https://x.com/trilitech/status/1841761946535596204?t=-pfzPZwIoiLHO0uxF6-vUQ&s=19

**Comment by jdsika** [comment]
Alternative: https://x.com/midl_dev/status/1841778430624296999

**Comment by ThierryThevenet** [comment]
We use Tzkt.
