### ISSUE TITLE
Talao wallet does not open when scanning applink on iOS

### ISSUE THREAD

**Issue by ejossev** [TalaoDAO/AltMe#2935]
When scanning QR code with the link (e.g. [https://app.altme.io/app/download/callback](https://app.altme.io/app/download/callback)), the Talao wallet does not open, instead safari opens the page. 
When I installed AltMe wallet, scanning the QR code opened the AltMe wallet, as expected. 

Version: 2.14.0 (both Talao and AltMe).

Anyway, it would be great to have the applinks url & parameters documented (our use case is to initiate the OID4VP from our application).

**Comment by ThierryThevenet** [comment]
NB : if you have found https://app.altme.io/app/download/callback in the wallet client metadata for verifiers, it is an error from our side we will fix it :

correct data are :

```
{
        "wallet_name": "talao_wallet",
        "key_type": "software",
        "user_authentication": "system_biometry",
        "authorization_endpoint": "https://app.altme.io/app/download/authorize",
        "grant_types_supported": [
            "authorization_code",
            "pre-authorized_code"
        ],
        "response_types_supported": [
            "vp_token",
            "id_token"
        ],
        "vp_formats_supported": {
            "jwt_vc_json": {
                "alg_values_supported": [
                    "ES256",
                    "ES256K",
                    "EdDSA"
                ]
            },
            "jwt_vp_json": {
                "alg_values_supported": [
                    "ES256",
                    "ES256K",
                    "EdDSA"
                ]
            },
            "vc+sd-jwt": {
                "alg_values_supported": [
                    "ES256",
                    "ES256K",
                    "EdDSA"
                ]
            },
           "ldp_vp": {
                 "proof_type": [
                     "JsonWebSignature2020",
                     "Ed25519Signature2018",
                     "EcdsaSecp256k1Signature2019",
                     "RsaSignature2018"
                   ]
              },
             "ldp_vc": {
                 "proof_type": [
                    "JsonWebSignature2020",
                     "Ed25519Signature2018",
                     "EcdsaSecp256k1Signature2019",
                     "RsaSignature2018"
                  ]
              }
         },
        "client_id_schemes_supported":[
            "did",
            "redirect_uri",
            "x509_san_dns",
            "verifier_attestation"
        ],
        "request_object_signing_alg_values_supported": [
            "ES256",
            "ES256K"
        ],
        "presentation_definition_uri_supported": True,
        "contacts: [
            "contact@talao.io"
         ]
    }

```

**Comment by ejossev** [comment]
@ThierryThevenet the URL was just an example. Looking at the [entitlements](https://github.com/TalaoDAO/AltMe/blob/TALAO/ios/Runner/Runner.entitlements) and [site association document](https://[app.altme.io/.well-known/apple-app-site-association](https://app.altme.io/.well-known/apple-app-site-association)), any link starting with [](https://app.altme.io/app/download) shall result in opening the application - regardless if it does makes sense or not, shouldn't it?. 
I find issue with using deeplinks with common schemas (like `openid://`), as there is usually conflict on my phone (specifically for `openid://`, it opens MS Authenticator, which I cannot uninstall, `openid-vc://` opens Sphereon, which I also use for testing).

**Comment by ejossev** [comment]
Update: after deleting sphereon, I figured out  `openid-vc://` also opens MS Authenticator.

**Comment by ThierryThevenet** [comment]
@ejossev 
...yes, you can also use haip:// or even siopv2://, openid://   
i dont believe many uses haip://... but in any case the universal link also works.

examples here with different scheme https://talao.co/sandbox/verifier/test_7

**Comment by ThierryThevenet** [comment]
@ThierryThevenet the URL was just an example. Looking at the [entitlements](https://github.com/TalaoDAO/AltMe/blob/TALAO/ios/Runner/Runner.entitlements) and [site association document](https://app.altme.io/.well-known/apple-app-site-association)), any link starting with shall result in opening the application - regardless if it does makes sense or not, shouldn't it?.

Yes because the OS of the device manages the domain name only. The wallet app code then can switch to process differently each call but the OS will start to open the app first.

**Comment by ejossev** [comment]
Good, but it does not for the Talao wallet. 

Btw, I tested with `haip://` schema, that one works, thanks.

**Comment by ThierryThevenet** [comment]
haip:// is attached to this profile https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.html but you dont need to suppor the profile to use the scheme.

**Comment by ThierryThevenet** [comment]
This one has bee defined to support
