### ISSUE TITLE
Name "Etherlink" correctly

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2936]
When creating a new account, I can see the Etherlink logo. However, it is called "Ethereum account". 

Suggestion:

Etherlink account
Create a new Etherlink (EVM) blockchain address

![IMG_7960](https://github.com/user-attachments/assets/02858e82-22ea-4715-9350-f9aa7b05f1e6)

**Comment by ThierryThevenet** [comment]
@bibash28 Regression ?

**Comment by bibash28** [comment]
merge issue...
