### ISSUE TITLE
Wallet cannot process properly escaped characters in the scanned URI

### ISSUE THREAD

**Issue by ejossev** [TalaoDAO/AltMe#2937]
When scanning the QR code with credential offer:

This QR code works:
[openid-credential-offer://?credential_offer_uri=https://openid.pre.vc-dts.sicpa.com/credential-offer/019257b7-da67-79b4-a204-3db874f6430f](openid-credential-offer://?credential_offer_uri=https://openid.pre.vc-dts.sicpa.com/credential-offer/019257b7-da67-79b4-a204-3db874f6430f)
But this one does not:
[openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fopenid.pre.vc-dts.sicpa.com%2Fcredential-offer%2F019257b7-da67-79b4-a204-3db874f6430f](url)

The first one is not properly formed URI (see rfc2396, chapter 2.4 in conjunction with 3.4). Escaping shall be used and the wallet shall process it.

**Comment by hawkbee1** [comment]
@ejossev 
Can you provide first link

**Comment by ejossev** [comment]
Sorry, I've updated it, it seems even the github cannot process malformed URLs as URLs ;)
