### ISSUE TITLE
Why do we have a 404  with the verifier with the build 2.14.0 ?

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2946]
we dont have the issue with the last build

issuer :  https://app-328189308.dev.archipels.io/issuer-catalog/J8yRY7h6kjv9t1ZWCFEf1q

verifier  https://app-328189308.dev.archipels.io/oidc/presentation-request/be121989-2fc1-4419-a2f5-81cf11f0f6c0

**Comment by ThierryThevenet** [comment]
it looks like the bug has been solved but i dont know what was eth issue. it was not the kid of the jwk as this problem has been solved by the verifier alone

**Comment by bibash28** [comment]
Found no issue...
