### ISSUE TITLE
Remove wrong key in OIDC4VC settings

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2953]
there is no new key for EBSI V4

remove did:key EBSI-V4

replace "did:key EBSI-V3" by "did:key EBSI P-256"

![File (9)](https://github.com/user-attachments/assets/0462d3ac-6048-4297-b1d1-8ec227072ac0)

**Comment by ThierryThevenet** [comment]
dont see the change

**Comment by bibash28** [comment]
![Image](https://github.com/user-attachments/assets/6987564d-a366-484a-ba68-25e57bead791)
