### ISSUE TITLE
High Prio: Configutarion fails on android

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2956]
v2.14.1
Google Pixel 7a

I am scanning the QR code. Android asks me to open it with an application: I can chose Firefox or Google (or other browser)

Problem 1)
If I chose Firefox the application is not opened but the link in the QR code is just entered into the search engine

Problem 2)
If I open it with "Google" then Altme opens and asks to load the configuration file.
BUT then the it asks me to verify my fingerprint (as it does this every time it opens) and if verify my fingerprint the "load configuration" vanishes.

Problem 3)
If I try to scan the QR code another time then it tells me that the configuration is already loaded but it isn't and the wallet profile is on "default"

**Comment by hawkbee1** [comment]
Problem 1: By default Firefox doesn't open applications and we can't change this from the app.
To change the Firefox default behavior: https://support.mozilla.org/en-US/kb/set-firefox-android-open-links-native-apps

We are investigating problems 2 and 3

**Comment by hawkbee1** [comment]
We are testing the following change which solve your issue end enforce security: force authentication before handling any universal links or deeplinks.
NB: As a consequence it prevents a user from adding a configuration before creating an account (currently the account creation overwrite a part of the enterprise configuration.

**Comment by ThierryThevenet** [comment]
done in beta 2.15.0
