### ISSUE TITLE
Enterprise Wallet: Wallet configuration not loading

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#2961]
Steps:
* reset wallet
* Do NOT create account yet
* scan QR code 
* Accept configuration
* Import account from seed words
* Now altme is NOT configured

Version: 2.14.1
Android 14
Google Pixel 7a

**Comment by jdsika** [comment]
Scan QR code again -> "profile is already configured"

**Comment by jdsika** [comment]
Feature Request: Ask to override profile when I scan a QR code again

**Comment by jdsika** [comment]
FYI: It does only work if I:
1) reset wallet
2) import wallet
3) scan qr code

**Comment by ThierryThevenet** [comment]
@bibash28 : configuration QR code reading improvement
The configuration QR code reading is improved in case of
- The wallet is already configured, the new configuration is the same as the current one:
>  wallet displays popup to user : 
```
Update configuration
Do you consent to update the configuration of <name>
cancel / continue
```

- The wallet is already configured, the new configuration is different:
>  wallet displays popup to user : 
```
Install new configuration
Do you consent to install  the configuration with <name>
cancel / continue
```

**Comment by ThierryThevenet** [comment]
![IMG_8603](https://github.com/user-attachments/assets/e29212d6-2615-4603-ab58-833c4addc03a)

**Comment by ThierryThevenet** [comment]
in case 3 , popup title is not the good one 

**Install a new configuration**

**Comment by ThierryThevenet** [comment]
done in 2.15.4
