### ISSUE TITLE
Message "This format is not supported" and then "Some issue in the response from the server" when adding a credential

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#2962]
**Description:** 
When downloading a credential from DEMIM, I get the message "This format is not supported"
![IMG_7964 2](https://github.com/user-attachments/assets/5df2c4da-58cd-4cef-b69a-3830cab545ae)

When I click on "MORE DETAILS", I get the following issue
![IMG_7977](https://github.com/user-attachments/assets/50b7461b-f315-40e9-b49c-277a48da34b3)

However, it lets me add the credentials anyway.

**What I would expect:**
- JSON-LD credentials are supported
- When I click on "MORE DETAILS", I get an answer on why it's maybe not supported 

**Version:**
- Version 2.14.5 (525) 
- iOS Version 17.6.1 on a iPhone 12

**Comment by ThierryThevenet** [comment]
To reproduce it, we would need the context issuer ? verifier ? which profile/configuration

json-ld are supported.
