### ISSUE TITLE
Talao backup/restore. Logic change

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2963]
**Only for Talao wallet**

The passphrase in the Talao wallet is useless as credentials must always be restored with the private identity keys.
So we must improve the logic and UX to only use backup an restore logic 

1. update subtitle of "Show wallet recovery phrase". Replace "The recovery phrase acts as a backup key to restore acces to your wallet"  by "This recovery phrase is requested to restore a wallet at installation." . See image 1
2. At installation/reset : replace "IMPORT ACCOUNT" by "RESTORE WALLET" and "CREATE ACCOUNT" by "CREATE WALLET". see image 2

when user clics on RESTORE WALLET, the process must be a Restore of the backup. There is no need to enter and restore the recovery phrase anymore.

**THIS LOGIC IS ONLY NEEDED FOR TALAO WALLET**

be carefull to regression on Altme wallet which must not change.

**Comment by ThierryThevenet** [comment]
image 1
![File (9)](https://github.com/user-attachments/assets/46c8ee19-de8f-4d8a-a758-39d78581481c)

image 2
![File (9)](https://github.com/user-attachments/assets/c646e949-b0d3-469e-8f23-4e70c6c72077)

**Comment by ThierryThevenet** [comment]
dont see the change

**Comment by bibash28** [comment]
this feature is available in talao app only
