### ISSUE TITLE
Manage relative access to the kid in a DID Document 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3028]
It is acceptable to use relative path to provide the `id `of the key (kid)   in a DID Document

**This does not replace the previous way**

exemple of the DID = did:jwk:eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IngzeWZaS251YW0yTzk2SjJpcUhma0ZXMUNPejcxaEQ3bWhMSWIxZmlZVUEiLCJ5IjoiYmpTVE5TMDYxcmZpNnRwU0ZTTmxzSjRPVENnSUdIVU1La2pXWG5FT1FvayJ9

The kid = did:jwk:eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IngzeWZaS251YW0yTzk2SjJpcUhma0ZXMUNPejcxaEQ3bWhMSWIxZmlZVUEiLCJ5IjoiYmpTVE5TMDYxcmZpNnRwU0ZTTmxzSjRPVENnSUdIVU1La2pXWG5FT1FvayJ9#0

k`id = <DID> + # + <identifier>`

and the DID Document is 
```

{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "@vocab": "https://www.iana.org/assignments/jose#"
    }
  ],
  "id": "did:jwk:eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IngzeWZaS251YW0yTzk2SjJpcUhma0ZXMUNPejcxaEQ3bWhMSWIxZmlZVUEiLCJ5IjoiYmpTVE5TMDYxcmZpNnRwU0ZTTmxzSjRPVENnSUdIVU1La2pXWG5FT1FvayJ9",
  "verificationMethod": [
    {
      "id": "#0",
      "type": "JsonWebKey2020",
      "controller": "did:jwk:eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IngzeWZaS251YW0yTzk2SjJpcUhma0ZXMUNPejcxaEQ3bWhMSWIxZmlZVUEiLCJ5IjoiYmpTVE5TMDYxcmZpNnRwU0ZTTmxzSjRPVENnSUdIVU1La2pXWG5FT1FvayJ9",
      "publicKeyJwk": {
        "crv": "P-256",
        "kty": "EC",
        "x": "x3yfZKnuam2O96J2iqHfkFW1COz71hD7mhLIb1fiYUA",
        "y": "bjSTNS061rfi6tpSFSNlsJ4OTCgIGHUMKkjWXnEOQok"
      }
    }
  ]
}

```

We see the `id = #0` of the key is a relative path , the DID is not added before the fragment `# `in the DID Document so the wallet takes into account this option when it resolves the DID

**Comment by ThierryThevenet** [comment]
test with

**Comment by bibash28** [comment]
ok. holderkid identifier whould match the verificationMethod id
