### ISSUE TITLE
Error using authorization code on OIDC4VCI flow

### ISSUE THREAD

**Issue by edutomesco** [TalaoDAO/AltMe#3033]
I'm having this error every time I've issued a credential with the authorization code flow, do you know if the authorization code flow it's working?

Wallet alert: Something went wrong, please try again later.

**Comment by ThierryThevenet** [comment]
yes its works. where is your issuer ?

**Comment by ThierryThevenet** [comment]
@edutomesco hello any more details ?

**Comment by edutomesco** [comment]
I'm using this credential offer request for example:

```json
{
  "credential_issuer": "https://trial.authlete.net",
  "credential_configuration_ids": [
    "IdentityCredential"
  ],
  "grants": {
    "authorization_code": {
      "issuer_state": "Iea0HXXDWjTcizBCY4M-SwHK7m1GiqQFHXIa3zSOqdo"
    }
  }
}
```


```json
openid-credential-offer://?credential_offer=%7B%22credential_issuer%22%3A%22https%3A%2F%2Ftrial.authlete.net%22%2C%22credential_configuration_ids%22%3A%5B%22IdentityCredential%22%5D%2C%22grants%22%3A%7B%22authorization_code%22%3A%7B%22issuer_state%22%3A%22Iea0HXXDWjTcizBCY4M-SwHK7m1GiqQFHXIa3zSOqdo%22%7D%7D%7D
```

The wallet rise an error saying: Something went wrong, please try again later.

**Comment by ThierryThevenet** [comment]
Authlete APIs has a couple of strict requirements. Check what client authentication method they use, and if the redirect_uri must be registered. We did an interop test with Authlete in May this year and it was ok but many options was to configure in particular a client_id value and the redirect_uri was to be registered.

You may also need to access our wallet provider backend if advanced options are required.

Check also this doc :  https://doc.wallet-provider.io/wallet/issuer_configuration#authlete-issuer-integration

**Comment by edutomesco** [comment]
But I would like to know what exactly it's rising the error? Because I don't see the wallet calls any endpoint from the issuer, any .well-known? So what makes the wallet throw the error?

**Comment by ThierryThevenet** [comment]
do you have the qr code ?

**Comment by edutomesco** [comment]
![qrcode](https://github.com/user-attachments/assets/d334e647-4e93-4984-baeb-d26bf96b19e7)

Here!

**Comment by edutomesco** [comment]
![imagen](https://github.com/user-attachments/assets/a0bf8426-6d35-459c-81fe-d3ba757031d4)

Here you have the qr code. And I do not have access to the server console, I'm just using the test guide

**Comment by edutomesco** [comment]
Actually I'm using my own issuer so then I'm issuing the format ldp_vc for the Draft 13, and I already customize the wallet profile, I shared the qr code

![imagen](https://github.com/user-attachments/assets/3f78c2c1-1213-4d58-8218-81f6f911108d)

The problem here is that I don't know when the wallet raise the error, because I do not receive any request on the issuer side, so I'm debugging that!

**Comment by ThierryThevenet** [comment]
No more, Authlete so. 
There is a developer mode option,
the wallet first checks the credential-issuer-configuration and oauth-authorization-server enpoints both data are available in the Display popup in developer mode.

 You will need to setup the wallet in choosing a custom profile and setups the parameters in the OIDC4VC settings menu to get ldp_vc and draft 13
 
for ldp_vc you will need to add @context in the issuer metadata. "vct" is not used for ldp_vc format.

As you have 2 different code flow proposed in the offer, wallet will chose the pre authorized code flow.

Here is an example of an issuer  configuration for ldp_vc with Draft 13 https://talao.co/sandbox/issuer/test_5

**Comment by ThierryThevenet** [comment]
The wallet calls the 2 endpoint and displays the VC for consent. You should see the call at minimum to the credential-issuer configuration. It works on my side as i see the VC displayedl.

in the issuer metadata the wallet will look for the @context and type to build its credential request

Yes there several authorization code flow here https://talao.co/issuer/oidc/test

**Comment by ThierryThevenet** [comment]
we need a fresh qrcode, or the issuer link to do some testing.

**Comment by ThierryThevenet** [comment]
Talao IOS 2.16.3 with safari

**Comment by ThierryThevenet** [comment]
the problem is probably due to a specific client authentication method expected by the oauth server.
In that config the wallet only provides a client_id which is its own DID. So it is a public client. Server should not expect any authentication.

**Comment by ThierryThevenet** [comment]
There are there more issues due to the inherent complexity of the linked data proof format :

1. For privacy issue the wallet does not support remote loading @context, so you have to replace  "https://trustbloc.github.io/context/vc/examples-crude-product-v1.jsonld", by the claims and their definition you need precisely. The other 3 contexts are embedded in the wallet: 

 "https://www.w3.org/2018/credentials/v1",     
  "https://w3id.org/vc-revocation-list-2020/v1",
   "https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json"

and is there is no remote access needed.

2. `$.credential.description` is not in the specs of a W3C VC. You should move it inside the credentialSubject object and add an element in the @context to describe  it ("description" : "https://schema.or/description" )... Same for "`$.credential.name`"

3.  the object :
```
 "issuer": {
        "id": "did:key:zDnaesSAxqHzavZ1R2h1U1QDWPBjULf7CgLccppg4U6Bc2sYA",
        "name": "i_myprofile_cmtr_p256_ldp"
```
     is not supported as the "name" is self declared. So you can replace it by 
      "issuer":  "did:key:zDnaesSAxqHzavZ1R2h1U1QDWPBjULf7CgLccppg4U6Bc2sYA",

**Another option would be to use the format jwt_vc_json which is less complex or even jwt_vc_json-ld**

**Comment by edutomesco** [comment]
Thanks, but about point number 2. I think W3C VC name and description attributes are accepted.
https://www.w3.org/TR/vc-data-model-2.0/#names-and-descriptions

Also it should accept the extended issuer property as indicated: https://www.w3.org/TR/vc-data-model-2.0/#example-expanded-use-of-the-issuer-property

What do you think?

**Comment by ThierryThevenet** [comment]
You are right but the wallet does not VCDM 2.0 for ldp vc and the issuer object The main reason is that we use an external lib which does not support it.

**Comment by edutomesco** [comment]
Sorry, but if the wallet do not accept remote @context what is the alternative? Because at my end I need to control my credential schema with the context json-ld. Is there any way to register this contexts to the wallet?

**Comment by edutomesco** [comment]
Is there any option to make the wallet read from remote contexts then?

**Comment by ThierryThevenet** [comment]
no because te lib we use (didkit) does not accept remote loading. the best option except embedded @context  is to change the format and take jwt_vc_json or jwt_vc_json-ld
