### ISSUE TITLE
DIIP V3 profile must support now all VC formats

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3043]

**Comment by ThierryThevenet** [comment]
@hawkbee1 as there are now several issuers for each VC 
we only display in th Discover of Proffile DIIP V3.0 the emailpass for sd_jwt and and the PID for sd-jwt
PID https://talao.co/id360/oidc4vc?format=vcsd-jwt&draft=13&type=pid
emailpass https://issuer.talao.co/emailpass?draft=13&format=vc_sd_jwt

**Comment by bibash28** [comment]
![Image](https://github.com/user-attachments/assets/a87e1c0a-6acc-4f49-9c74-f9291038c431)
We have three places we are specifically considering based on `vcFormatType == VCFormatType.vcSdJWT`
