### ISSUE TITLE
Bug: Multiple Account Ownership cards

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/AltMe#3061]
# Bug
* As a user I can click on "get a proof of crypto ...  Account Ownership" multiple times and will receive multiple cards

# Expected
* The wallet recogniozes that there is already a card available

**Comment by jdsika** [comment]
IMPORTANT:
If I delete the duplicated account ownership card then it disappears from the overview but I can still select twice the same card when I want to receive and sign a credential.

# Test
* Add Tezos account
* Add 2 times the account ownership card
* Delete one card
* Get DEMIM user credential
* See 2 cards to select from

**Comment by bibash28** [comment]
How to get DEMIM user credential?

After the beacon connection, I get the form. After filling in some data, I get 'Thank you for submitting your request'.

**Comment by jdsika** [comment]
You have the member credential and account. Login with that one and approve your user

**Comment by bibash28** [comment]
okay. thanks.

**Comment by jdsika** [comment]
You do not neet DEMIM for this btw. Just click on the "get account ownership card" field in altme twice

**Comment by bibash28** [comment]
Can you help with the screenshot, @jdsika ? I am bit confused.

**Comment by jdsika** [comment]
# it get's even worse
I now wanted to make a screenshot of the two cards but if I now want to click on "add card" then ALTME thinks I have no tezos account because I deleted the dublicate account ownership card.

I am redirected to the "import account page"

![Screenshot_20241106-075657](https://github.com/user-attachments/assets/8551a173-528b-4369-a7f3-953b53b52430)
![Screenshot_20241106-075703](https://github.com/user-attachments/assets/f38e9b2a-cd0c-41ff-9930-f99bd5763ce3)

**Comment by jdsika** [comment]
Customer in the workshop clicked on the "Discover -> account ownership card" twice and got them twice. 
As described you get multiple cards. Then after deleting the button to add a card does not work anymore and when receiving a credential then the deleted card becomes visible again

**Comment by hawkbee1** [comment]
@hawkbee1 check with @jdsika if that OK with the new way of handling Associated adress caeds
