### ISSUE TITLE
Non regression Test 1 / DIIP V3.0

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3068]
With DIIP V3 profile

1. OIDC4VCI tests 10
2. OIDC4VCI test 8
3. OIDC4VP Test 11
4. OIDC4VP Test 9
5. OIDC4VP Test 10
6. OIDC4VP Test 12

**Comment by ThierryThevenet** [comment]
With DIIPV3

Issuer :
https://ewc.pre.vc-dts.sicpa.com/issuePID 

Verifier
 https://ewc.pre.vc-dts.sicpa.com/

**Comment by bibash28** [comment]
pass
