### ISSUE TITLE
Wallet builds incorrect endpoint path

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3130]
on the server we see GET //issuer/grlvzckofy/.well-known/openid-credential-issuer

//issuer/uwbcbtilws/.well-known/oauth-authorization-server

it shoudl not be "//issuer..." but "/issuer..."

**Comment by bibash28** [comment]
can you give me a specific test? I am not catching the issue in the tests I am testing.. @ThierryThevenet
