### ISSUE TITLE
It looks like we cannot transfer gender (male) and nationalities

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3150]
OIDC4VP test 10

![File (7)](https://github.com/user-attachments/assets/83846dac-df72-44eb-b183-f7867ec56f1c)

**Comment by hawkbee1** [comment]
@ThierryThevenet  Gender is in the payload so that's normal.
Nationality is in the payload but its content is from SD, I'm working on the issue.
