### ISSUE TITLE
Discover Page is empty

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#3152]
Altme version: 2.18.2 (555)
Device: iPhone12

I wanted to add the blockchain network card to my imported account. However, the "Discover" page is empty. Therefore, I can't add any card. I'm not using a profile either (default Altme).

![image](https://github.com/user-attachments/assets/799672c9-2540-4b23-a57d-ea70726f41d9)

**Comment by morarhen97** [comment]
Hello @dansan566 
Thank you for submitting your first issue to this repository! A maintainer will be here shortly to triage and review.
In the meantime, please double-check that you have provided all the necessary information to make this process easy! Any information that can help save additional round trips is useful! We currently aim to give initial feedback within two business days. If this does not happen, feel free to leave a comment.
Please keep an eye on how this issue will be labeled, as labels give an overview of priorities, assignments and additional actions requested by the maintainers:

"Priority" labels will show how urgent this is for the team.
"Status" labels will show if this is ready to be worked on, blocked, or in progress.
"Need" labels will indicate if additional input or analysis is required.

Finally, remember to use the official Decentralized Dapp Protocol to initiate a chat with the support team to get immediate support via [our Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat 💬 icon at the bottom of the page to get started.

**Comment by dansan566** [comment]
As mentioned in #3152, I was able to add the credential with version 2.17.0. All of a sudden, the Discover page is not empty anymore in 2.18.2:

![image](https://github.com/user-attachments/assets/3d31b3cc-8a83-4dc0-8e4c-4230ea5147a1)

**Comment by hawkbee1** [comment]
I deleted comment from @morarhen97 , we don't know this person and the links provided were... suspect at least.

**Comment by hawkbee1** [comment]
@dansan566 AssociatedAddress credentials are now created automatically when accounts are created so you won't see it in discover anymore.
The empty discover screen with default profile is strange, it may be specific to testing version 2.18.2 (555). We will see if this happens again (currently I don't have the issue when creating a new wallet).
