### ISSUE TITLE
Blockchain network (by default) setting gets overwritten

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#3153]
Altme version: 2.18.2 (555)
Device: iPhone12

I changed the network setting to "Tezos Ghostnet". However, after changing account without closing Altme the setting gets overwritten and I will be asked again to change the network to "Tezos Gostnet". I'm not sure yet what exactly causes the overwrite.

**Comment by hawkbee1** [comment]
Are you using an enterprise profile or the default one @dansan566 ?

**Comment by hawkbee1** [comment]
2.18.2  is a beta which has some blocking issues and we will publish a release candidate this afternoon.

**Comment by dansan566** [comment]
@hawkbee1 default

**Comment by ThierryThevenet** [comment]
2.18.5
