### ISSUE TITLE
After approving a user in (staging) DEMIM, it's not possible to download the credential anymore

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#3154]
Altme version: 2.18.2 (555)
Device: iPhone12

I signed up a new user for a company. The user then wanted to download his credential. However, the following issue appeared: 

![image](https://github.com/user-attachments/assets/e3abd5f4-f45e-4c68-b7be-8e5e9c7e11ec)

I then switched back to version 2.17.0 (541) and I got the following workflow: 

![IMG_8136](https://github.com/user-attachments/assets/ec4f3152-5778-4e20-8fca-1aad474433e5)
![IMG_8137](https://github.com/user-attachments/assets/fd7f1633-6fac-4ba9-9aab-ea73a9cd315b)
![IMG_8138](https://github.com/user-attachments/assets/43568949-c619-4ffe-b014-d609cec3f891)
![IMG_8139](https://github.com/user-attachments/assets/dc7bae6d-9bca-400e-8e7b-e24dbb9f61b9)

**Comment by hawkbee1** [comment]
Regression: existing AssociatedAddress credentials for a blockchain were deleted when a new crypto account was created.
Correction will be in 2.18.4 today.
