### ISSUE TITLE
IMPORTED tag not consistent anymore

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#3155]
Version: 2.18.2 (555)
Device: iPhone 12

I noticed that not all of my imported accounts get the "IMPORTED" tag. All accounts in this overview were imported via Private Key into Altme. It is the first time I notice this issue after having hundreds of accounts imported into Altme. It seems to me that this issue have been introduced recently. 

![IMG_8143](https://github.com/user-attachments/assets/ada165e7-5a77-4315-ba18-4aa02fd4621b)

**Comment by hawkbee1** [comment]
@bibash28 Can you investigate this point ?
