### ISSUE TITLE
Two different wallets, two different calculations

### ISSUE THREAD

**Issue by dansan566** [TalaoDAO/AltMe#3156]
Version: 2.18.2 (555)
Device: iPhone12

After successfully presented the credential on https://staging.envited-x.net/, I logged in with my Altme wallet to "mint" an NFT (simulation data, HD Map). There are two major issues:

1. For me as a user, it is totally unclear what operations I execute. In only have the "SEND" button. I actually interact with a smart contract plus doing a reveal operation. Only an advanced users sees that a KT-Account is actually a smart contract.
2. I get another fee calculation same operations in an other wallet. Who is right, who is wrong? 

Altme:
![IMG_8144](https://github.com/user-attachments/assets/52050e1d-cd93-425f-8770-634f10ea2485)

Temple:
![Bildschirmfoto 2024-12-04 um 11 30 28](https://github.com/user-attachments/assets/98e004c3-b337-45b2-976e-596f1b3e1a1f)

**Comment by ThierryThevenet** [comment]
You mean to add the operation id to that screen ? @dansan566 
![Screenshot_20241204-170837](https://github.com/user-attachments/assets/44dc559a-0820-4168-ace3-69c83b0059e2)

**Comment by dansan566** [comment]
No @ThierryThevenet, I'm talking about the screen I posted above. Altme currently only provides a "Send" screen. It also uses the same screen when interacting with a smart contract. It currently interprets it as a transaction from - to. However, I called an entrypoint (mint) in a smart contract.

**Comment by ThierryThevenet** [comment]
@bibash28 fails to buy on objkt.com

**Comment by ThierryThevenet** [comment]
2.18.8

**Comment by hawkbee1** [comment]
you're speaking of https://staging.envited-x.net/ ?
I can't start the process: 

![Image](https://github.com/user-attachments/assets/4810d3e4-51c0-4be1-96fa-b117634e88a7)
