### ISSUE TITLE
Update API Moralis to check if it impacts us on Altme

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3161]
https://docs.moralis.com/changelog/endpoint-deprecations?utm_medium=email&_hsenc=p2ANqtz-_Zalfuy3rcLpqm04hjCfHxNKSRYshzmJRWehNax10AI-xhXKM2T00CDLeA-1KHTB3lv3CY1R-YbjgKZ64YXEtv4qAm1CkUDPZBh_sDcUE3GSRQ2bM&_hsmi=100070018&utm_content=100070018&utm_source=hs_email

**Comment by bibash28** [comment]
does not affect us..
