### ISSUE TITLE
Profile DIIPV3 Discover, GET for Over18 is not correct format

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3173]
it is in ldp_vc, it should sd-jwt

call should be https://issuer.talao.co/ai/over18?vc_format=vc_sd_jwt

**Comment by hawkbee1** [comment]
@bibash28 we have to issues in _getCredentialByAI: 

- vc format is not append to the url used for the call (format_vc=....)
- after the post we consider it's a json but with vc+sd-jwt we get a jwk which cause an error when we try jsonDecode
