### ISSUE TITLE
OIDC4VP request must be checked by wallet before treatment and an error and error_description must be returned to the verifier is any

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#3210]
if there are troubles with the request then the wallet MUST send a POST with error and error description with Content-Type: application/x-www-form-urlencoded ?

error = invalid_request  and add error_description depending on the error case if:
- response_type or client_id or nonce is missing
- redirect_uri and response_uri both in the request at the same time
- if client_id_scheme is not in the list -> did, redirect_uri, verifier_attestation, x509_san_dns 
- presentation_definition and presentation_definition_uri are both in the same request
- if there is an issue with the content of the presentation definition

**Comment by ThierryThevenet** [comment]
does not work with client_id_scheme not in the list

**Comment by ThierryThevenet** [comment]
does not work when nonce is missing, user message is displayed but server does not receive the POST

**Comment by ThierryThevenet** [comment]
**for all those erre cases:
- wallet user must see a an error message (popup)
- verifier must received a POST with error and error description (same as for user)**

**Comment by bibash28** [comment]
this is already done..

**Comment by ThierryThevenet** [comment]
it does not test the 

if client_id_scheme is not in the list -> did, redirect_uri, verifier_attestation, x509_san_dns

@bibash28

**Comment by ThierryThevenet** [comment]
if there are troubles with the request then the wallet MUST send a POST with error and error description with Content-Type: application/x-www-form-urlencoded ?

error = invalid_request and add error_description depending on the error case if:

    response_type or client_id or nonce is missing
    redirect_uri and response_uri both in the request at the same time
    if client_id_scheme is not in the list -> did, redirect_uri, verifier_attestation, x509_san_dns
    presentation_definition and presentation_definition_uri are both in the same request
    if there is an issue with the content of the presentation definition
