### ISSUE TITLE
New card :  Tezotopia memberShip card

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#331]
New credential type
Wainting for design and json-ld specs

**Comment by ThierryThevenet** [comment]
associated to MembershipCard_1

**Comment by hawkbee1** [comment]
@HugoNDO is it the expected design


![Image](https://user-images.githubusercontent.com/49282360/186359653-d40020af-cb76-45c7-a878-88cd1d3a77f4.png)
