### ISSUE TITLE
Keep the  date of presentation for each credential

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#413]
Those dates will be displayed in the detail of the credential screen

**Comment by bibash28** [comment]
Is this already addressed? @ThierryThevenet @hawkbee1

**Comment by hawkbee1** [comment]
@bibash28 I don't see how it could be already done.
@ThierryThevenet we are tracking only the last presentation done with each credential or all presentation history ?

**Comment by bibash28** [comment]
i thought this is handled by backend..

**Comment by bibash28** [comment]
We need more details then...

**Comment by hawkbee1** [comment]
For each credential we will store store acquisition date and every presentation date of the credential. This data will be displayed in credential detail screen, in the activity section.

**Comment by hawkbee1** [comment]
acquisition date is when we accept the credential. As an exemple I have the preview of a compelio ticket credential offer... The moment (now) I "ADD THIS CARD" is the datetime to store for the credential acquisition date.
