### ISSUE TITLE
New card :  Diploma card

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#433]

**Comment by hawkbee1** [comment]
New diploma card in Figma


![Image](https://user-images.githubusercontent.com/49282360/186358439-c06b9861-3e42-4e34-9e7b-49fbd870ecff.png)

**Comment by hawkbee1** [comment]
Size: S

**Comment by bibash28** [comment]
@hawkbee1 design not available in figma
