### ISSUE TITLE
link to analytics of voucher

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#458]

**Comment by ThierryThevenet** [comment]
see issue 479 first as the link, will be one of the credential attribute

**Comment by bibash28** [comment]
Can you explain more  @ThierryThevenet @hawkbee1 ???

**Comment by hawkbee1** [comment]
As far as I understand there is now a link in the voucher credential and we should display this link.  Apparently, @bibash28 , you've already done such link presentation when dealing with ticket #479
