### ISSUE TITLE
beacon integration

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#484]

**Comment by hawkbee1** [comment]
https://docs.walletbeacon.io/getting-started/first-dapp/

**Comment by hawkbee1** [comment]
@TalebRafiepour @bibash28 let's create new tickets for beacon based on the documentation.
I added the "beacon" label to regroup those tickets

**Comment by bibash28** [comment]
add to beacon dApp list

https://github.com/airgap-it/beacon-docs
https://docs.walletbeacon.io/dapps/

**Comment by bibash28** [comment]
Beacon android and ios SDK
https://github.com/airgap-it/beacon-android-sdk
https://github.com/airgap-it/beacon-ios-sdk

**Comment by bibash28** [comment]
Node js backend sdk
https://github.com/airgap-it/beacon-sdk

**Comment by bibash28** [comment]
TypeScript  Library for build dApps on the Tezos

https://tezostaquito.io/
https://github.com/ecadlabs/taquito

**Comment by bibash28** [comment]
Article explaining beacon flow
https://medium.com/airgap-it/beacon-connect-tezos-wallets-with-dapps-2edb0fa3ee4a

**Comment by bibash28** [comment]
Possible Beacon Features
- Scan QR code from the browser application directly with the mobile application to establish the connection
- Beacon browser extension with multiple possible signing methods

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/184830339-86ffc999-243f-4a8b-8c4d-3f3cdbb8687b.png)

**Comment by bibash28** [comment]
https://www.youtube.com/watch?v=OHJojBS9awA

![Image](https://user-images.githubusercontent.com/18188709/185539663-f80c33f5-8845-447c-83a8-8cc8c0d17599.png)


![Image](https://user-images.githubusercontent.com/18188709/185539709-954b925f-8f97-461d-bfcf-4921ce2fbf2a.png)

**Comment by bibash28** [comment]
https://medium.com/airgap-it/airgap-the-step-by-step-guide-c4c3d3fe9a05
