### ISSUE TITLE
New card : Talao community card

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#486]

**Comment by bibash28** [comment]
Can you provide the card design for the community card?? @ThierryThevenet @hawkbee1

**Comment by hawkbee1** [comment]
You can find the community card in Figma ( https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=3%3A1533 ) in the credentials/cards section. We will use the purple one. Here is a screenshot.
![image](https://user-images.githubusercontent.com/49282360/182153003-9ab0a8f4-5e2c-479e-a53f-dd6321dad406.png)
