### ISSUE TITLE
New Discover Screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#488]
Following is deprecated:
Must link to  a browser screen  inside the app to display a responsive web site.
the URL will be by default https://altme.io/discover but one can change it manually in the input field of the browser.

**Comment by hawkbee1** [comment]
Change: discover inside the app now.

**Comment by hawkbee1** [comment]
"Get it" are removed from credential list.
"Get it" cards is the content of discover screen with same design as credential list.

**Comment by TalebRafiepour** [comment]
The discovered link (https://altme.io/discover) returns 404 now!
