### ISSUE TITLE
Credential detail 

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#514]
text color of activity, information and description is white. We are not using text color from credential manifest in this part.
![image](https://user-images.githubusercontent.com/49282360/182181494-40a2d6d7-61ee-43e6-8d50-55e673e919e1.png)

**Comment by bibash28** [comment]
We are not using color from the credential manifest on this screen...

Can you give me more details?? @hawkbee1 @ThierryThevenet
