### ISSUE TITLE
credential manifest, type "number" 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#524]
cannot manage number (not string) in credential manifest output descriptors "type"

https://json-schema.org/understanding-json-schema/reference/numeric.html

**Comment by ThierryThevenet** [comment]
test on sandbox
http://192.168.43.67:3000/sandbox/direct_offer?VC=VerifiableDiploma.jsonld

**Comment by ThierryThevenet** [comment]
{
                        "path": [
                            "$.credentialSubject.learningSpecification.ectsCreditPoints"
                        ],
                        "schema": {
                            "type": "number"
                        },
                        "fallback": "Unknown",
                        "label": "ECTS Points"
                    },

**Comment by hawkbee1** [comment]
added boolean and integer tho the scope of this ticket
