### ISSUE TITLE
Ramp payment solution

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#531]
[@romuald barbe](https://talao.slack.com/team/U0252HM1VGB)
 salut.pas de nouvelles de moinpay. L autre solution c est ramp avec spe pay. Ils ont un sdk qui integre celui de passbase   . Je les si contacté il n y a pas moyen d utiliser notre kyc. Il faudra refaire un kyc oassbase pour acheter des cryptos. On ajouter ce ticket https://docs.ramp.network//
docs.ramp.networkdocs.ramp.network
[Welcome to Ramp Docs! | Ramp Docs](https://docs.ramp.network//)
Here's all you need to know before integrating Ramp into your dApp or wallet.

**Comment by hawkbee1** [comment]
@hawkbee1 Ask ramp API key again

**Comment by bibash28** [comment]
https://share.hsforms.com/1TKWT1ksNQZ6AURRV0ssvqg5awa0

**Comment by bibash28** [comment]
https://github.com/TalaoDAO/AltMe/tree/ramp-setup
