### ISSUE TITLE
Associate the Diploma card to type LearningAchievement and VerifiableDiploma

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#532]

**Comment by hawkbee1** [comment]
Use this card for both of them


![Image](https://user-images.githubusercontent.com/49282360/186358957-bdb689f8-dd6f-43ec-af59-2bcdcdf6ed0f.png)

**Comment by hawkbee1** [comment]
https://github.com/TalaoDAO/AltMe/issues/433
