### ISSUE TITLE
As a user I want to add the ethereum private key of my Talao account in the wallet

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#536]
Add menu in drawer to add this Ethereum private key.
Just Store the Ethereum private key in secure storage for now... later it will probably be additional account on Ethereum network.

@HugoNDO may we have a text for this importation screen?
@HugoNDO In the menu should we use a specific existing icon

**Comment by HugoNDO** [comment]
Répondu dans le channel marketing ✅

**Comment by hawkbee1** [comment]
smal part of this ticket: https://github.com/TalaoDAO/AltMe/issues/584

**Comment by hawkbee1** [comment]
everything is in #584
