### ISSUE TITLE
Replace in home screen "NFTs" by "Gallery"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#542]
and remove this screen with the text NFT when there is no NFT.
One can change the text see @HugoNDO go
![Screenshot_20220811-081416](https://user-images.githubusercontent.com/32768069/184074734-c3fff592-4fff-432f-a8c8-9cb59a444fe2.jpg)

**Comment by HugoNDO** [comment]
Replace "No NFT provided with your account!" by : "Your digital gallery is empty !"
