### ISSUE TITLE
create testable backend

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/AltMe#556]

**Comment by bibash28** [comment]
Node js backend sdk
https://github.com/airgap-it/beacon-sdk

TypeScript Library for build dApps on the Tezos

https://tezostaquito.io/
https://github.com/ecadlabs/taquito

**Comment by hawkbee1** [comment]
Asking @ThierryThevenet for existing sandbox dapp and produciton to ease dev

**Comment by bibash28** [comment]
https://www.walletbeacon.io/

**Comment by bibash28** [comment]
https://www.walletbeacon.io/
