### ISSUE TITLE
Talao community card part 2

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#584]
1) from the ethereum private key calculate the Ethereum address (see TALAO smart_contract.dart) All private keys must be stored in secure storage (same for Tezos private keys and passphrase)
2) calculate the TALAO token number. see code as exemple how to get ethereum token smart contract token balance (TALAO_smart_contract.dart) see Thierry
3) if TALAO token balance is less than 500 display message (see figma) "Sorry you have any TALAO token...." or Sorry you need more than 500 TALAO token...). If token balance is > 500 display "Well done !...."
Figma screen https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=1763%3A10428
if more than 500 
4) calculate the JWK key for the ethereum private key (see code example ethereum_2_jwk.dart) Thierry
5) issue with didkit the credential :  https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/TalaoAssociatedAddress.jsonld with same proncipal as TezosAssociatedAddres : the issuer DID is the owner of the ethereum address and the credentialSubjectId is the wallet DID
6) at  the end of the process the wallet gives the link to get the Talao Community Card : https://issuer.talao.co/tc

**Comment by ThierryThevenet** [comment]
you will also need teh ABI.json of the TALAO smart contract
Everything here is linked to Ethereum blockchain only

**Comment by ThierryThevenet** [comment]
Ethereum address start with 0x (Hex encoded)
Usually ethereum private key starts with 0x as it is also Hex enconded but some times they dont display 0x (Metamask)

**Comment by hawkbee1** [comment]
screenshot from the design in Figma. The text "Sorry, you don't have any Talao..." is in fact "Sorry you need more than 500 TALAO token in this account!"
![image](https://user-images.githubusercontent.com/49282360/186383099-5ab78e1b-9e51-4881-94e6-5f99b486966a.png)

**Comment by ThierryThevenet** [comment]
probbaly useless
