### ISSUE TITLE
When beacon package is done, add wallet Altme  to beacon list

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#599]
[@romuald barbe](https://talao.slack.com/team/U0252HM1VGB)
 il faudra penser a faire refetencer la package Dart beacon sur le site des développeurs de Beacon. C est une equipe tres connue de l ecosysteme Tezos. Il faut avoir de bonnes relations avec eux. Ensuite il faudra referencer le wallet sur leur site . C est un pount d entree pour que le wallet soir integré ensuite sur tous les jeux Tezos 
[@Hugo MIR](https://talao.slack.com/team/U03JXRA763Z)

**Comment by bibash28** [comment]
To add your altme wallet to the list, you can create a pull request and add it to this array:
https://github.com/airgap-it/beacon-sdk/blob/master/scripts/blockchains/tezos.ts#L84
[tezos.ts](https://github.com/airgap-it/beacon-sdk/blob/master/scripts/blockchains/tezos.ts)

@hawkbee1

**Comment by bibash28** [comment]
Where to add beacon package?? @hawkbee1
