### ISSUE TITLE
red message on crypto when we reload the token screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#603]
![Screenshot_20220825-132948](https://user-images.githubusercontent.com/32768069/186654321-da5b88ff-9480-48f3-a395-615a1808700c.jpg)

**Comment by hawkbee1** [comment]
When testing on iphone I had this error message a lot. 
Apparently it happened in two occasions:
- when downloading some pictures (maybe token picture, not sure) url of the download is empty,
- When updating contracts: see following picture  
![image](https://user-images.githubusercontent.com/49282360/186884203-b5181c64-18be-4846-af95-9e8ccf949314.png)
