### ISSUE TITLE
check if mobile scanner works with passbase and implement...

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/AltMe#608]

**Comment by hawkbee1** [comment]
currently need to use github version

**Comment by bibash28** [comment]
https://pub.dev/packages/mobile_scanner/versions/3.0.0-beta.1

beta version is released... @hawkbee1

**Comment by hawkbee1** [comment]
M

**Comment by bibash28** [comment]
https://github.com/juliansteenbakker/mobile_scanner/issues/314

**Comment by bibash28** [comment]
https://github.com/juliansteenbakker/mobile_scanner/issues/314
