### ISSUE TITLE
token list (add token list)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#620]
at initalisation display all tokens user have + a list of tokens.
Token list: see next posts

**Comment by nicolasmullertalao** [comment]
Tezotopia tokens: UNO, ENR, MCH, MIN, GIF

**Comment by HugoNDO** [comment]
Dogami (DOGA)
Kolibri DAO (KDAO)
Wrapped BUSD (WBUSD)

**Comment by ThierryThevenet** [comment]
QUIPU
