### ISSUE TITLE
Get multiple credentials at once after KYC

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#626]

**Comment by hawkbee1** [comment]
Doing a loop in cubit with list of url to get credentials.

**Comment by hawkbee1** [comment]
@HugoNDO should we warn the user with a popup before getting all the credentials? Could you get text or design for this popup?

**Comment by ThierryThevenet** [comment]
I have found an openiD protocol for VC which can do that. I am working on  it.

**Comment by hawkbee1** [comment]
https://docs.google.com/document/d/1joRv1p-bpTAJBonj096yax5rEYRhYD4-yX5yuqsqEYQ/edit#heading=h.c9s2xorc1ezg

**Comment by hawkbee1** [comment]
on récupère tout
