### ISSUE TITLE
new design of membership card Tezotopia

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#629]

**Comment by hawkbee1** [comment]
![Image](https://user-images.githubusercontent.com/49282360/189063900-db50628e-3d4c-45fe-ab95-326ce14b7b9f.png)

**Comment by hawkbee1** [comment]
![Image](https://user-images.githubusercontent.com/49282360/189064098-2e0680aa-7d71-4769-9e17-5c344b53f7ea.png)

**Comment by hawkbee1** [comment]
S Size

**Comment by TalebRafiepour** [comment]
![Image](https://user-images.githubusercontent.com/40627325/190181866-05c8431c-81a1-49bc-aaad-c2539f5d6a45.png)

**Comment by TalebRafiepour** [comment]
@hawkbee1 both the Membership card and TezotopiaVoucher card have the same get_it card design?

**Comment by hawkbee1** [comment]
nope 
![image](https://user-images.githubusercontent.com/49282360/190183581-c5186cd1-c02b-47e3-bd5c-0056479fd264.png)
