### ISSUE TITLE
Add referrals in discover

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#632]
Cometh: https://docs.cometh.io/polygon-galactic-grand-prix-1/referral-program-1
Sorare: 

When user press the discover card we:
- add a self issued referal card with type specific of the referral program.
- the self issued is added to wallet in gaming section
- The link of the referal is opened in phone browser

**Comment by hawkbee1** [comment]
@ThierryThevenet we need to define the jsonLD of the self issued

**Comment by hawkbee1** [comment]
@nicolasmullertalao We need the referrals link to use in the app.

**Comment by hawkbee1** [comment]
![Image](https://user-images.githubusercontent.com/49282360/189067192-737467ce-946e-4d34-8fa7-590254362ecb.png)

**Comment by hawkbee1** [comment]
XL size

**Comment by hawkbee1** [comment]
sandbox link: https://www.sandbox.game/en/login/?r=iTpRlmGR5o7jn8BxhVYrq
sorare: https://sorare.com/r/altme2022

Cometh is removed from project

**Comment by hawkbee1** [comment]
Don't shw it on iphone

**Comment by hawkbee1** [comment]
@HugoNDO : we need description text for the self issued card
@ThierryThevenet we should add a link property in self issued credential manifest, right ?

**Comment by HugoNDO** [comment]
Abandon de la carte SANDBOX (le referral n'existe plus). 

Pour la carte SORARE, voici le texte à mettre : "By connecting to Sorare with the referral Altme link, once you have collected 5 Limited cards you will win 2 Limited cards!"

**Comment by HugoNDO** [comment]
For Sorare referral card, here is the content : 

1) Description : By connecting to Sorare with the referral Altme link, once you have collected 5 Limited cards you will win 2 Limited cards!

2) Expiration date: This card will remain active as soon as long as the Sorare referral program is active.

3) How to get it: You just have to click on the card and agree to add it to your Altme wallet.

**Comment by HugoNDO** [comment]
Sandbox referral program is over so this credential is abandoned. You can close the ticket after integrating Sorare.
