### ISSUE TITLE
Add design of a new card  of type "EthereumAssociatedAddress"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#639]

**Comment by ThierryThevenet** [comment]
we need it for  a demo on Thursday 3rd Nov

**Comment by hawkbee1** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
My side it does not work, grey screen 


![Image](https://user-images.githubusercontent.com/32768069/199559635-6a13b8b4-d998-4d79-9bdf-53db781be174.jpg)
