### ISSUE TITLE
New issuer for new cards

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#644]
new issuers available :  Nationality card, Age Range card  and gender card:
https://issuer.talao.co/nationality
https://issuer.talao.co/gender
https://issuer.talao.co/agerange

types : Nationality, Gender, AgeRange

**Comment by hawkbee1** [comment]
Added the links in tickets of each cards.
gender card[#627](https://github.com/TalaoDAO/AltMe/issues/627)
card age range[#624](https://github.com/TalaoDAO/AltMe/issues/624)
nationality card[#625](https://github.com/TalaoDAO/AltMe/issues/625)
