### ISSUE TITLE
Fix transaction history for "fa2" standards tokens

### ISSUE THREAD

**Issue by TalebRafiepour** [TalaoDAO/AltMe#654]
The JSON of transactions history which is returned for a "fa2" token has a different object than normal JSONs for other Transactions JSON. 
I should update JSON casting for "fa2" tokens to get all history in app correctly.

**Comment by ThierryThevenet** [comment]
still problem with Lugh Euro for instance

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  The pull request for this issue merged today. I think you should wait for the new build because I did it.
