### ISSUE TITLE
dont see the first transfer of crypto

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#655]

**Comment by ThierryThevenet** [comment]
Dont see the first trasfer oc CRUNCH

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  I did it; please wait for the new build today!

**Comment by TalebRafiepour** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-05 at 12 18 45](https://user-images.githubusercontent.com/40627325/188396635-dda105d4-7f36-4d0d-b940-d56f99d8624d.png)

@ThierryThevenet
