### ISSUE TITLE
Beacon: design of beacon wallet screens

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#662]
Beacon screens from other wallets.

![IMG_0212](https://user-images.githubusercontent.com/49282360/188561127-633f4444-6c9c-406d-abaf-d98369ef352d.PNG)
![IMG_0222](https://user-images.githubusercontent.com/49282360/188561131-8b3ced18-c58c-4585-bb5f-0b49ecc36168.PNG)
![IMG_0221](https://user-images.githubusercontent.com/49282360/188561132-b9fbf7ef-974a-4d0f-8480-39d4e7566f58.PNG)
![IMG_0211](https://user-images.githubusercontent.com/49282360/188561136-d464b82b-0244-45c8-a338-d5180e0924eb.jpg)
![IMG_0210](https://user-images.githubusercontent.com/49282360/188561143-56135df9-cedd-4f1e-9b8e-19c68d20e2d1.jpg)
![IMG_0220](https://user-images.githubusercontent.com/49282360/188561149-91d22c32-615e-4e5e-9d66-a64eb87db364.PNG)
![IMG_0209](https://user-images.githubusercontent.com/49282360/188561150-eaf4079e-62bb-4acd-ab06-29d84d30434e.jpg)

**Comment by Klannka** [comment]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2351%3A10620

**Comment by hawkbee1** [comment]
etape 2
![image](https://user-images.githubusercontent.com/49282360/189128137-4f4dc0fe-4f64-4b02-92d9-2d4bb02676d0.png)

**Comment by hawkbee1** [comment]
When pressing scan button
![image](https://user-images.githubusercontent.com/49282360/189128944-e6926377-7a42-4a21-a027-c3a4533571f2.png)

**Comment by hawkbee1** [comment]
See Dapp permissions
![image](https://user-images.githubusercontent.com/49282360/189130081-3e20fdd2-5d21-428d-8ab9-e765821a7bba.png)

**Comment by hawkbee1** [comment]
Bouton disconnect
![image](https://user-images.githubusercontent.com/49282360/189130362-c8bc3d92-4865-4717-9ec6-f1de71147236.png)

**Comment by hawkbee1** [comment]
En voie 1 Tz à dsoijsoidfj §?

Sur la dapp de test: 
![image](https://user-images.githubusercontent.com/49282360/189135525-b5569d2d-e749-4ee2-93d7-51d8c7ef0530.png)

Sur le wallet:
![image](https://user-images.githubusercontent.com/49282360/189135663-fd30e8a1-4ade-4c65-b632-f2881ba229b7.png)

**Comment by hawkbee1** [comment]
![image](https://user-images.githubusercontent.com/49282360/189136944-53afe88c-5aef-49bf-b147-fb68b3f69669.png)

*************************

![image](https://user-images.githubusercontent.com/49282360/189137045-e248e082-5a3d-4b8a-8a5b-c3ff82ecce7a.png)

**Comment by Klannka** [comment]
Design screens for Beacon : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2643%3A8715
