### ISSUE TITLE
QueryByExemple: Allow selection and presentation of multiple credentials

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#671]
Same thing as we've already done for credential manifest: https://github.com/TalaoDAO/AltMe/issues/553

**Comment by hawkbee1** [comment]
Size: M

**Comment by ThierryThevenet** [comment]
still proble, teh server receives only 1 credential
the resposne should be a json in 1 credetial and a set of json if multiple credentials (as previously)
