### ISSUE TITLE
tokens not shoving on first account (test wallet on mainnet)

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#694]
![image](https://user-images.githubusercontent.com/49282360/190334922-ca2fbdd3-6c39-4d96-a726-2778e1c27eb1.png)

**Comment by TalebRafiepour** [comment]
@hawkbee1  fixed

**Comment by ThierryThevenet** [comment]
still same issue on build60

**Comment by TalebRafiepour** [comment]
on iOS build 56 it's working for me. I will check it twice

**Comment by hawkbee1** [comment]
![image](https://user-images.githubusercontent.com/49282360/190574585-2b7bef12-7fb3-49f9-9278-68463caebb1a.png)

**Comment by ThierryThevenet** [comment]
see new issue
