### ISSUE TITLE
check network validity while performing with beacon

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/AltMe#706]

**Comment by hawkbee1** [comment]
Check connectivity also in lib/app/shared/dio_client/dio_client.dart for GET and POST
+ beacon when pressing button

**Comment by hawkbee1** [comment]
Size: M

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/197812190-36b9d9e8-7d5a-42a7-9b42-627c2bc00c09.png)
