### ISSUE TITLE
disconnect with beacon if crypto account does not exist

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/AltMe#707]

**Comment by hawkbee1** [comment]
@bibash28 is checking the API to see if beacon is now sending the correct list of dApp connections.

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/197820737-ce2344c9-a3c8-4d53-93fa-ee5cf9107a43.png)

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/197934346-7a57ba8e-6c19-4b75-a940-6ec856e0315a.png)

**Comment by bibash28** [comment]
Size: L

**Comment by hawkbee1** [comment]
can't delete account
