### ISSUE TITLE
Pagination issue  - Dont see the Tezotopia NFT which has been bought in the wallet

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#740]
https://tzkt.io/oojjADNbqmQqTSqvuv6jmLwSHVri4yCQPmzvuBmHmxouBuVkAbg/77145256/25

**Comment by ThierryThevenet** [comment]
update of the cache ?

**Comment by bibash28** [comment]
If we have a total of 22 NFTs...

Test 1: limit = 10
1. First-page loading -> NFT displayed - 10
2. Scroll down -> Show Loading -> NFT displayed - 20 
3. Scroll down -> Show Loading -> NFT displayed - 20        (Bug)

Test 2: limit = 10
1. First-page loading -> NFT displayed - 10
2. Pull to refresh -> NFT displayed - 10
3. Pull to refresh -> Show Loading -> NFT displayed - 10     (Bug)

Test 3: limit = 2 (Case when the screen size is large)
1. First-page loading -> NFT displayed - 2
2. Scroll down -> Show Loading -> Nothing happens            (Bug)  if more space is left then offset should be increased and API should be called

Test 4: limit = 2 (Case when the screen size is large)
1. First-page loading -> NFT displayed - 2 
2. Pull to refresh -> Nothing happens                                      (Bug) -  I cannot pull to refresh
