### ISSUE TITLE
Beacon : App Crashes on rarible when buying a NFT 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#769]

**Comment by ThierryThevenet** [comment]
https://rarible.com/token/tezos/KT18pVpRXKPY2c4U2yFEGSH3ZnhB2kL8kwXS:80609?tab=overview

**Comment by ThierryThevenet** [comment]
![File(2)](https://user-images.githubusercontent.com/32768069/192595310-bbf459f2-8c59-4217-bd34-ab96c2810756.jpg)

**Comment by ThierryThevenet** [comment]
![Capture d’écran de 2022-09-27 19-26-33](https://user-images.githubusercontent.com/32768069/192595452-8588bdcc-2f66-4960-9163-39d755545186.png)

**Comment by ThierryThevenet** [comment]
App does not crash but Beacon does not work on rarible to buy

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/193749769-8a919a81-0f9a-4198-9f02-48bb4551d44d.png)

https://github.com/bitmark-inc/autonomy-client/issues/329

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/193767226-8920bebc-1e48-4bad-8339-91a03f74daee.png)

**Comment by bibash28** [comment]
Solution from autonomy:

https://github.com/autonomy-system/beacon-android-sdk/commit/5b0245187d66c8d82f5c3201a9326f15bbb8a9b1
https://github.com/bitmark-inc/autonomy-client/commit/f8071f86537eee798bb6e4c172ac669d591aa838
