### ISSUE TITLE
NFT is not displayed correctly

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#770]
https://tzkt.io/ooi1x5UmJy5HicHvAVX1CAUnzqSV8DWWoceLQQ4MGuwXLhaBKYR/77145271/25

**Comment by ThierryThevenet** [comment]
it this one :
https://objkt.com/asset/KT1GD6QENFRTGo8rZXapdrHtiMzsZP8qZs1C/15

**Comment by ThierryThevenet** [comment]
this is this one https://objkt.com/asset/KT1GD6QENFRTGo8rZXapdrHtiMzsZP8qZs1C/15
it is correctly displayed in Naan but not in Temple (Metadat ?)

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  No meta data found for:
 KT1GD6QENFRTGo8rZXapdrHtiMzsZP8qZs1C

**Comment by ThierryThevenet** [comment]
I know but Naan found them !!!! try with the Naan wallet
I suppose they dont use tzkt to get data 

![File(2)](https://user-images.githubusercontent.com/32768069/192515921-9195bc5c-daac-4552-b880-1c72149508fa.jpg)

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  Yes, Naan used the OBJKT API instead of TZKT
I also asked a question to Tezos slack about some NFT metadata not shown in the result of API.
