### ISSUE TITLE
Beacon : swap does not run on https://spicyswap.xyz/#/swap

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#782]

**Comment by ThierryThevenet** [comment]
Probably same problem on another swap tezos website
https://app.youves.com/swap

**Comment by hawkbee1** [comment]
[Token buy with swap is failing#753](https://github.com/TalaoDAO/AltMe/issues/753)

**Comment by ThierryThevenet** [comment]
https://quipuswap.com/swap/KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb_0-tez

**Comment by hawkbee1** [comment]
Was able to do transaction today


![Image](https://user-images.githubusercontent.com/49282360/193757617-4c7423ca-7859-49b1-850f-cb7871e6b8da.png)

**Comment by bibash28** [comment]
https://github.com/bitmark-inc/autonomy-client/issues/384
