### ISSUE TITLE
VerifiiablePresentationRequest with DIDAUth does not work anymore

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#784]
{
    "type": "VerifiablePresentationRequest",
    "query": [
        {
            "type": "DIDAuth"
        }
    ],
    "challenge": "3c051fd8-3f30-11ed-8bda-0a1628958560",
    "domain": "https://talao.co/"
}

**Comment by ThierryThevenet** [comment]
and QueryByExample  does not work with several credentials

**Comment by hawkbee1** [comment]
Size: S
