### ISSUE TITLE
When user press on membership card from discover: check and warn user about credentials to present

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#785]

**Comment by hawkbee1** [comment]
if user don't have cards we tell user he must get required cards before.

**Comment by hawkbee1** [comment]
List of required credential types :

- CredentialSubjectType.ageRange
- CredentialSubjectType.nationality

Text for popup:
You need to get those credentials in your wallet to acquire membership card:
- Nationality Proof,
- Age Range Proof.

**Comment by hawkbee1** [comment]
S

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/193190639-817871f9-caee-41d6-892c-3c79ab7b8e14.png)
