### ISSUE TITLE
Beacon : after synchronization, we see the screen "Try again"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#794]
the synchro is fine but teh screen "Try again" is displayed

tested on https://rarible.com/

**Comment by bibash28** [comment]
When trying to buy nft:
error: Error while processing incoming messages: other(BeaconCore.HexString.Error.invalidHex(""))

**Comment by bibash28** [comment]
opened issue too:
https://github.com/bitmark-inc/autonomy-client/issues/329
