### ISSUE TITLE
Beacon does not work on swap on quipuswap

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#818]
https://quipuswap.com/swap/KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb_0-tez

**Comment by ThierryThevenet** [comment]
the swap causes probleme when we swap from a crypto (not a TEZ) with anothe crypto 
https://app.crunchy.network/#/swap?from=KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9_0&to=KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb_0

**Comment by hawkbee1** [comment]
[Beacon : swap does not run on https://spicyswap.xyz/#/swap#782](https://github.com/TalaoDAO/AltMe/issues/782)

**Comment by bibash28** [comment]
The issue occurs when I try to swap from non-tezos token to tezos. But swapping from tezos to non-tezos token is working fine...

**Comment by bibash28** [comment]
https://github.com/bitmark-inc/autonomy-client/issues/384#issuecomment-1297944810
