### ISSUE TITLE
Voucher and Memebership card vs Get It

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#824]
When a voucher/membership card is on the home screen the GET IT is removed
If the voucher/membership card is deleted the GET IT is displayed

**Comment by hawkbee1** [comment]
same thing as for Over18

**Comment by ThierryThevenet** [comment]
when tyeh card is deleted from home it does not appear on discover

**Comment by hawkbee1** [comment]
duplicate of Voucher and membership card is no more available in the Android build 75 #845
