### ISSUE TITLE
When create a new account switch to the new account

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#827]

**Comment by bibash28** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
does not work properly, grey box on top screen 


![Image](https://user-images.githubusercontent.com/32768069/196774322-4b6cef47-bd01-4d84-9f1b-dd081f5881f8.jpg)

**Comment by ThierryThevenet** [comment]
maybe the problem comes from the messages displayed on top
