### ISSUE TITLE
BEACON : when synchronize with beacon the "Connected dApps" screen is displayed

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#829]
dont eed t hat screen when we synchronize

**Comment by hawkbee1** [comment]
"Connected dApps" screen is shown only when user access it from drawer menu

**Comment by hawkbee1** [comment]
![Image](https://user-images.githubusercontent.com/49282360/194495880-0143a17a-ab73-4906-ab77-b16720abf79b.png)
