### ISSUE TITLE
When a wallet account receives a transfer from tz1YtKsJMx5FqhULTDzNxs9r9QYHBGsmz58o

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#834]
Display a lmessage "You ghave receive a  reward of .....USD"

**Comment by hawkbee1** [comment]
J'en parle avec Taleb ce matin pour savoir si on a déjà l'info, ce que je ne crois pas... A part quand on affiche l'activity.

**Comment by hawkbee1** [comment]
- A timer which check last  UNO and XTZ received
- When wallet receive tokens from tz1YtKsJMx5FqhULTDzNxs9r9QYHBGsmz58o we display message to user in popup: ""
- When wallet receive from tz1YtKsJMx5FqhULTDzNxs9r9QYHBGsmz58o  we store transaction id as lastNotifiedReward
- Timer is launch with the app for addresses of Tezotopia vouchers, on mainnet.

**Comment by hawkbee1** [comment]
M Size

**Comment by ThierryThevenet** [comment]
it does not work cotrrectly when you send xtz from temple for instance (with the correct address)

**Comment by ThierryThevenet** [comment]
request private key to romuald to test it

**Comment by ThierryThevenet** [comment]
It is ok for UNO transfer but it does not work with XTZ

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  Can you provide TransactionId? I want to check again

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  Can you provide TransactionId? I want to check again
