### ISSUE TITLE
Beacon : Give explanations to user when transactions through Beacon fail

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#842]
We need to give detail to user to avoid the standard  "This transaction...failed, try later..."
In particular if the reason of the failure is not due to Altme :

1: gas fees to low : -> text should be about increasing gas fees
2 : not enough cryptos to buy : say that user does not have enough cryptos
3 : dApp not responding

**Comment by hawkbee1** [comment]
Here is the error message list: https://tezos.gitlab.io/api/errors.html

**Comment by ThierryThevenet** [comment]
List :
1) Balance too low
An operation tried to spend more tokens than the contract has
Id : proto.alpha.contract.balance_too_low
Category : temporary

2)Cannot pay storage fee
The storage fee is higher than the contract balance
Id : proto.alpha.contract.cannot_pay_storage_fee
Category : temporary

3)Operation fees are too low
Operation fees are too low
Id : proto.alpha.prefilter.fees_too_low
Category : temporary

4) Operation fees are too low to be considered in full mempool
Operation fees are too low to be considered in full mempool
Id : proto.alpha.prefilter.fees_too_low_for_mempool
Category : temporary

5) Balance too low
Tried to spend a ticket index from an index without the required balance
Id : proto.alpha.tx_rollup_balance_too_low
Category : temporary

6) Attempted to transfer zero ticket
A transfer's amount must be greater than zero.
Id : proto.alpha.tx_rollup_invalid_zero_transfer
Category : temporary

7) Attempted to sign a transfer with an unknown address
The address must exist in the context when signing a transfer with it.
Id : proto.alpha.tx_rollup_unknown_address
Category : temporary

8) Inactive chain
Attempted validation of a block from an inactive chain.
Id : node.validator.inactive_chain
Category : branch

**Comment by ThierryThevenet** [comment]
difficult to test
