### ISSUE TITLE
Reward message for UNO and XTZ to chek with Hugo

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#846]

**Comment by HugoNDO** [comment]
<img width="369" alt="Capture d’écran 2022-10-11 à 09 50 12 (1)" src="https://user-images.githubusercontent.com/108657151/195032700-3d2192fe-9bc7-4bca-8af6-a8fe3f948f77.png">

**Comment by HugoNDO** [comment]
=> Link on "tz1aXD7..." towards : Tezos block explorer

**Comment by hawkbee1** [comment]
size: S
