### ISSUE TITLE
Change splash screen and the 3 slides

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#848]
@hawkbee1 add screenshots from Hugo marketing

**Comment by ThierryThevenet** [comment]
<img width="1094" alt="Capture d’écran 2022-10-04 à 18 42 19" src="https://user-images.githubusercontent.com/32768069/194837991-5f4a4f75-c08c-42b5-ab32-f9a59f5df258.png">

**Comment by hawkbee1** [comment]
@HugoNDO Je ne met pas "NFT" dans le splash histoire de ne pas se faire encore jeter par Apple
