### ISSUE TITLE
Add a title to "My Wallet" page

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#852]
V2 designs have page title for "My Wallet" and "Discover". For the moment, only the page "Discover" has a title. We need to add one to the "My Wallet" page : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2436%3A8110
 
<img width="724" alt="Capture d’écran 2022-10-10 à 18 25 36" src="https://user-images.githubusercontent.com/108657151/195034033-43b65517-d4e0-4abf-86e6-6ae5d796b79a.png">

**Comment by ThierryThevenet** [comment]
to be discussed as the information part of the screen is quite small. We cannot display more than 6 credentials or 6 NFTs at the moment

**Comment by hawkbee1** [comment]
Size: M
