### ISSUE TITLE
Add a "My" in front of every category in "My wallet" + Add a "Get" in front of every category in "Discover"

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#854]
<img width="894" alt="Capture d’écran 2022-10-10 à 18 18 09" src="https://user-images.githubusercontent.com/108657151/195035439-3eb6e1fc-1559-46d6-b378-e811401a5b8e.png">

**Comment by hawkbee1** [comment]
Rajouter "My"....
Add "My" in front of every category title in My Wallet

Rajouter "Get"...
Add Get in front of every category title in Discover

**Comment by hawkbee1** [comment]
Size: S
