### ISSUE TITLE
Add information in "Choose Network" 

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#856]
Choose network information to add to be more precise for users : 

Title : Tezos Main Network (= Mainnet)
Paragraph : This network is the official Tezos blockchain running Network. You should use this network by default.

Title : Tezos Test Network (= Testnet)
Paragraph : This network is used to test protocol upgrades (do not use it unless you are a developer).

=> This modification needs to be applied in the drawer AND in the Tokens network selection

<img width="457" alt="Capture d’écran 2022-10-10 à 10 41 08" src="https://user-images.githubusercontent.com/108657151/195037150-fef28c4d-b5ee-43a8-8f92-e26f71ce21a1.png">

**Comment by hawkbee1** [comment]
title: Tezos Mainnet
title: Tezos Ghostnet

**Comment by hawkbee1** [comment]
Size: S
