### ISSUE TITLE
Details for cards in Discover (several screens to implement but no logic)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#863]
The objective is to give information about the credential utility in the Discover area.
For most of the cards it is just before the KYC process and it replaces the screen before the Passbase first screen.
[ALTME CARD DETAILS for DISCOVER.pdf](https://github.com/TalaoDAO/AltMe/files/9757943/ALTME.CARD.DETAILS.for.DISCOVER.pdf)

**Comment by HugoNDO** [comment]
Why get this card : This proof may be required by some Web 3 Apps / Websites to access their service or claim benefits : Membership card, Loyalty card, Rewards… 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : It’s super easy. Altme will verify your email ownership by sending a code by email. 

------

Website game : https://tezotopia.com 

Why get this card : This Membership card will give you 25% cash backs on ALL Tezotopia Game transactions when you buy a Drops on the marketplace or mint an NFT on starbase.  
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You need to present a Nationality Proof and an Age Range Proof. Claim them by following Altme’s KYC check.  

------

Why get this card : This proof may be required by some Web 3 Apps / Websites to access their service or claim benefits : Membership card, Loyalty card, Rewards, etc. 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check.  ------

Why get this card : This proof may be required by some Web 3 Apps / Websites to access their service or claim benefits : Membership card, Loyalty card, Rewards… 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check.

 ------

Why get this card : This Passeport footprint contains a unique number associated to you.  It may be required to prove that you vote only one time in a DAO, etc. 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check.  

------

Why get this card : This digital identity card contains the same information as your physical ID card. You can use it in Web 3 for a KYC check for example. 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check. 

------

Why get this card : This proof may be required by some Web 3 Apps / Websites to access their service or claim benefits : Membership card, Loyalty card, Rewards… 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : It’s super easy. Altme will verify your email ownership by sending a code by SMS.  

------

WebsIte game : https://tezotopia.com 

Why get this card : This Voucher card will give you 10% cash backs on ALL Tezotopia Game transactions when you buy a Drops on the marketplace or mint an NFT on starbase.  
Expiration date : This card will remain active and reusable for 30 days. 

How to get it : It’s super easy. You can claim it for free right now.  

------

Why get this card : This Gender Proof is useful to prove your gender (Male / Female) without revealing any other information about you. It can be used in a user survey, etc. 
Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check. 

------

Why get this card : This credential is useful to prove your Nationality without revealing any other information about you. It can be required by Web 3 Apps in a user survey, etc. 

Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check.  

------

Why get this card : This credential is useful to prove your Age Range without revealing any other information about you. It can be required by Web 3 Apps in a user survey or to claim benefits : Membership card, etc.

Expiration date : This card will remain active and reusable for 1 YEAR. 

How to get it : You can claim this card by following Altme’s KYC check.

**Comment by bibash28** [comment]
Size: M
