### ISSUE TITLE
Add activity in tab for card detail

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#865]
https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2351%3A10634

**Comment by hawkbee1** [comment]
Size: M

**Comment by HugoNDO** [comment]
+ Status : Active / Inactive in "Informations" (not separated anymore)
+ "Activity" should only display the data of presentation (first) and then the name of the organization => Display with the most recent activity at the top (= sort by presentation date with the most recent at the top)
