### ISSUE TITLE
same design to be used

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#867]
Those 2 screens have the same kind of function, they should get the same design, size, police, same text and button color, etc

Use the first screen style for both screens, no checkbox needed

![IMG_7132](https://user-images.githubusercontent.com/32768069/195408937-c7847456-a6e1-46fb-ab78-57f319a48694.jpeg)

![IMG_7131](https://user-images.githubusercontent.com/32768069/195408951-2c24db2b-daea-4142-9507-6359bd8e5d4d.jpeg)

**Comment by hawkbee1** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
color should be the same and there should be a checkbox in both or no checxbox at all in both. see with hugo what design we chose.

**Comment by ThierryThevenet** [comment]
The design is still same as before ????
We need same color (purple) for both screens and remove the checkbox to get the same style in both screens

**Comment by ThierryThevenet** [comment]
not visible on last build

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  Can you let me know where you checked the pop-up? in Which part of the app?
