### ISSUE TITLE
Change text above credentials in credentialOffer

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#902]
See below :
The first phrase " "Select your Tezos associated wallet" must be removed
The second pĥrase is the "reason" attribute of the credential manifest (one different by credential).
We want to display only one phrase :

If "reason" exists , display the reason text if not display "Select your credential"

![File(1)](https://user-images.githubusercontent.com/32768069/196757434-5444d27a-af58-4896-b584-d8a6be79b619.jpg)

**Comment by bibash28** [comment]
Size: S
