### ISSUE TITLE
Beacon : sign Payload does not work, grey screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#908]

**Comment by ThierryThevenet** [comment]
see https://talao.co/sandbox/saas4ssi/dapp

**Comment by bibash28** [comment]
![image](https://user-images.githubusercontent.com/18188709/197120316-f5857846-6f3b-4bd3-b487-7a07cfc0544f.png)

**Comment by bibash28** [comment]
https://docs.walletbeacon.io/guides/sign-payload/

The format of payload is incorrect... @hawkbee1  @ThierryThevenet

**Comment by bibash28** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/18188709/197121959-8e42f9bd-497b-4ff5-a99b-f08cbca7733d.png">

**Comment by bibash28** [comment]
'test'
=>
05010031363254657a6f73205369676e6564204d6573736167653a20626561636f6e2d746573742d646170702e6e65746c6966792e6170702f20323032322d31302d32315430353a34353a32362e3931315a2074657374

**Comment by bibash28** [comment]
Size: S

**Comment by bibash28** [comment]
Talao Example Dapp sigining with temple
![Image](https://user-images.githubusercontent.com/18188709/197168077-8f88c94f-6aa3-44ae-bc58-6adb0551924f.png)

**Comment by bibash28** [comment]
Beacon Example Dapp sigining with temple



![Image](https://user-images.githubusercontent.com/18188709/197168246-c346a436-dba9-47cd-b444-6ae2b8816f76.png)
