### ISSUE TITLE
 build 84, credentialOffer loops on select credential

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#914]
sometimes it request several times the same credentials and several cards are issued.

you can it with https://talao.co/sandbox/op/issuer/rhvlluqbxx

**Comment by ThierryThevenet** [comment]
server track 1 GET and 4 POST
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:14 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:22 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:26 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:31 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:31 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:31 ip-172-31-37-180 gunic

**Comment by ThierryThevenet** [comment]
Server log : 1 GET and 4 POSTs
Oct 22 16:32:06 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:06 +0000] "GET /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 2457 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:14 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:14 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:22 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:22 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:26 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:26 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"
Oct 22 16:32:31 ip-172-31-37-180 gunicorn[3664]: INFO:root:credential signed by did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5
Oct 22 16:32:31 ip-172-31-37-180 gunicorn[3664]: INFO:root:signature ok
Oct 22 16:32:31 ip-172-31-37-180 gunicorn[3664]:  - - [22/Oct/2022:16:32:31 +0000] "POST /sandbox/op/beacon/ormmcdomjv?issuer=did:ethr:0x64098e894fea5b83e7e4c52a30d70b98e25bd9d5 HTTP/1.0" 200 1706 "-" "Dart/2.18 (dart:io)"

**Comment by bibash28** [comment]
![image](https://user-images.githubusercontent.com/18188709/197450811-f4da72b3-f2fb-4fe8-b69c-9c3ccdfeb17b.png)
