### ISSUE TITLE
Beacon : start credentialOffer with Beacon 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#916]
We use the RAW signing type with a message that includes the QRcode URL  :
dApp code is :
const signature = await client.requestSignPayload({
          signingType: beacon.SigningType.RAW,
          payload: 'Get your Tezotopia voucher ! #https://talao.co/sandbox/op/beacon/kmjdgmvtpu?issuer=did:tz:tz1NyjrTUNxDpPaqNZ84ipGELAcTWYg6s5Du'
               }) 
The QRcode URL starts after the fragment (#) 

There are 3 examples for testing on https://talao.co/sandbox/saas4ssi/dapp which are the 3 green buttons

**Comment by ThierryThevenet** [comment]
add possibility to accept MICHELINE and OPERATION signing type

**Comment by hawkbee1** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
it crashed app on IOS

**Comment by ThierryThevenet** [comment]
same issue with build 86 ios 1.3.3
none of the green button works on https://talao.co/sandbox/saas4ssi/dapp
