### ISSUE TITLE
connect and delegates: crashes app..

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/AltMe#918]

**Comment by hawkbee1** [comment]
Thierry ask fot not crashing and display message:

**Comment by hawkbee1** [comment]
duplicate [Beacon : follow up with test dapp : Delegate creashes#909](https://github.com/TalaoDAO/AltMe/issues/909)

**Comment by hawkbee1** [comment]
duplicate https://github.com/TalaoDAO/AltMe/issues/909
