### ISSUE TITLE
Customer support for app

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#920]
we need a solution to manage usert interaction with us .

maybe https://docs.desk360.com/sdk/desk360-flutter-sdk ?
or equivalent

**Comment by hawkbee1** [comment]
desk 360 devait devenir payant l'année dernière, c'est bizarre de ne toujours pas voir de grille tarifaire, juste un "free for now"

**Comment by hawkbee1** [comment]
Donner la possibiliter de nous contacter depuis l'appli

**Comment by hawkbee1** [comment]
https://github.com/MyEtherWallet

**Comment by hawkbee1** [comment]
Size: XL

**Comment by HugoNDO** [comment]
See what MEW Wallet is using for customer support : https://github.com/MyEtherWallet

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/201607724-2f6f5608-3b91-4fd0-9a13-3b116696eee4.png)



![Image](https://user-images.githubusercontent.com/18188709/201607884-b960c3e9-f6b7-4407-bcf5-382c06293ef5.png)



![Image](https://user-images.githubusercontent.com/18188709/201607813-5eb780ca-e0ab-4ed6-9414-263d3dda04cc.png)



![Image](https://user-images.githubusercontent.com/18188709/201607845-b5165b18-4617-41a4-9949-96f9879c9b2b.png)



![Image](https://user-images.githubusercontent.com/18188709/201607933-e7e694ee-67ec-484b-b889-0491a0f20a02.png)



![Image](https://user-images.githubusercontent.com/18188709/201607766-f2f5b31d-1fe1-4e32-a6d7-94b6a7842adb.png)



![Image](https://user-images.githubusercontent.com/18188709/201607946-40d3ccb8-3516-49fc-90a1-491f705b953d.png)



![Image](https://user-images.githubusercontent.com/18188709/201607915-0a7ed56a-d8ea-44ca-84f2-8a627e95fa3a.png)



![Image](https://user-images.githubusercontent.com/18188709/201607962-71b728eb-86f7-4f95-86aa-5bede6fd7635.png)



![Image](https://user-images.githubusercontent.com/18188709/201607788-59d8ede9-8c1f-46ae-ae40-4fab2933efc1.png)

**Comment by bibash28** [comment]
![Image](https://user-images.githubusercontent.com/18188709/201650198-0301475f-35f9-4e2f-aa5d-6470e0b65c66.png)

**Comment by bibash28** [comment]
![image](https://user-images.githubusercontent.com/18188709/201821531-d24dd896-a420-44b6-a7c6-f49e646d633e.png)

**Comment by bibash28** [comment]
https://github.com/Teknasyon-Teknoloji/desk360-flutter-sdk/issues/3

**Comment by ThierryThevenet** [comment]
we will not use desk360, one can remove the lib
