### ISSUE TITLE
Get Over13 credential through yoti (AI age estimation)

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#921]
1/ User press on button from discover to get Over13
2/ Popup or credential If user has successfully done KYC he's getting his credential the usual way.
If user don't have KYC a popup explain him he will take a selfie to get AI validation.
3/ User take selfie
4/ Selfie is sent to backend with DID
5/ App is checking  credential availability (time base loop)
6/ App add Over13 credential

**Comment by ThierryThevenet** [comment]
+ Over18 and age range 
+ the card must be a bit different as it is not the same assurance
+ biometric before selfie and after selfie with limited time to do the all process to avoid fraud
+ it looks like it is synchrone so probably no pull
