### ISSUE TITLE
Option "None" in Issuer Registry

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#934]
If None is chosen, do not check Issuer registry (do not call API to get issuer data and do not ask "Do you trust that host"
By defaul None is selected

**Comment by hawkbee1** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
set None as Default in Registry

**Comment by hawkbee1** [comment]
@TalebRafiepour "None" is by default and working correctly.
Have regression with EBSI which is strucked.

![Image](https://user-images.githubusercontent.com/49282360/198613925-9f7a24e8-b735-4e72-bebf-6ac042cff305.jpg)
