### ISSUE TITLE
Add type LearningAchievement to Diploma card

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#935]

**Comment by bibash28** [comment]
@ThierryThevenet @hawkbee1 

We only have the following categories...

enum CredentialCategory {
  gamingCards,
  identityCards,
  communityCards,
  proofOfOwnershipCards,
  passCards,
  othersCards
}

**Comment by bibash28** [comment]
Learning achievement in identity category

**Comment by bibash28** [comment]
Size: S

**Comment by bibash28** [comment]
@ThierryThevenet @hawkbee1 learning achievement is already in the identity category??  What is this ticket about?
