### ISSUE TITLE
Does not work anymore with rarible

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#936]

**Comment by bibash28** [comment]
https://github.com/autonomy-system/beacon-android-sdk/commit/5b0245187d66c8d82f5c3201a9326f15bbb8a9b1

**Comment by bibash28** [comment]
https://github.com/autonomy-system/beacon-ios-sdk/commit/6f8f8d74e393677ba47766b9dccdddeccba1ece0
