### ISSUE TITLE
credential manifest for self issued tezosassociatedaddres

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#939]
https://github.com/TalaoDAO/wallet-tools/blob/main/credential_manifest/TezosAssociatedAddress_credential_manifest.json

**Comment by hawkbee1** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
not done ?

**Comment by ThierryThevenet** [comment]
issuedBy.name = "My Wallet"  as it is a  self issued

**Comment by ThierryThevenet** [comment]
here is the credential jsonld https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/TezosAssociatedAddress.jsonld

**Comment by ThierryThevenet** [comment]
not visible on last build

**Comment by TalebRafiepour** [comment]
@ThierryThevenet  Did you create a new account and test it?
