### ISSUE TITLE
New design for onboarding

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#941]

**Comment by HugoNDO** [comment]
![Onboarding _ start (1)](https://user-images.githubusercontent.com/108657151/198214952-eed43dda-d2bf-46e7-b453-f16e0af0c359.png)

![Onboarding _ Create PIN code](https://user-images.githubusercontent.com/108657151/198214960-05568b34-8a49-4ae8-8432-277e4492bd1e.png)

![Onboarding _  Confirm PIN code](https://user-images.githubusercontent.com/108657151/198214983-dae3c4dd-9d78-4e9f-8586-635d728532a8.png)

![Onboarding _ Activation Biometric](https://user-images.githubusercontent.com/108657151/198214992-8b61314a-d8fb-452f-a334-18943f1d847b.png)

![Onboarding _ Activation Biometric (1)](https://user-images.githubusercontent.com/108657151/198215015-a91d33ec-a82f-4b6b-9c6a-171afbca41a5.png)

![Onboarding _ recovery phares](https://user-images.githubusercontent.com/108657151/198215035-675956b4-2079-4e96-b97f-8a5dd58d542c.png)

![Onboarding _ Congratulation _ Create wallet](https://user-images.githubusercontent.com/108657151/198215064-4d9cbb11-8ccb-4009-a591-984dc81d9252.png)

![FrameOnboarding _ Congratulation _ Create wallet _ Check terms 185](https://user-images.githubusercontent.com/108657151/198215092-66989c27-7059-4571-90a9-6938615fc70d.png)

![Onboarding _ Terms](https://user-images.githubusercontent.com/108657151/198215120-83690aa1-cc28-489f-bdbb-6ce63f1537c6.png)

![Create wallet _ Terms _ uncheck](https://user-images.githubusercontent.com/108657151/198215144-21b937bb-7747-48ed-ae8c-3fc1ec5dc4d8.png)

**Comment by HugoNDO** [comment]
1) Do not take into account first screen design for the moment, we are working on a new version for this one. I added the 1st screen just to help you understand the new onboarding process. 

2) The "congrats" screen should have an **animation background**

**Comment by hawkbee1** [comment]
Size: XL

**Comment by HugoNDO** [comment]
Here is the final version : https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=3732%3A9425
