### ISSUE TITLE
In Discover, sentence font should not be bigger than card title

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#943]
Screenshot : 
<img width="380" alt="Capture d’écran 2022-10-27 à 09 22 20" src="https://user-images.githubusercontent.com/108657151/198217523-468f17b0-7d64-40a5-9151-3671a8569470.png">

How it should be : Roboto 24px
<img width="596" alt="Capture d’écran 2022-10-27 à 09 17 08" src="https://user-images.githubusercontent.com/108657151/198217116-686d3805-891b-43b3-8d3c-b5cb3c0fab6d.png">

**Comment by bibash28** [comment]
Size: S
