### ISSUE TITLE
extension of the "pattern" attribute of credential manifest ( credentialOffer)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#944]
we need to allow user to select any credentials with a type which ends with "Address"  as "TezosAssociatedAddres" or "TezosLinkedAddress" or "EthereumAssociatedAddress"

we use regex json schema https://howtodoinjava.com/java/regex/start-end-of-string/ 
see : "word$" -> to get all strings finishing by "word"

in the credential manifest : 
constraints": {
                            "fields": [
                                {
                                    "path": ["$.type"],
                                    "filter": {
                                        "type": "string",
                                        "pattern": "Address$"
                                    }
                                }
                            ]

**Comment by ThierryThevenet** [comment]
have to check other solutions

**Comment by hawkbee1** [comment]
Credential manifest should already allow such filtering because we are using given jsonPath.
