### ISSUE TITLE
CredentialOffer : Select VCs based on an attribute only  

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#949]
Need to support :
"constraints": {
                            "fields": [
                                {"path": ["$.credentialSubject.associatedAddress"]}
                                ]}}

For testing :
1) collect an ethereum associated address or Linked address VC on https://talao.co/sandbox/playground
2) issuer : https://talao.co/sandbox/op/issuer/fufuoervtu

**Comment by hawkbee1** [comment]
Size: S

**Comment by hawkbee1** [comment]
@ThierryThevenet l'issuer me renvoie à https://talao.co/sandbox/op/issuer_endpoint/fufuoervtu/8899fe0c-7c77-11ed-b281-0a1628958560?issuer=did:tz:tz1NyjrTUNxDpPaqNZ84ipGELAcTWYg6s5Du qui retourne une erreur 404
