### ISSUE TITLE
"In my wallet" and "Get it" information under cards in Discover or My Wallet are not useful anymore

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#956]
<img width="230" alt="Capture d’écran 2022-11-02 à 15 00 15" src="https://user-images.githubusercontent.com/108657151/199509871-b86a08d3-28b0-403d-85b0-6e56af0d0a96.png">

<img width="224" alt="Capture d’écran 2022-11-02 à 15 00 05" src="https://user-images.githubusercontent.com/108657151/199509879-60c90207-bb65-40af-b058-753025133f5c.png">

**Comment by hawkbee1** [comment]
Size: S
