### ISSUE TITLE
AUDIT : Update API token value for wallet call to issuer.talao.co

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#969]
Change the value for the following endpoints 

https://issuer.talao.co/passbase/webhook'   authorization token

https://issuer.talao.co/passbase/check/<did>  authorization token

https://issuer.talao.co//ai/over13     X-API-KEY  
https://issuer.talao.co//ai/over18     X-API-KEY

https://issuer.talao.co/token  X-API-KEY 

Request Thierry to get the transfered by slack

**Comment by hawkbee1** [comment]
Size: S
