### ISSUE TITLE
IOS build, Text in first 2 screens (splash screen) is displayed  differently (Iphone X)

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#970]
![IMG_7193](https://user-images.githubusercontent.com/32768069/200126340-862ff1f9-0d77-4f9a-8463-d1b7072a94b0.jpeg)
![IMG_7194](https://user-images.githubusercontent.com/32768069/200126341-39396145-fcce-4ead-b120-213f9cb5a130.jpeg)

**Comment by ThierryThevenet** [comment]
and button "Create wallet" is too close to bottom bar

**Comment by bibash28** [comment]
Size: S
