### ISSUE TITLE
Change text "ID Verification pending"

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#972]
See the screenshot below :
![Capture d?ecran   202 2-11-07 à 15 29 20](https://user-images.githubusercontent.com/108657151/200322888-46985f01-6cff-4421-9928-a72e28401980.png)

New Title : Your ID verification is pending
New text : Usually it takes less than 5 min to get verified. You will receive an email when the verification is complete.

**Comment by bibash28** [comment]
Size: S
