### ISSUE TITLE
remove the word "Test" of that screen

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#976]

**Comment by ThierryThevenet** [comment]
<img width="468" alt="Capture d’écran 2022-11-07 à 14 19 23" src="https://user-images.githubusercontent.com/32768069/200363269-38d5bb84-bf3f-4c33-aecd-7a55c3042040.png">

**Comment by hawkbee1** [comment]
Size: S

**Comment by bibash28** [comment]
This issue is occurring from the server..

JSON Value:
"givenName": "Test"
