### ISSUE TITLE
AI for age range 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#983]
https://issuer.talao.co/ai/agerange

**Comment by hawkbee1** [comment]
Figma look: https://www.figma.com/file/gNQ9POVTHhxZQbzRQl6Qks/Altme?node-id=2385%3A28567&t=KXUbBs1TbFuP7UAy-0

**Comment by hawkbee1** [comment]
@HugoNDO we need texts for age range description in Discover

**Comment by hawkbee1** [comment]
@hawkbee1 get json-ld definition
