### ISSUE TITLE
Add consent screen in yoti process and send screenshot to yoti

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#992]
[Consent collection messaging.pdf](https://github.com/TalaoDAO/AltMe/files/9980589/Consent.collection.messaging.pdf)

@HugoNDO I think you have material for the explanation screen when user choose to use yoti

**Comment by hawkbee1** [comment]
I think that's OK with last design version

**Comment by ThierryThevenet** [comment]
grey screen
