### ISSUE TITLE
Implement wallet connect as we have done with beacon

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#997]
https://pub.dev/packages/walletconnect_dart

Maybe
https://pub.dev/packages/wallet_connect
https://pub.dev/packages/flutter_web3

**Comment by ThierryThevenet** [comment]
look for Dart package for WalletConnet 2.0 (multi chain)
if not we will use WalletConnect 1.0

**Comment by bibash28** [comment]
Size: XL
